codecov/gazebo

- src/services/trial/useStartTrial.spec.tsx
- src/services/trial/useStartTrial.ts
Small little update to change location where `owner` comes from.
- Quick update to `useStartTrial` to take `owner` as arg for `mutate` function
- Update tests
> Update useStartTrial to take Owner as Mutation Arg (CODE-3625)

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.spec.jsx
With the introduction of codecov trial, we no longer need to ask for the credit card when you're under our old trial. This Pr removes the need for that.
Caveat: do not merge this until the whole trial initiative is in.
- Removed the ask for credit card info in the upgrade page once you're trialing and adjusted the test for it
- Adjusted trialstatuses never_trialed value to cannot_trial as that's the expected API value
> ref: Remove ask for credit card when trialing

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.spec.jsx
- src/shared/utils/upgradeForm.js
- src/shared/utils/upgradeForm.spec.js
Since we're giving a vast amount of seats when users are trialing we can't block them from upgrading to an amount of seats that is lower then the current activated amount so this bypasses that check in the form resolver.
- Update `getSchema` function to return bypass the seat count vs activated member check if the current plan is on trial and trial is currently ongoing.
- Update `UpgradeForm` to pass along `trialStatus` value
- Update tests
> fix: Adjust Upgrade Plan Form Resolver When Seat Count is Lower then Activated Members (CODE-3642)

- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.spec.tsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.tsx
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.tsx
Quick fix to make sure ongoing banner does not display when the date difference is less then zero
- Add check for `dateDiff >= 0` in `TrialBanner`
- Update tests
> fix: Hide Ongoing Banner if Date Diff is Less Then 0 (CODE-3649)

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateButton/UpdateButton.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateButton/UpdateButton.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.spec.jsx
Because we're moving the ability to start the trial to the plan page, and also allowing users to start paying right away it was required that we remove any mention of trials from the upgrade page.
- Remove trial related stuff from `UpgradeForm`
- Remove trial related stuff from `UpgradeButton`
- Update Tests
> ref: Remove Any Mention of Trials on the Upgrade Page (CODE-3651)

- src/pages/PlanPage/subRoutes/CancelPlanPage/CancelPlanPage.jsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/CancelPlanPage.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeDetails/UpgradeDetails.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeDetails/UpgradeDetails.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.spec.jsx
- src/shared/utils/upgradeForm.js
- src/shared/utils/upgradeForm.spec.js
We've decided that users should not be able to access the cancel
- Update `shouldRenderCancelLink` to return `false` when user is on a trial
- Update `UpgradeDetails` to fetch trial status and pass values through to `shouldRenderCancelLink`
- Update `CancelPlanPage` to redirect users away when on trial
- Update tests
> ref: Hide Cancel Link While User is On a Trial (CODE-3645)

- src/pages/PlanPage/hooks/usePlanPageData.js
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/CurrentPlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/CurrentPlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/index.ts
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.spec.jsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStatickNavLinks.spec.js
- src/ui/Button/Button.jsx
To make it easier for users to start trials, or directly upgrade to a pro version we're making some slight changes to the base plan, and if the user is eligible for a trial they will now see a `Start Trial` button, or a link `upgrade now` which they can directly upgrade to a pro version. While the user is on a trial they will also be able to upgrade right away if they wish to do so. If the users trial expires they will be informed of the plan that they trialed.
- Display `FreePlanCard` if user is on a trial plan
- Create new `ProPlanSubheading` component that handles the variety of states that the sub-heading may be in
- Update `FreePlanCard` to use new `ProPlanSubheading` 
- Update free plan card sub-heading text if the user is currently on trial in `FreePlanCard`
- Update …
> feat, fix: Add New Trial Logic to Plan Page (CODE-3587)

- src/pages/MembersPage/MembersActivation/Activation/Activation.spec.jsx
- src/pages/MembersPage/MembersActivation/MembersActivation.spec.jsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.spec.tsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/CancelPlanPage.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeDetails/UpgradeDetails.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.spec.jsx
- src/services/account/usePlanData.spec.tsx
- src/services/account/usePlanData.ts
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.spec.tsx
Because the free plan card currently displays the current benefits the user has on their account this would display the trial plan benefits but that's not whats supposed to be displayed. So the API will have a new field introduced that will allow us to get the information for the plan the user had previously.
- Update `usePlanData` to fetch the pre-trial info
- Update `FreePlanCard` to display the pre-trial benefits if the user is currently on a trial
- Update tests
Closes codecov/applications-team#66
> fix: Display Pre-Trial Benefits on Downgrade Card (CODE-3647)

- README.md
Replaces Open Source in Readme
> Replace "open source" in README.md

- src/pages/MembersPage/MembersActivation/Activation/Activation.jsx
- src/pages/MembersPage/MembersActivation/Activation/Activation.spec.jsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.spec.tsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateButton/UpdateButton.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateButton/UpdateButton.tsx
- src/shared/GlobalTopBanners/TrialBanner/OngoingBanner.tsx
This PR updates a few pieces of text requested after a walk through of the trial was completed.
Closes: codecov/applications-team#130
- Update `UpdateButton` on the upgrade page to show `Proceed to Checkout`
- Update the downgrade message in the `FreePlanCard`
- Update Owner page trial CTA while the trial is ongoing
- Update `OngoingBanner` left and right side text
- Update copy on the members page activation section
- Update tests
> Copy Updates for Trial

- .env.development
- src/layouts/Header/DesktopMenu.spec.jsx
- src/layouts/Header/Dropdown.spec.jsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.spec.jsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
if i run Codecov locally and load `localhost:3000/login/gh` and click the "login" button, it sends me to `localhost:3000/login/gh` which is where i already was and nothing happens. if i modify it to send me to `localhost:8000/login/gh`, which is my local API instance, it will send me to a GitHub authorization page as i'd expect.
i don't understand why this isn't a problem in staging and production. am i missing anything?
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by …
> fix/rfc: use API_URL instead of BASE_URL for auth button hrefs

- .env.development
- src/layouts/Header/DesktopMenu.spec.jsx
- src/layouts/Header/Dropdown.spec.jsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.spec.jsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
> Revert "fix/rfc: use API_URL instead of BASE_URL for auth button hrefs"

- src/pages/PullRequestPage/Header/Header.spec.jsx
- src/pages/PullRequestPage/Header/PendoLink.spec.tsx
- src/pages/PullRequestPage/Header/PendoLink.tsx
- src/pages/PullRequestPage/PullRequestPage.spec.jsx
Quick PR to remove the Pendo modal flag that's located on the PR page as it has been fully rolled out.
- Remove flag from `PendoLink` component
- Update tests to remove flag mock
> ref: Remove Pendo Modal PR Page Flag

- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Badges/Badges.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Badges/Badges.spec.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/BadgesAndGraphsTab.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/BadgesAndGraphsTab.spec.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Graphs/Graphs.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Graphs/Graphs.spec.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Graphs/URLEmbed.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Graphs/useGraphsDetails.js
People need a way to default urls to default branch without having to hard code it in the URL, we support default to repo.branch in the API so an easy fix was to remove default branch. 
Remove default branch from URLs
Fix tests
any repo settings.
Issue: https://github.com/codecov/engineering-team/issues/306
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
> ref: Remove default branch from badges and graphs 

- src/services/user/useResyncUser.js
- src/services/user/useResyncUser.spec.js
For the onboarding page, we want to invalidate the `UseMyOrganizations` query when syncing users.
- Adjusted resync user hook + tests
> Invalidate UseMyOrganizations query

- src/layouts/BaseLayout/BaseLayout.jsx
- src/layouts/BaseLayout/BaseLayout.spec.jsx
Impersonation accounts are struggling with the default org selector screen; this is a quick fix for that.
- Added an impersonation check for codecov users to bypass the default org selector screen
> feat: Allowing impersonation to bypass default org selector

- .github/workflows/alpha.yml
- .github/workflows/client-release.yml
- craco.config.js
Setting up sentry config for releases in other envs
> Setting up sentry config for releases in other envs

- src/shared/GlobalTopBanners/TrialBanner/OngoingBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/OngoingBanner.tsx
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.spec.tsx
Quick copy change to the ongoing trial banner. 
Closes codecov/engineering-team#399
- Update `OngoingBanner` to render different text based on `dateDiff` being `<= 1`.
- Update `OngoingBanner` to say `Upgrade now` instead of just `upgrade`
- Update tests.
> style: Pluralize Trial Days Message

- src/config.js
- src/config.spec.js
- src/pages/AccountSettings/AccountSettings.jsx
- src/pages/AccountSettings/AccountSettings.spec.jsx
- src/pages/AccountSettings/AccountSettingsSideMenu.jsx
- src/pages/AccountSettings/AccountSettingsSideMenu.spec.jsx
- src/pages/AccountSettings/tabs/Access/Access.jsx
- src/pages/AccountSettings/tabs/Access/Access.spec.jsx
Currently when running in self hosted mode the access tab on the account settings page is currently hidden, some customers are looking to use this access tab while others are looking to keep it hidden so this is an option that will allow it to be toggled per customer.
Closes #2199 
- Add check for `config.HIDE_ACCESS_TAB` in `AccountSettings`
- Update tests.
> feat: Add Configuration Option to Toggle Access Tab

- src/pages/PullRequestPage/Summary/CompareSummary.jsx
- src/pages/PullRequestPage/Summary/CompareSummary.spec.jsx
The compare message displayed an extra 0 'cus of a bad `&&`
/gh/codecov/codecov-api/pull/1623
> fix: Remove 0 from source data

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.tsx
Another day ... another PR removing trial flag things, this time from the `ProPlanSubheading` component.
- Remove trial flag from `ProPlanSubheading` component
- Update tests
> ref: Remove Trial Flag from from ProPlanSubheading

- src/ui/CodeRenderer/CodeRenderer.css
- src/ui/CodeRenderer/CodeRenderer.tsx
- src/ui/CodeRenderer/CoverageLineIndicator/CoverageLineIndicator.jsx
- src/ui/FileList/FileList.css
- src/ui/FileList/FileList.stories.tsx
- src/ui/Table/Table.css
- src/ui/Table/TableSorting.stories.tsx
Less documentation then the Tableui, migration/DX is more or less identical, different HTML markup requirements (not using a proper table). I made a fairly polished demo in storybook.
* Converted CodeRenderer to typescript
* Tweaked/improved TableUI style/examples if I found something better.
* Code renderer styles were affecting things outside of itself, added a classname to scope it down to only it.
* Added expanded support to table + file list
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to …
> Setup a fileviewer list to replace old table

- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/DefaultBranch/DefaultBranch.spec.jsx
- src/services/branches/useBranches.js
The API returns only unmerged branches by default which is nice in that it keeps the branch selector fairly tidy and relevant to current work.  When we're searching for a specific branch we'd like to search across merged branches as well.  This passes the necessary GraphQL resolver filter in that case.
From https://github.com/codecov/codecov-api/issues/96
> feat: Branch dropdown search merged + unmerged branches

- src/ui/A/A.jsx
Sanitize url in `A` as per https://github.com/codecov/gazebo/issues/2164
- Adjusted string evaluation + tests
> 2164 url sanitization

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.spec.jsx
Another day another PR removing the trial flag, this time from the `ActionsBilling` component. I thought I'd also update the test `setup` function to take a object argument so that if we need to add another flag in it's not a positional argument which isn't fun to clean up.
- Remove flag from `ActionsBilling` component
- Update tests, including swapping to obj arg for `setup`
> ref: Remove Trial Flag from Actions Billing

- src/services/user/useInternalUser.ts
Super small PR changing the schema type from `string` to `number`.
> fix: Switch integrationId to a Number from String Type

- src/shared/GlobalTopBanners/TrialBanner/ExpiredBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/ExpiredBanner.tsx
- src/shared/GlobalTopBanners/TrialBanner/OngoingBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/OngoingBanner.tsx
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.spec.tsx
We display 0 days if there are less than 24 hours left for the trial period, this is updating the trial banner to handle a different copy for the last day. 
- update ongoing banner
- update missing space in trial banner + expired trial banner with organization instead of org 
- update tests 
Issue: https://github.com/codecov/engineering-team/issues/391
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> fix: Update ongoing trial to handle last day of the trial

- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.spec.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.spec.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/hooks/useRepoBranchContentsTable.js
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/hooks/useRepoBranchContentsTable.spec.js
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/shared/RepoContentsResult.jsx
Small PR updating the `useRepoBranchContentsTable` to pull out the flags param if present and pass it along with the API request.
Closes codecov/engineering-team#424
Closes codecov/engineering-team#469
- Update `useRepoBranchContentsTable` to pull flags from URL params
- Update `useRepoBranchContentsTable` tests
- Update `FileExplorer` tests adding in missing call to `setup` function
- Add in Error message when no results are returned and flags have been selected
> feat: Update useRepoBranchContentsTable to Pull Pass Along Flags Filter

- src/pages/PullRequestPage/PullRequestPage.jsx
- src/pages/PullRequestPage/PullRequestPage.spec.jsx
- src/pages/PullRequestPage/hooks/usePullPageData.spec.tsx
- src/pages/PullRequestPage/hooks/usePullPageData.tsx
We don't need to check `isCurrentUserPartOfOrg` to view the repo, if user has access permissions (wether they are collaborators or part of the org), the base permission class in the api https://github.com/codecov/codecov-api/blob/7c60f91d2f0799285d43384bddd0736e875c2d3a/api/shared/permissions.py#L64 takes care of this. 
look here https://sentry.slack.com/archives/C04M5GE2R5M/p1695135465184899 for more context.
issue: https://github.com/codecov/gazebo/issues/2239
- Remove `isCurrentUserPartOfOrg` from pull request page
- Fix tests 
nothing new to look at 
try while logged in, then while logged out:
https://deploy-preview-2276--gazebo-staging.netlify.app/gh/codecov/codecov-assume-flag-test/pull/23
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of …
> fix: Update to depend on api for view permissions

- src/pages/PullRequestPage/Header/Header.jsx
- src/ui/FileViewer/ToggleHeader/Title/Title.jsx
- src/ui/FileViewer/ToggleHeader/ToggleHeader.jsx
- src/ui/MultiSelect/MultiSelect.jsx
- src/ui/TabNavigation/TabNavigation.jsx
Preemptive css work to allow MultiSelect to be compatible with the pull request page / commit detail page tab navigation section
- I saw the order of stats + navigation on small screens because it looks nice.
Note: flag multi select not included in these changes
Desktop screens
Medium screens
Small screens
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
> Update pull request page for better mobile styles, premtive work for flag select

- src/pages/PullRequestPage/hooks/usePullPageData.tsx
- src/pages/PullRequestPage/subroute/ComponentsTab/hooks/query.ts
- src/pages/PullRequestPage/subroute/ComponentsTab/hooks/useComponentComparison.tsx
- src/services/comparison/schemas/FirstPullRequest.ts
- src/services/comparison/schemas/index.ts
- src/services/pulls/usePulls.tsx
Update current typescript translated hooks to support handling the new `FirstPullRequest` type added to the union `Comparison` type in the API.
> feat: Update Zod Schemas to Handle New FirstPullRequest GraphQL Type

- src/services/commit/useCommit.tsx
- src/services/commit/useCompareTotals.tsx
- src/services/commits/useCommits.js
- src/services/comparison/constants.js
- src/services/pull/fragments.js
- src/services/pulls/usePulls.tsx
With the addition of this new type on the union we need to check for it in a few more locations.
- Update `usePulls` to use new `mapEdges` funciton
- Update `useCommit` hook to handle `FirstPullRequest` type
- Update `useCompareTotals` hook to handle `FirstPullRequest` type
- Update other queries to spread on comparison type
> fix: Update Remaining Comparisons with FirstPullRequest Spread

- src/App.jsx
- src/App.spec.jsx
- src/layouts/BaseLayout/BaseLayout.spec.jsx
- src/layouts/BaseLayout/hooks/useUserAccessGate.js
- src/layouts/BaseLayout/hooks/useUserAccessGate.spec.tsx
- src/pages/LoginPage/LoginButton.jsx
- src/pages/LoginPage/LoginButton.spec.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/LoginPage/LoginPage.spec.jsx
- src/pages/SyncProviderPage/SyncProviderPage.spec.tsx
- src/pages/SyncProviderPage/SyncProviderPage.tsx
This PR removes the feature flag for login w/Sentry, as well as removing the checks hiding the `SyncProviderPage` when running in self hosted mode.
Closes codecov/engineering-team#476
- Enable `SyncProviderPage` in `App`
- Remove `sentryLoginProvider` flag from components and tests
- Update `useUserAccessGate` to function properly in self hosted mode.
> ref: Allow SyncProviderPage in Self Hosted

- src/pages/PullRequestPage/PullRequestPageContent/ErrorBanner/ErrorBanner.jsx
- src/pages/PullRequestPage/PullRequestPageContent/ErrorBanner/ErrorBanner.spec.jsx
- src/pages/PullRequestPage/PullRequestPageContent/PullRequestPageContent.jsx
- src/pages/PullRequestPage/PullRequestPageContent/PullRequestPageContent.spec.jsx
- src/pages/RepoPage/PullsTab/PullsTable/PullsTable.jsx
- src/pages/RepoPage/PullsTab/PullsTable/Title/Title.jsx
- src/pages/RepoPage/PullsTab/PullsTable/Title/Title.spec.jsx
- src/shared/utils/comparison.js
if first pull request, default to file explorer. 
- Update pulls page to default to file explorer for the first pull request  
- Tests 
issue: https://github.com/codecov/engineering-team/issues/404
> feat: Default to file explorer for the first time UX

- src/shared/treePaths/useTreePaths.js
- src/shared/treePaths/useTreePaths.spec.js
Quick small fix to the `useTreePaths` hook which instead of passing the query param object it actually spreads it so we can set the query params properly.
- Update `useTreePaths` to spread query params instead of passing a full object
- Update tests
> fix: useTreePaths not spreading query params

- src/shared/ListRepo/OrgControlTable/RepoOrgNotFound/RepoOrgNotFound.jsx
- src/shared/ListRepo/OrgControlTable/RepoOrgNotFound/RepoOrgNotFound.spec.jsx
- Update "Can't find your repo organization? Try re-syncing"-> "Can't find your repo? Try re-syncing"
- Remove "or installing the Codecov app" as users wont see this page if app isn't installed
- Remove "Checkout our docs for more information" as it's redundant and can be deleted
issue: https://github.com/codecov/engineering-team/issues/551
- Update copy
- Update tests
repo page
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm …
> ref: Update org not found copy

- src/pages/AccountSettings/shared/Header/Header.jsx
- src/pages/AccountSettings/shared/Header/Header.spec.jsx
- src/pages/AnalyticsPage/AnalyticsPage.jsx
- src/pages/AnalyticsPage/AnalyticsPage.spec.jsx
- src/pages/AnalyticsPage/Tabs/Tabs.jsx
- src/pages/AnalyticsPage/Tabs/Tabs.spec.jsx
- src/pages/MembersPage/Tabs/Tabs.jsx
- src/pages/MembersPage/Tabs/Tabs.spec.jsx
- src/pages/OwnerPage/Tabs/Tabs.jsx
- src/pages/OwnerPage/Tabs/Tabs.spec.jsx
- src/pages/PlanPage/Tabs/Tabs.jsx
- src/pages/PlanPage/Tabs/Tabs.spec.jsx
- src/pages/RepoPage/FlagsTab/FlagsTab.jsx
- src/pages/RepoPage/FlagsTab/FlagsTab.spec.jsx
- src/pages/RepoPage/RepoPage.jsx
- src/pages/RepoPage/RepoPage.spec.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/GeneralTab.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/GeneralTab.spec.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/Tokens/TokensTeam/TokensTeam.spec.js
Getting rid of some feature flags that aren't needed as part of code removal
- Getting rid of redundant feature flags 
> Team flags refactor

- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.tsx
Currently, the `Your trial ends in`  banner is visible across all tabs. This PR makes it such that it does on render on the `Plan` tab. Two approaches were considered. 
1.) Dismiss the banner no matter where the user is after they click **Upgrade** , even if they are on that page already
2.) Do not show the banner on the Plan page, even if they did not get there by clicking the button
This change implements approach 2, keeping in mind that the sales experience on that page is soon to be upgraded. 
I also cleaned up some redundancies in `TrialBanner.spec.tsx` in order to add tests for this behaviour. I'm leaning towards creating issues for any refactoring work in the future but prefer to keep these changes for now. 
https://github.com/codecov/gazebo/assets/148245014/ed440317-cf79-4ab3-a850- …
> Remove free trial expiry banner from plan page

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.spec.jsx
- src/pages/MembersPage/MembersActivation/Activation/Activation.jsx
- src/pages/MembersPage/MembersActivation/Activation/Activation.spec.jsx
- src/pages/MembersPage/MembersActivation/MembersActivation.jsx
- src/pages/MembersPage/MembersActivation/MembersActivation.spec.jsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.spec.tsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.tsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/CancelPlanPage.jsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/CancelPlanPage.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/ProPlanSubheading/ProPlanSubheading.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/ProPlanCard/ProPlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/shared/ActionsBilling/ActionsBilling.spec.jsx
- src/pages/PlanPage/subRoutes/InvoiceDetailsPage/InvoiceDetail.spec.jsx
- src/pages/PlanPage/subRoutes/InvoiceDetailsPage/sections/InvoiceFooter.spec.jsx
- src/pages/PlanPage/subRoutes/InvoiceDetailsPage/sections/InvoiceHeader.spec.jsx
- src/pages/PlanPage/subRoutes/InvoiceDetailsPage/sections/InvoiceItems.jsx
- src/pages/PlanPage/subRoutes/InvoiceDetailsPage/sections/InvoiceItems.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeDetails/UpgradeDetails.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.spec.jsx
- src/services/account/usePlanData.spec.tsx
- src/services/account/usePlanData.ts
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.tsx
We're changing the `planName` resolver value for plan data to `value`. Historically, we've used `value`, and although we ultimately want to use `planName`, maintaining both keys/utils/proptypes/revolving logic with different key names can be hard to follow, specially with those files not using TS atm.
- Change `usePlanData` hook to use `value` over `planName`
- Change every use of planName to use value throughout the codebase + tests
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> feat: change planName to value for planData hook

- src/sentry.ts
Quick fix to disable the `debug` console from logging in prod.
> fix: Sentry Debug Value Setting

- src/pages/CommitDetailPage/CommitDetailPage.spec.jsx
- src/pages/CommitDetailPage/subRoute/FilesChangedTab/FilesChangedTab.spec.tsx
- src/pages/CommitDetailPage/subRoute/FilesChangedTab/FilesChangedTab.tsx
Quickly updating the `FilesChangedTableTeam` for the commit detail page to only render the team table when the repo is private and the tier is team.
- Update `FilesChangedTableTeam` to check repo visibility
- Update tests
> feat: Hide Commits Page Team Files Changed Table for Public Repos 

- src/pages/CommitDetailPage/CommitDetailPage.jsx
- src/pages/CommitDetailPage/CommitDetailPage.spec.jsx
This PR hides the commit summary on the commit detail page when the owner is on a team plan as well as the repo being private, if the repo is public then it will still show the commit summary.
Closes codecov/engineering-team#618
- Update the `CommitDetailPage` to conditionally render the `CommitDetailSummary` based off of repo visibility and tier value.
- Update tests to check new cases.
Public Repo:
Private Repo:
> feat: Remove Commit Summary from Commit Detail Page on Team Plan

- src/sentry.ts
Just some small tweaks to our Sentry config to clean up our issues as well as stopping the use of deprecated options.
- Create function to check for blocked user agents
- Set Sentry Replay rates
> fix: Drop Transactions from Blocked User Agents

- src/pages/CommitDetailPage/Header/Header.spec.tsx
- src/pages/CommitDetailPage/Header/Header.tsx
- src/pages/PullRequestPage/Header/Header.spec.tsx
- src/pages/PullRequestPage/Header/Header.tsx
- src/pages/RepoPage/RepoPage.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/GeneralTab.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/GeneralTab.spec.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/hooks/index.ts
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/hooks/useRepoForTokensTeam.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/hooks/useRepoForTokensTeam.tsx
We recently added the requirement to only show the team plan for private repos. This change goes back to work that was pushed prior to this decision and adding that check there to ensure only public repos follow.
- Add checks in a bunch of different files + adjusted the tests
- Rename useRepoDefaultBranch.spec.tsx to useRepoForTokensTeam.spec.tsx
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, …
> Make previous team plan changes only apply if repo is private

- src/pages/RepoPage/CommitsTab/CommitsTableTeam/CommitsTableTeam.spec.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/CommitsTableTeam.tsx
- src/pages/RepoPage/PullsTab/PullsTableTeam/PullsTableTeam.spec.tsx
- src/pages/RepoPage/PullsTab/PullsTableTeam/PullsTableTeam.tsx
Closes https://github.com/codecov/engineering-team/issues/782. Pretty straightforward. 
> fix: Add percentage next to patch column title for team plan tables

- src/pages/RepoPage/FlagsTab/FlagsTab.jsx
- src/pages/RepoPage/FlagsTab/FlagsTab.spec.jsx
This PR updates the `FlagsTab` to only redirect while an org is on a team plan and the repo is also public.
Closes codecov/engineering-team#781
- Update `FlagsTab.jsx`
- Update tests
> fix: Redirect on Flags Tab for Public Repos

- src/pages/RepoPage/CoverageTab/SummaryTeamPlan/SummaryTeamPlan.spec.tsx
- src/pages/RepoPage/CoverageTab/SummaryTeamPlan/SummaryTeamPlan.tsx
- src/ui/Select/Select.jsx
- src/ui/Select/Select.spec.jsx
This PR enables devs to pass along an icon that lives next to the select text, as well as updating the team plan version of the coverage tab summary to pass along a branch icon. This change in plan was confirmed with design.
Closes codecov/engineering-team#780
- Update `Select` to support passing along a button icon prop
- Update `SummaryTeamPlan` to pass along the branch icon
- Update tests
> fix: Show Branch Icon in Branch Dropdown for Team Plan

- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.jsx
- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.spec.jsx
This PR adds in a new CTA on the analytics page for team plan users, urging them to upgrade if they wish to see coverage over time data for private repos.
Closes codecov/engineering-team#773
- Add new CTA to `ChartSelectors`
- Update tests
> feat: Add Upgrade CTA to Analytics Page

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.jsx
- src/shared/utils/upgradeForm.js
- src/shared/utils/upgradeForm.spec.js
Add validation logic when person is trying add seats when going for team plan where it can't exceed 10 seats
Alter schema to handle the seats validation for the team plan 
> feat: Seats validation for team plan

- src/shared/GlobalTopBanners/TrialBanner/ExpiredBanner.spec.tsx
- src/shared/GlobalTopBanners/TrialBanner/ExpiredBanner.tsx
- src/ui/TopBanner/TopBanner.tsx
- src/ui/TopBanner/index.ts
This PR adds an `onClick` event to the upgrade button in the `ExpiredBanner` that saves the value to the local storage. This is a little hacky because it's reliant on the navigation to update the state when returning to the previous page to actually hide the banner because there's no real way to update the state from the `ExpiredBanner` component itself.
Closes codecov/engineering-team#746
- Update `ExpiredBanner`
- Update `TopBanner`
- Update tests
> feat: Hide expired banner when clicking on upgrade link

- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.jsx
- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.spec.jsx
This PR closes https://github.com/codecov/engineering-team/issues/785. If the user is on a team plan, we only want to show them public repos on the analytics page. Adds similar logic as the one in the [table below](https://github.com/codecov/gazebo/blob/main/src/shared/ListRepo/ReposTable/ReposTable.jsx#L154) to filter public repositories. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> Fix analytics page chart selector behavior

- src/pages/CommitDetailPage/CommitDetailPageContent/CommitDetailPageContent.spec.jsx
- src/pages/CommitDetailPage/CommitDetailPageTabs/CommitDetailPageTabs.jsx
- src/pages/CommitDetailPage/CommitDetailPageTabs/CommitDetailPageTabs.spec.jsx
- src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/hooks/useRepoCommitContentsTable.js
- src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/hooks/useRepoCommitContentsTable.spec.js
- src/pages/CommitDetailPage/subRoute/FilesChangedTab/FilesChangedTable/FilesChangedTable.jsx
- src/pages/CommitDetailPage/subRoute/FilesChangedTab/FilesChangedTable/FilesChangedTable.spec.jsx
- src/pages/CommitDetailPage/subRoute/IndirectChangesTab/IndirectChangesTable/IndirectChangesTable.jsx
- src/pages/CommitDetailPage/subRoute/IndirectChangesTab/IndirectChangesTable/IndirectChangesTable.spec.jsx
- src/pages/PullRequestPage/PullRequestPageTabs/PullRequestPageTabs.jsx
- src/pages/PullRequestPage/PullRequestPageTabs/PullRequestPageTabs.spec.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FlagMultiSelect.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FlagMultiSelect.spec.jsx
- src/pages/RepoPage/CoverageTab/subroute/Fileviewer/Fileviewer.jsx
- src/pages/RepoPage/CoverageTab/subroute/Fileviewer/Fileviewer.spec.jsx
- src/ui/FileViewer/ToggleHeader/ToggleHeader.spec.jsx
This PR removes the various feature flags used to conditionally render the flag multi select, as we've fully rolled it out, and as we also want to fully roll it out to enterprise customers as well.
- Removed `coverageTabFlagMutliSelect` flag
- Removed `commitTabFlagMultiSelect` flag
- Removed `pullRequestPageFlagMultSelect` flag
> ref: Remove All Flag Multi Select ... Flags

- src/pages/CommitDetailPage/subRoute/FilesChangedTab/FilesChangedTableTeam/FilesChangedTableTeam.tsx
- src/pages/PullRequestPage/subroute/FilesChangedTab/FilesChanged/TableTeam/TableTeam.tsx
Tweak team plan table styles
* mostly just applying numeric type to the headers to align titles. Can't make the table scroll on small screens till we refactor the code viewer unfortunately.
> Table css styles fix

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.spec.jsx
Team card was displaying the incorrect name when trialing, this fixes it.
- Adjust copy for teamplancard when trialing + tests
> fix: change copy of team card when trialing

- src/pages/AnalyticsPage/Chart/useCoverage.js
- src/pages/AnalyticsPage/Chart/useCoverage.spec.js
- src/services/charts/useReposCoverageMeasurements.ts
Make the line chart on the Analytics page filter on only public repos if the user is on a team plan. This makes use of the new `isPublic` parameter on the measurements GQL field as added in https://github.com/codecov/engineering-team/issues/786. This PR closes https://github.com/codecov/engineering-team/issues/787.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> [Client] Add logic to return measurements data based on specifying public and private repo

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.spec.jsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.spec.js
We're adding a `learn more` link to the team card plan. We didn't add it before cause we didn't know the link.
- Add link + tests for the team plan card + links hook
> feat: Add learn more link to the team plan card when upgrading

- src/pages/AccountSettings/tabs/Admin/GithubIntegrationSection/GithubIntegrationSection.jsx
- src/pages/AccountSettings/tabs/Admin/GithubIntegrationSection/GithubIntegrationSection.spec.jsx
> fix: Update to Codecov App link in GitHub integration section #2306

- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.jsx
- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.spec.jsx
- src/services/trial/useStartTrial.ts
- src/shared/ListRepo/ReposTable/ReposTable.jsx
The analytics chart selector was fetching all sorts of repos rather than using the activated ones. This is because we were supplying `active` rather than `activated` props to the useRepos hook, which wasn't caught cause that test still mocks the hook implementation rather than emulate it through MSW. 
- Fix prop provided to `useRepos` by the analytics chart selector
Matching the lists to the repo list ^
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …
> feat: adjust useRepos prop ingestion from active to activated

- .github/workflows/ci.yml
This PR removes a `- 1` from the calculating test index function, it seems that this was removing a handful of tests from being ran because there wasn't enough tests to go over the 80 per runner ratio.
> build: Remove minus one from test index calculation

- src/shared/utils/unsupportedExtensionsMapper.js
Remove F# files from the image blocklist.
Fixes #2427
> Remove F# files from the image blocklist

- src/pages/PullRequestPage/subroute/ComponentsSelector/ComponentsSelector.tsx
- src/pages/PullRequestPage/subroute/ComponentsSelector/index.js
- src/pages/PullRequestPage/subroute/FilesChangedTab/FilesChanged/hooks/useImpactedFilesTable.js
- src/pages/PullRequestPage/subroute/FilesChangedTab/FilesChanged/hooks/useImpactedFilesTable.spec.js
- src/pages/PullRequestPage/subroute/FilesChangedTab/FilesChangedTab.spec.tsx
- src/pages/PullRequestPage/subroute/FilesChangedTab/FilesChangedTab.tsx
Add components selector to impacted files tab.
- Add selector to files changed tab
- Adjust hook to accept filters 
- Tests 
https://github.com/codecov/gazebo/assets/91732700/c4654f8c-e75e-4512-8f91-a3624fa98b42
> feat: Update files changed tab with components selector

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/BillingOptions/BillingOptions.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/BillingOptions/BillingOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/PriceCallout/PriceCallout.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/PriceCallout/PriceCallout.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/ProPlanController.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/ProPlanController.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/Controllers/ProPlanController/index.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/PlanTypeOptions/PlanTypeOptions.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/PlanTypeOptions/PlanTypeOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/UpdateButton/UpdateButton.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/UpdateButton/UpdateButton.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/UpgradeForm2.jsx
- src/shared/utils/unsupportedExtensionsMapper.js
We're adding the `ProController` isolated component that handles form data. This is to improve the general flow for the UpgradeForm component
- Added the `ProController`, a component that encapsulates the BillingOptions, UserCount and PriceCallout components
- Made use of `ProController` in the UpgradeForm2 component
- Some variable renaming: `setValue` to `setFormValue`, `planString` to `newPlan`
- Created some types to standardize the values
- Changed a bit the UpdateButton component to remove unnecessary prop drilling and adjusted test as well
* there are 2 tests that are skipped, I need a hand w/ those 🙃 
(Still only working for Pro. I'm abstaining from doing a full-blown check in every of these PRs as the code isn't running and I'll do one when all the 3 services are in)
Look, I get …
> feat add ProController component to the 2nd form component

- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/hooks/useRepoBranchContentsTable.js
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/hooks/useRepoBranchContentsTable.spec.js
- src/shared/ContentsTable/TableEntries/BranchEntries/BranchDirEntry.jsx
- src/shared/ContentsTable/TableEntries/BranchEntries/BranchDirEntry.spec.jsx
- src/shared/ContentsTable/TableEntries/BranchEntries/BranchFileEntry.jsx
- src/shared/ContentsTable/TableEntries/BranchEntries/BranchFileEntry.spec.jsx
Updates `useRepoBranchContentsTable` to be used to filter components in file explorer and file viewer. Note that these changes do not affect anything that propagates `MissingFileData` as of yet. 
> Adjust useRepoBranchContentsTable to accept components filters

- src/pages/RepoPage/CommitsTab/CommitsTab.jsx
- src/pages/RepoPage/CommitsTab/CommitsTab.spec.jsx
- src/services/branches/index.js
- src/services/branches/useBranchHasCommits.spec.tsx
- src/services/branches/useBranchHasCommits.tsx
This PR makes it so that when you visit the commits tab of a repo whose default branch has no commits it will swap over to the `All branches` option by updating the query params on the initial render, so users can force their way back to the default branch if they wish to investigate further.
Closes codecov/engineering-team#870
- Add new `useBranchHasCommits` hook
- Update `CommitsTab` to swap to `All branches` when default branch has no commits only on initial render.
https://github.com/codecov/gazebo/assets/105234307/f0e933d5-f82a-4c4d-8533-0363d9fe5247
> feat: Default to All branches when default branch has no commits

- src/pages/PullRequestPage/subroute/FileExplorer/FileExplorer.jsx
- src/pages/PullRequestPage/subroute/FileExplorer/FileExplorer.spec.jsx
- src/pages/PullRequestPage/subroute/FileExplorer/hooks/useRepoPullContentsTable.js
- src/pages/PullRequestPage/subroute/FileExplorer/hooks/useRepoPullContentsTable.spec.js
Adding the selector to PR files explorer 
- Add the selector component 
- Support filters in the hook 
https://github.com/codecov/gazebo/assets/91732700/467c1ed8-e28d-40c8-ba6c-9b8d8210cb05
> feat: Update files explorer tab with components selector

- src/ui/MultiSelect/MultiSelect.jsx
before and after: 
it's conflicting with flags multi selector, we're going to resolve this problem when we move the rest of the stuff down a to the gray box anyway. 
> fix: Fix z index of flags selector

- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileExplorer.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileExplorer.spec.jsx
- src/pages/RepoPage/CoverageTab/subroute/Fileviewer/Fileviewer.jsx
- src/ui/ComponentsSelect/ComponentsSelectCommit.spec.tsx
- src/ui/ComponentsSelect/ComponentsSelectCommit.tsx
- src/ui/ComponentsSelect/index.ts
Adds the components multi select to the file explorer in the Coverage tab. This closes https://github.com/codecov/engineering-team/issues/829. 
This PR also moves `ComponentsSelectCommit` to its own ui folder for shared access across multiple components. 
https://github.com/codecov/gazebo/assets/148245014/089cd4b8-a753-4000-b405-4505a2eb15e1
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> [feat] Place the new multi selector for components in file explorer

- src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/CommitDetailFileExplorer.jsx
- src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/CommitDetailFileExplorer.spec.jsx
- src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/hooks/useRepoCommitContentsTable.js
- src/pages/CommitDetailPage/subRoute/CommitDetailFileExplorer/hooks/useRepoCommitContentsTable.spec.js
- src/services/pathContents/commit/file/usePrefetchCommitFileEntry.spec.tsx
- src/services/pathContents/commit/file/usePrefetchCommitFileEntry.tsx
- src/shared/ContentsTable/TableEntries/CommitEntries/CommitDirEntry.jsx
- src/shared/ContentsTable/TableEntries/CommitEntries/CommitDirEntry.spec.jsx
- src/shared/ContentsTable/TableEntries/CommitEntries/CommitFileEntry.jsx
- src/shared/ContentsTable/TableEntries/CommitEntries/CommitFileEntry.spec.jsx
Adds component selector to the file explorer in the commit detail page. This PR closes https://github.com/codecov/engineering-team/issues/860.
https://github.com/codecov/gazebo/assets/148245014/419b3a0c-69e0-4df7-b6d7-766c6c14c312
> [feat] Place components selector in commit details file explorer

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.spec.jsx
This PR makes the use of the new upgrade form
closes https://github.com/codecov/engineering-team/issues/778
[screen-capture (12).webm](https://github.com/codecov/gazebo/assets/82913673/168ce051-c0a0-43fa-8dc9-e04ffd2ad279)
> feat: use 2nd upgrade form

- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/TeamPlanSpecialOffer/TeamPlanCard/TeamPlanCard.spec.tsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/TeamPlanSpecialOffer/TeamPlanCard/TeamPlanCard.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.spec.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/PlanTypeOptions/PlanTypeOptions.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/PlanTypeOptions/PlanTypeOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/hooks/usePlanParams.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm2/hooks/usePlanParams.ts
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.jsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradePlanPage.spec.jsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
This PR updates a couple different pieces regarding the team plan, by adding in a URL search param when linking to the upgrade page so that the page will default to showing the team plan.
Closes: codecov/engineering-team#706
- Update `useNavLinks -> upgradeOrgPlan` to support query params being appended to URL
- Create new `usePlanParams` hook to grab `plan` search param from the URL
-  Update relevant cards to append `?plan=team` to upgrade link
- Update `PlanTypeOptions` and `UpgradePlanPage` to grab plan param and set value to team plan if they have access to the team plan.
> feat: Have upgrade to team plan links include URL search param

- src/pages/RepoPage/FlagsTab/subroute/FlagsTable/FlagsTable.jsx
- src/pages/RepoPage/FlagsTab/subroute/FlagsTable/FlagsTable.spec.jsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
This PR makes entries in the flags page link to their selected flag in the coverage page.
Closes https://github.com/codecov/engineering-team/issues/847
- Added new link for the coverage page that accepts query params
- Made flag names link to the coverage page
[screen-capture (13).webm](https://github.com/codecov/gazebo/assets/82913673/fa745eca-48a8-4ed4-969e-72df34a6ea74)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that …
> feat: make flag entries links

- src/config.js
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.spec.js
Change the [nav links](https://github.com/codecov/gazebo/blob/2751fa45ddd1ef7af7c71745cad21a61e1c70c37/src/services/navigation/useNavLinks/useStaticNavLinks.js#L69-L74) on the [context switcher](https://github.com/codecov/gazebo/blob/2751fa45ddd1ef7af7c71745cad21a61e1c70c37/src/ui/ContextSwitcher/ContextSwitcher.jsx#L154) https://github.com/apps/codecov/installations/new to use a config value for codecov (config.GH_APP). The value codecov is incorrect on self hosted + dedicated namespace.
We want to [default](https://github.com/codecov/gazebo/blob/main/src/config.js#L3-L10) GH_APP value to codecov to ensure no issues by default.
- Use config value in app installation static link 
- Fix test
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in …
> fix: Update installation nav link to use config value

- src/pages/RepoPage/NewRepoTab/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/NewRepoTab/GitHubActions/GitHubActions.tsx
- src/services/repo/useRepo.js
Fix onboarding docs to reflect the use of the global token.
- Update GitHub actions with global token 
- Update tests 
- Refactor to typescript 
closes: https://github.com/codecov/engineering-team/issues/940
> fix: Update onboarding docs with global token

- src/pages/CommitDetailPage/CommitDetailPageContent/CommitDetailPageContent.jsx
- src/ui/TabNavigation/TabNavigation.jsx
This PR updates the `TabNavigation`, and the `CommitDetailPageContent` components to use container queries specifically for the tabs on the commit detail page so that the breakpoints are based off the size of the tab and not the screen itself.
Closes codecov/engineering-team#809
- Add in `div` to create a container selector for Tailwind in `CommitDetailPageContent`
- Add in container queries that override default media queries when `commit-detail-page` container is present.
https://github.com/codecov/gazebo/assets/105234307/7d42d1bd-9f38-411b-8524-9c6e755dc093
> fix: Update TabNav styles to fix hiding tabs

- src/services/account/usePlanData.ts
`planUserCount` can be a `null` value so we need to set it to be `nullable` in our zod schema.
> fix: Plan user count can be a nullable value

- src/pages/AccountSettings/AccountSettingsSideMenu.jsx
- src/pages/AccountSettings/AccountSettingsSideMenu.spec.jsx
Currently we're not displaying the link to show the org upload token in self hosted, this PR fixes that by adding the link when the given user is an admin for the org.
Closes codecov/engineering-team#972
- Update `AccountSettingsSideMenu` to add in org upload token link for admins run running self-hosted
- Add/Update tests accordingly
>  fix: Display Org Upload Token Tab in Self Hosted/Dedicated Cloud

- src/services/ats/useRepoATS.spec.tsx
- src/services/ats/useRepoATS.tsx
Now that we have `primaryLanguage` and `isATSConfigured` supported on the [backend](https://github.com/codecov/codecov-api/pull/323), this change adds a [useRepoATS](url) hook to be consumed on the main repo view(to be added in a follow-up PR). 
The idea is to call this hook and use the response to conditionally render the ATS tab and its contents as per the [design](https://github.com/codecov/engineering-team/issues/811). 
This PR closes https://github.com/codecov/engineering-team/issues/931.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I …
> [feat] Add useRepoATS hook

- src/pages/TermsOfService/hooks/useTermsOfService.spec.tsx
- src/pages/TermsOfService/hooks/useTermsOfService.ts
we counted on the fact that users would have at least email when they login to Codecov, but we realised BB users can have both business email and email null, this is changing Zod schema to accommodate such use case .
https://github.com/codecov/gazebo/assets/91732700/f7302a66-f472-4571-8c69-4ebb93220caf
https://github.com/codecov/gazebo/assets/91732700/d06d7709-9c51-4474-b96a-2701bc68606f
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I …
> fix: Fix BB bug

- src/shared/utils/bundleAnalysis.spec.ts
- src/shared/utils/bundleAnalysis.ts
This PR adds in a new function that utilizes the `Intl.formatNumber()` class and method to correctly format sizes to strings ensuring the correct unit is placed as well as limiting to two decimal places. 
Closes codecov/engineering-team#1000
```tsx
import { formatSizeToString } from 'shared/bundleAnalysis'
const totalBundleSize = formatSizeToString(123456)
```
- Add in new function to format size numbers to formatted string
- Tests for new functions
> feat: Create function to format bundle size strings

- src/services/user/useResyncUser.js
For whatever reason `eslint` is causing the builds to fail because `useResyncUser` is using a callback that is going to be deprecated in the next version of TanStack query. This PR removes the callback instead moving the functionality into a `useEffect` as recommended in the migration guide.
> fix: useResyncUser causing Docker builds to fail

- src/services/pull/usePullBundleList.spec.tsx
- src/services/pull/usePullBundleList.tsx
This PR adds in a new hook that fetches a list of bundles for a given pull.
GH codecov/engineering-team#993
- Create new `usePullBundleList` hook
- Write up tests for `usePullBundleList`
> feat: Create hook to fetch a list of bundles for a pull

- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsOrgToken.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsOrgToken.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsRepoToken.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsRepoToken.tsx
if user has GUT already generated, and if feature flag is on, we show GUT docs otherwise; we show old docs.
- Rename old docs to reflect repo specific docs 
- Create new org upload token doc 
- Tests and some restructure to display the correct component 
closes: https://github.com/codecov/engineering-team/issues/940 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> feat: Update GitHub Actions tab with GUT 

- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.jsx
- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.spec.jsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsOrgToken.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsOrgToken.tsx
- src/services/orgUploadToken/index.js
- src/services/orgUploadToken/useOrgUploadToken.spec.tsx
- src/services/orgUploadToken/useOrgUploadToken.ts
- src/services/repo/useRepo.js
- src/services/user/useIsCurrentUserAnAdmin.spec.js
- src/services/user/useOwner.js
This PR removes the `orgUploadToken` field from a couple of data fetching hooks, and move it to it's own hook that will fetch the token on it's own avoiding any unauthorized requests.
- Create a new hook to fetch the org upload token
- Remove `orgUploadToken` field from a couple of hooks
- Refactor components to grab the org upload token from new hook
- Update tests
> fix: Move fetching of org upload token to a different hook

- src/pages/PullRequestPage/FirstPullBanner/FirstPullBanner.spec.tsx
- src/pages/PullRequestPage/PullCoverage/PullCoverage.spec.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/PullCoverageTabs.spec.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/hooks/useTabsCounts.spec.js
- src/pages/PullRequestPage/PullRequestPage.spec.jsx
- src/pages/PullRequestPage/hooks/usePullPageData.spec.tsx
- src/pages/PullRequestPage/hooks/usePullPageData.tsx
This PR updates the `usePullPageData` to also fetch the fields to see if coverage or bundle analysis is enabled for future use on the PR page.
GH codecov/engineering-team#997
- Update `usePullPageData` to fetch product status checks
- Update related tests
> feat: Fetch product status in use pull page data

- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCIOrgToken.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCIOrgToken.tsx
if we're showing repo token, we show new yaml instructions too. 
- update copy
- fix tests 
> fix: Update repo token with v4 instructions for circle ci

- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsOrgToken.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActionsOrgToken.tsx
if we're showing repo token, show the new instructions for v4 release. 
- copy changes 
- tests
> fix: Update gh actions with v4 yaml input for repo token

- src/pages/PullRequestPage/Dropdowns/PullCoverageDropdown.spec.tsx
- src/pages/PullRequestPage/Dropdowns/PullCoverageDropdown.tsx
- src/services/pull/usePullCoverageDropdownSummary.spec.tsx
- src/services/pull/usePullCoverageDropdownSummary.tsx
This PR creates the first of two dropdowns for the pull request page, creating one to summarize the coverage information. This dropdown will be used later when putting everything all together on the PR page soon.
GH codecov/engineering-team#997
- Create new `PullCoverageDropdownSummary`
- Update `usePullCoverageDropdownSummary` to return just the pull
- Create/update tests
> feat: Create pull coverage dropdown

- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCIOrgToken.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCIOrgToken.tsx
if we're showing repo token, show new changes for the yaml (new ci version)
- copy changes
- tests
> fix: Update other ci with v4 instructions

- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleTable/BundleTable.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleTable/BundleTable.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleTable/index.ts
- src/shared/utils/bundleAnalysis.spec.ts
- src/shared/utils/bundleAnalysis.ts
This PR adds in the table that will be used on the bundles tab for the upcoming bundle analysis product.
GH codecov/engineering-team#1024
>[!note]
> Requires #2559 
- Create new `BundleTable` component
- Add `BundleTable` to `BundleContent` component
- Create new function to format load time values
> feat: Create table to display list of bundles

- src/layouts/Header/DesktopMenu.jsx
- src/layouts/Header/DesktopMenu.spec.jsx
Currently, we have 2 repeated "Feedback" links one located on the top nav, another one on the footer. We are adding a new "feedback" link on the banner here, see design here: https://github.com/codecov/engineering-team/issues/1065.
To avoid confusion, we should remove the "Feedback" link on the top nav.
remove the link, fix test 
closes: https://github.com/codecov/engineering-team/issues/1069
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
> fix: Remove feedback link form header 

- docker/start-nginx.sh
Some builds can use something other than `Z`.
> Use regex for var on enterprise vcs

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/TeamPlanController.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/TeamPlanController.tsx
Before 
https://github.com/codecov/gazebo/assets/91732700/5b40d039-6477-4e28-b19c-f02de41d727c
After
https://github.com/codecov/gazebo/assets/91732700/21ecedd8-d7af-48c9-802a-42eb8a65e750
this is a temp fix, i'm working on refactoring extract seats so that each seats input its own value 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> Fix: Update to default to 10 if pro plan already exceeds 10 users 

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.jsx
- src/shared/utils/upgradeForm.js
- src/shared/utils/upgradeForm.spec.js
We had it defaulting to pro plan when it's switching from pro to team, solution is to default to team plan when selecting team plan, not only if you're on team plan.
before
https://github.com/codecov/gazebo/assets/91732700/e9c97682-a1eb-4a20-832c-def4c55be195
After
https://github.com/codecov/gazebo/assets/91732700/9bf591d9-0a32-4011-b30c-47bb8bf89d85
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> fix: Update to team plan when selecting team plan

- src/pages/CommitDetailPage/CommitBundleAnalysis/BundleMessage/BundleMessage.tsx
- src/pages/CommitDetailPage/Dropdowns/CommitCoverageDropdown.tsx
- src/pages/PullRequestPage/Dropdowns/PullBundleDropdown.tsx
- src/pages/PullRequestPage/Dropdowns/PullCoverageDropdown.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.tsx
This PR updates the warning icons to display the correct icons, as well as fix the text size for the pull dropdowns and bundle only pulls tab.
GH codecov/engineering-team#996
GH codecov/engineering-team#997
GH codecov/engineering-team#1024
- Fix warning icons
- Fix pull bundles text size
> fix: Pull bundle text size and warning icons

- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.jsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.jsx
We shouldn't redirect from the new repo page component if the repo is active.
> fix: Remove redirect from coverage onboarding

- src/pages/RepoPage/RepoPageTabs.spec.tsx
- src/pages/RepoPage/RepoPageTabs.tsx
Add in a badge to denote that the bundles tab is currently in beta.
GH codecov/engineering-team#1024
- Add beta badge to `RepoPageTabs`
- Update tests
> feat: Setup beta badge for bundles tab

- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.tsx
This PR updates onboarding to include a step for copying the org token, as well as fixing the big code block clipboard value. Sorry there are a lot of changes, but there are not major changes in functionality overall.
Closes codecov/engineering-team#1180
- Update `RollupOnboarding` to display Codecov token
- Update `ViteOnboarding` to display Codecov token
- Update `WebpackOnboarding` to display Codecov token
>  fix: Bundle onboarding

- src/pages/PullRequestPage/PullCoverage/routes/ComponentsTab/ComponentsTable.tsx
> fix: Quick patch for the text alignment

- src/mocks/handlers.js
- src/pages/PullRequestPage/Dropdowns/PullBundleDropdown.spec.tsx
- src/pages/PullRequestPage/Dropdowns/PullBundleDropdown.tsx
- src/pages/PullRequestPage/Header/HeaderDefault/HeaderDefault.jsx
- src/pages/PullRequestPage/Header/HeaderTeam/HeaderTeam.jsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.tsx
- src/pages/PullRequestPage/PullRequestPage.spec.tsx
- src/services/pull/usePullBADropdownSummary.spec.tsx
- src/services/pull/usePullBADropdownSummary.tsx
- src/ui/TruncatedMessage/TruncatedMessage.tsx
Update to show latest commit in pull bundle dropdown and message, also increase header size for commit and pull page headers.
Closes codecov/engineering-team#1224
- Add latest source to pull bundle dropdown and standalone message
- Increase Commit and PR Page header to `text-xl`
> feat, fix: modify dropdown font size and add commit source

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/hooks/useBundleSummary.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/hooks/useBundleSummary.ts
This PR adds in a new `useBundleSummary` hook that returns the information that's required for the upcoming updated `BundleSummary` component.
>[!note]
>Requires #2605
GH codecov/engineering-team#1201
- Create new `useBundleSummaryHook`
- Add in tests
> feat: Create useBundleSummary hook

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.tsx
- src/pages/RepoPage/RepoPage.tsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
This PR updates the Bundle Summary branch selector to update the URL with the selected branch from the branch selector, as well as add in the `/:branch` param to the routes for the bundles tab.
>[!note]
> Requires: #2605, #2606, #2607
Closes codecov/engineering-team#1215
- Add `branch` option to `bundles` route in `useNavLinks`
- Update branch context selector to update the branch in the `BundleSummary`
- Update tests
> feat: Add branch route param to bundles route

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BranchSelector.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BranchSelector.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.tsx
- src/pages/RepoPage/RepoPage.spec.tsx
- src/pages/RepoPage/RepoPage.tsx
- src/services/branches/useBranchBundlesNames.spec.tsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
- src/ui/Select/Select.jsx
This PR creates a bundle selector for the upcoming changes to the bundles tab. When you select a bundle it sets the branch and bundle param in the URL. If you select a new branch we reset the bundle select to it's empty state and update the URL accordingly.
>[!note]
> Requires #2614
Closes codecov/engineering-team#1203
- Create new `BundleSelector` component
- Update `BundleSummary` and `BranchSelector` to create ref and pass it around for resetting the `BundleSelector`
- Few styling tweaks
https://github.com/codecov/gazebo/assets/105234307/0c0f5e07-19a3-498d-b930-6c15cd6b64c4
> feat: Create bundle selector for bundles tab

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleDetails.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleDetails.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.tsx
- src/services/bundleAnalysis/index.ts
- src/services/bundleAnalysis/useBranchBundleSummary.spec.tsx
- src/services/bundleAnalysis/useBundleSummary.spec.tsx
- src/services/bundleAnalysis/useBundleSummary.tsx
- src/services/repo/useRepoOverview.tsx
- src/ui/Select/Select.jsx
This PR adds in a new `BundlesDetail` component that is used in the top right of the updated bundles tab.
Closes codecov/engineering-team#1207
- Create new `BundlesDetail` component
- Few tweaks to `useBundleSummary` hook
- Few small tweaks here and there
- Update to tests
> feat: Create bundles tab summary section

- src/pages/RepoPage/RepoPageTabs.spec.tsx
- src/pages/RepoPage/RepoPageTabs.tsx
This PR tweaks the repo page tabs slightly for the upcoming release of bundle analysis where a user might have only one product enabled, we don't want to show the tab if it hasn't been setup so random users don't click on it and get redirect somewhere else.
- Update tab adding logic in `RepoPageTabs`
- Add a lot more tests to ensure the correct tabs are rendered properly
> fix: Repo Page tabs rendering when they should not

- src/pages/EnterpriseLandingPage/EnterpriseLandingPage.spec.tsx
- src/pages/EnterpriseLandingPage/EnterpriseLandingPage.tsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.tsx
- src/pages/SyncProviderPage/SyncButton.spec.tsx
- src/pages/SyncProviderPage/SyncButton.tsx
- src/pages/SyncProviderPage/SyncProviderPage.spec.tsx
- src/pages/SyncProviderPage/SyncProviderPage.tsx
- src/services/config/index.ts
- src/services/config/useLoginProviders.spec.tsx
- src/services/config/useLoginProviders.ts
- src/services/config/useSyncProviders.spec.tsx
- src/services/config/useSyncProviders.ts
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.spec.js
- src/ui/Button/Button.jsx
This PR updates the `/sync` page to fetch the list of configured Git providers from the API so that Self-Hosted users who are have configured enterprise versions of the Git providers will also be able to limit what Git providers their users can sync with.
Closes codecov/engineering-team#910
- Rename `useServiceProviders` to `useLoginProviders`
- Create new `useSyncProviders` hook
- Update Sync page to fetch list of sync providers and display them
- Update `SyncButton` to support enterprise Git providers
Coming soon
> fix: Sync page to pull in dynamic list of sync providers

- src/pages/AccountSettings/tabs/YAML/YAML.jsx
- src/pages/AccountSettings/tabs/YAML/YamlEditor/YamlEditor.jsx
- src/pages/RepoPage/SettingsTab/SettingsTab.jsx
- src/pages/RepoPage/SettingsTab/tabs/BadgesAndGraphsTab/Graphs/URLEmbed.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/Tokens/GraphToken/GraphToken.jsx
- src/pages/RepoPage/SettingsTab/tabs/GeneralTab/Tokens/RepoUploadToken/RepoUploadToken.jsx
- src/pages/RepoPage/SettingsTab/tabs/YamlTab/YAML/YAML.jsx
- src/pages/RepoPage/SettingsTab/tabs/YamlTab/YamlTab.jsx
- src/ui/SettingsDescriptor/SettingsDescriptor.jsx
Style tweaks across the settings pages. Mostly adjusts widths of body divs on settings pages so that they match the comps.
[Figma](https://www.figma.com/file/0VVfIlEmmKlGNe4bLs84IW/GH-888?type=design&node-id=1-239&mode=design)
Closes codecov/engineering-team#888
- Adjust large screen widths of several settings page body divs
- Fix save button position on Global YAML settings page
Global YAML
> style: Fix settings style inconsistencies

- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/CommitsTableTeam.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/CommitsTableTeam.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.tsx
- src/pages/RepoPage/CommitsTab/CommitsTab.spec.jsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/CommitsTableTeam.spec.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/CommitsTableTeam.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.spec.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.tsx
- src/services/commits/useCommitsTeam.spec.tsx
- src/services/commits/useCommitsTeam.tsx
This PR updates the commits team tables to display a bundle analysis column if the user is uploading bundle analysis data to Codecov.
- Update pull request page commits team table to have bundle analysis column
- Update repo page commits tab team table to have bundle analysis column
- Update team commits hook to fetch bundle analysis data
- Update tests
> feat: Add BA column to commits team tables

- src/pages/CommitDetailPage/CommitCoverage/CommitCoverageSummary/CommitCoverageSummary.spec.jsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverageSummary/hooks/useCommitForSummary.spec.js
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.spec.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/IndirectChangesTable.spec.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/IndirectChangesTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FilesChangedTable/FilesChangedTable.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FilesChangedTable/FilesChangedTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/IndirectChangedFiles.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/IndirectChangedFiles.tsx
- src/services/commit/useCommit.tsx
Adds a 'Deleted file' status indicator to the files changed tables for both pull and commit. Also adds the 'Critical file' status indicator to the files changed table for commit and the indirect changes tables for both pull and commit, bringing these tables into alignment.
[Designs](https://www.figma.com/file/pt7RLbHw7XLDp2SOAVDyQm/Untitled?type=design&node-id=2%3A287&mode=design&t=3MqbcG0Cl4vXv5ZM-1)
Closes https://github.com/codecov/engineering-team/issues/1087
- Add deleted file status to files changed tables
- Only show file link and drop down toggle on non-deleted files
- Unify status indicators across files changed/indirect changes tables
> feat: Add deleted file status to files changed tables

- src/pages/CommitDetailPage/CommitBundleAnalysis/BundleMessage/BundleMessage.spec.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/BundleMessage/BundleMessage.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.spec.tsx
- src/pages/CommitDetailPage/CommitDetailPage.spec.tsx
- src/pages/CommitDetailPage/Dropdowns/CommitBundleDropdown.spec.tsx
- src/services/commit/useCommitBADropdownSummary.spec.tsx
- src/services/commit/useCommitBADropdownSummary.tsx
Small change to use new change field for the commit bundle dropdown summary.
- Update summary hook to fetch in data from new fields
- Update commit bundle message to access new fields
- Update tests
> ref: Update commit bundle summary to use new data

- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTable/CommitsTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTable/createCommitsTableData.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTable/createCommitsTableData.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/CommitsTableTeam.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.tsx
- src/pages/RepoPage/CommitsTab/CommitsTable/CommitsTable.tsx
- src/pages/RepoPage/CommitsTab/CommitsTable/createCommitsTableData.spec.tsx
- src/pages/RepoPage/CommitsTab/CommitsTable/createCommitsTableData.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/CommitsTableTeam.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.spec.tsx
- src/pages/RepoPage/CommitsTab/CommitsTableTeam/createCommitsTableTeamData.tsx
- src/pages/RepoPage/PullsTab/PullsTable/PullsTable.tsx
- src/pages/RepoPage/PullsTab/PullsTable/createPullsTableData.spec.tsx
- src/pages/RepoPage/PullsTab/PullsTable/createPullsTableData.tsx
- src/pages/RepoPage/PullsTab/PullsTableTeam/PullsTableTeam.tsx
- src/pages/RepoPage/PullsTab/PullsTableTeam/createPullsTableTeamData.spec.tsx
- src/pages/RepoPage/PullsTab/PullsTableTeam/createPullsTableTeamData.tsx
Some quick fixes to the commits and pulls tables.
- Update Commits table regular and team for both repo page and pulls page
- Update Pulls table regular and team
Before:
After:
Before:
After:
> fix: Commits and pulls tab sizing

- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/useUploads/useUploads.js
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/useUploads/useUploads.spec.js
- src/pages/PullRequestPage/PullCoverage/PullCoverage.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverage.spec.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/PullCoverageTabs.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/PullCoverageTabs.spec.jsx
- src/pages/PullRequestPage/PullRequestPage.spec.tsx
- src/pages/PullRequestPage/PullRequestPage.tsx
In `useRepoSettings` there's a field that requires a user to be authenticated, however we're using it on pages where we cannot be sure a user will be authenticated. This PR replaces the use of `useRepoSetttings` to `useRepoOverview` that does not require a user to be authenticated.
- Update `PullCoverageTabs`
- Update `PullCoverage`
- Update `PullRequestPage`
- Update `useUploads`
> fix: Swap to using repo overview instead of settings

- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleHeadTable/PullBundleHeadTable.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleHeadTable/PullBundleHeadTable.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummaryOld/BundleSummaryOld.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummaryOld/BundleSummaryOld.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleTable/BundleTable.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleTable/BundleTable.tsx
- src/services/bundleAnalysis/useBranchBundleSummary.spec.tsx
- src/services/bundleAnalysis/useBranchBundleSummary.tsx
- src/shared/utils/bundleAnalysis.spec.ts
- src/shared/utils/bundleAnalysis.ts
Small updates to use new GQL fields missed in previous updates, as well as moving to use the updated format time to string function.
- Remove old format time to string hook
- Update to use new format function
- Update components to use new functions
- Update tests
> ref: Remove old deprecated format time to string

- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.tsx
TrialBanner is called by anyone visiting a org page, this change make it so that we don't retrieve the plan data of the org for users not belonging in the org. This change is necessary because in the API there is a change that hides plan / planData / hasPrivateRepos.
> don't get planData if user is not in org

- .github/workflows/ci.yml
Updating GH workflow actions to latest, the current versions are using node16 which is now EOL. The updated versions are on node 20.
https://github.com/actions/setup-node/tree/v4/
https://github.com/fossas/fossa-action/tree/v1.3.3/
https://github.com/actions/cache/tree/v4/
> chore: Update workflows for setup-node, cache and fossa to latest

- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.jsx
- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.spec.jsx
- src/layouts/shared/NetworkErrorBoundary/networkErrorMetrics.spec.ts
- src/layouts/shared/NetworkErrorBoundary/networkErrorMetrics.ts
- src/shared/utils/metrics.ts
After todays eng retro I threw together this quick PR so we can start collecting some basic metrics from the network error boundary so we can setup some alerts for when things catch on fire.
- Add in new metrics keys to `metrics.ts`
- Add in helper function
- Update `NetworkErrorBoundary` to send the metrics
> feat: add Sentry metrics to network error boundary

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/EmailAddress/EmailAddress.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.tsx
- src/services/account/propTypes.js
- src/services/account/useAccountDetails.ts
shows the invoice and billing components when usesInvoice is true, regardless of the user's plan provider or rootOrganization.
Just adding a conditional to the component, one small thing I did was alias the zod shortcircuit thing with the schema so we could get the type inference throughout the app. I didn't realize it went away when I added the conditional so this is just to square away that front :) 
- Tested locally by going to the plans page
- From there, shortcircuited BillingDetails.tsx and LatestInvoiceCard.tsx with mock data (locally) to confirm it popped up as expected. 
- Screenshot above
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is …
> feat: Show invoice page when usesInvoice is true

- src/pages/PullRequestPage/PullCoverage/PullCoverage.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverage.spec.jsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChangedTab.tsx
- src/shared/FlagsNotConfigured/FlagsNotConfigured.jsx
When we hit an error on the Pulls page, there's a top level error component that renders instead of any of the content pages, even though the inner navbar still shows.
This PR intends to change that behavior such that we show both the content pages AND the error component at the same time
There are also some very small margin tweaks for some minor polish due to this new behavior (video below)
closes: https://github.com/codecov/engineering-team/issues/1179
https://github.com/codecov/gazebo/assets/159853603/ea2b09da-8ea4-41b2-b0d2-d99e5347249d
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …
> fix: #1179 - Show commits page even when missing head report

- src/pages/RepoPage/FlagsTab/Header/Header.jsx
- src/pages/RepoPage/FlagsTab/Header/Header.spec.jsx
Removes the search box from the flags tab as searching functionality is already provided by the flag selector.
Closes https://github.com/codecov/engineering-team/issues/1246
- Remove duplicate search box on flags tab
Before:
After:
> fix: Remove duplicate search box on flags tab

- src/shared/GlobalTopBanners/GlobalTopBanners.spec.tsx
- src/shared/GlobalTopBanners/GlobalTopBanners.tsx
Also show the install help banner in global top banners in addition to the limited experience. This closes [#1393](https://github.com/codecov/engineering-team/issues/1393). 
> [fix] Show install help banner in global top banners

- src/App.jsx
- src/App.spec.jsx
- src/layouts/Header/Dropdown.spec.jsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
Updates the redirect from `/` to go to `/login` instead of `/login/gh`.
Closes https://github.com/codecov/engineering-team/issues/1244
- Change base route's redirect
> feat: Redirect to general login instead of github

- src/pages/RepoPage/RepoPage.tsx
Fix the broken tab navigation to Rollup bundle onboarding
> fix: Rollup tab navigation in bundles onboarding is broken

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.tsx
This PR updates the `BundleSelect` component to use a state initializer function to set the initial state of the value only once, so search patterns are still maintained properly.
Closes codecov/engineering-team#1430
> fix: Bundle dropdown being empty when bundles are present

- src/services/pull/usePullTeam.tsx
Fixes https://github.com/codecov/internal-issues/issues/372. The zod schema was throwing an error when returned patch coverage is null and returning empty data. This change allows the coverage to be nullable similar to `usePull`.
> [fix] Make patch coverage on team plan nullable

- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileExplorer.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileExplorer.spec.jsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.tsx
This PR fixes https://github.com/codecov/engineering-team/issues/1455. Moves the `No Coverage Available` message to the table and keeps the select state instead of removing the filters altogether.
**BEFORE**
https://github.com/codecov/gazebo/assets/148245014/88994b8d-74ee-40c7-bea9-b10e9efffb05
**AFTER**
https://github.com/codecov/gazebo/assets/148245014/c7c1b957-83e1-472f-a8b6-0ba4da87ccb7
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I …
> Maintain filters on coverage tab when no data is present 

- src/services/repo/useRepoComponents.tsx
> fix: Move branch out of components filters

- src/sentry.ts
This PR makes it so that users are required to submit an email before submitting feedback through Sentry's feedback utility.
> feat: Make email field required when submitting feedback

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.tsx
I thought I had originally fixed this, but it seems to have creeped back in, this should fix the remaining issues with the bundle selector.
> fix: Fix bundle select not updating list of bundles when changing branch

- craco.config.js
Small change to how we grab the Sentry project value from the environment.
> build: Update sentry config

- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
Currently missing the case where there's no bundle selected and we get a bad response from the API, this PR solves that by adding in a new check for those cases.
- Update conditional rendering of the `BundleContent` component
> fix: Not showing select bundle when there is no bundle selected

- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/ComponentsTable.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/hooks/useRepoComponentsTable.js
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/hooks/useRepoComponentsTable.spec.js
This fixes:
- calling empty array of components as filters 
- padding for last uploaded 
> fix: Fix a couple of quick stuff for components tab

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BranchSelector.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BranchSelector.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.tsx
One more small fix, for an unseen case where it's redirecting to `/Select branch` 🤦
> fix: Do not redirect on select branch

- gazebo
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/CurrentPlanCard.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/CurrentPlanCard.tsx
- src/services/user/useResyncUser.js
We want to show the enterprise plan card (maybe not the best name anymore?) when usesInvoices is true; usesInvoices being a property on the user model set in Django admin.
> fix: Show enterprise plan card when usesInvoices true

- src/pages/RepoPage/ComponentsTab/BackfillBanners/TriggerSyncBanner/TriggerSyncBanner.spec.tsx
- src/pages/RepoPage/ComponentsTab/BackfillBanners/TriggerSyncBanner/TriggerSyncBanner.tsx
- src/pages/RepoPage/ComponentsTab/ComponentsTab.jsx
- src/pages/RepoPage/ComponentsTab/ComponentsTab.spec.jsx
- src/services/repo/useRepoComponents.tsx
- Fix a bug where branch selected is not being passed to the API
- Update the backfilling banners to align with the design doc:
fixes: https://github.com/codecov/engineering-team/issues/1602
fixes: https://github.com/codecov/engineering-team/issues/1603
> fix: components over time rendering and fix branch selecting

- README.md
The first build may take a while to start, so adding a note in the README in case other people run into the same problem.
The other change is a typo fix on line 169.
> Add a note to the README about the first `npm run start`

- .github/workflows/run-preview.yml
- .github/workflows/trigger-gazebo-preview.yml
This is an empty workflow that will prevent forks from running the gazebo preview deploy until the code is approved. We will then trigger from this workflow succeeding
> fix: create new gazebo preview trigger

- src/pages/AccountSettings/tabs/YAML/YAML.jsx
Little oopsie from me probably
> Fix Learn more casing in yaml editor

- src/pages/MembersPage/MembersList/MembersList.jsx
- src/pages/MembersPage/MembersList/MembersTable/MembersTable.tsx
- src/services/users/useInfiniteUser.tsx
Issue was that the page number was being manually set in the parent component, overriding the infinite query's automatic page handling.
Closes https://github.com/codecov/engineering-team/issues/1637
> Fix MembersTable duplicate users

- src/pages/AccountSettings/tabs/Admin/ManageAdminCard/AdminTable/AdminTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTableTeam/FilesChangedTableTeam.tsx
- src/pages/MembersPage/MembersList/MembersTable/MembersTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FilesChangedTable/FilesChangedTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/TableTeam/TableTeam.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.ts
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.tsx
- src/shared/ListRepo/ReposTable/ReposTable.tsx
- src/shared/ListRepo/ReposTableTeam/ReposTableTeam.tsx
The `.at()` method on arrays seems to still not be supported on some browsers.
Bracket notation functions the exact same at `.at()` for non-negative indexes.
Fixes all the `e.at is not a function` Sentry issues.
> Use bracket notation over array.at()

- src/pages/AnalyticsPage/Chart/Chart.jsx
- src/pages/AnalyticsPage/Chart/Chart.spec.jsx
- src/pages/AnalyticsPage/Chart/useCoverage.js
- src/pages/AnalyticsPage/Chart/useCoverage.spec.js
- src/services/charts/useReposCoverageMeasurements.spec.tsx
- src/services/charts/useReposCoverageMeasurements.ts
This PR swaps the data source on the analytics page from `max` to `avg` and adds in label informing users that the chart displays the average of all selected repos.
Closes codecov/engineering-team#1066
- Swap to fetching `avg` data
- Add in chat label
> feat: Swap to avg and add in data source label

- package-lock.json
- package.json
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
- src/pages/RepoPage/BundlesTab/BundlesTab.tsx
Update two routes from React-Router Routes to our Sentry wrapped Route, and bump to beta-4.
> fix: Small Sentry route fixes

- src/pages/RepoPage/ComponentsTab/Header/Header.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/ComponentsTable.tsx
- src/shared/ComponentsNotConfigured/ComponentsNotConfigured.tsx
fixes: https://github.com/codecov/engineering-team/issues/1666
- Change the icon in the "Get started with Components" button to white.
- Have a bottom border for components table when no data state (needs configuration, activate, backfilling)
- Remove the bottom border line of the header section
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> A few UI tweaks for coverage over time for components

- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/hooks/useRepoComponentsTable.spec.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/hooks/useRepoComponentsTable.ts
- src/pages/RepoPage/FlagsTab/subroute/FlagsTable/hooks/useRepoFlagsTable.spec.tsx
- src/pages/RepoPage/FlagsTab/subroute/FlagsTable/hooks/useRepoFlagsTable.ts
Bug was caused by trying to nullish coalesce on empty string - which is not nullish.
Closes https://github.com/codecov/feedback/issues/337
> Fix flag/component select 404 on flags and components tables

- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/IntroBlurb/IntroBlurb.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/IntroBlurb/IntroBlurb.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.jsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.jsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
First increment of onboarding changes. Adjusts title, banner, and page layout. Next PR to include new Card component.
[Design](https://www.figma.com/file/ICgJ2z5wJSxs0kzrtOp073/GH-1439?type=design&node-id=1-238&mode=design&t=sSmo8OEMnLvhAOzt-0)
- Move title into banner
- Move banner to above CI provider tabs
- Left align onboarding page
Before:
After:
> Update repo onboarding title position and page alignment

- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.jsx
- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.spec.jsx
- src/pages/AccountSettings/tabs/OrgUploadToken/useGenerateOrgUploadToken.js
Super small change removing the word `repository` from GUT page header, and toast cleaning things up a little bit.
- Remove `repository` from header and toast
- Update tests
> fix: Remove repository from GUT settings page header

- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
We want to only show this banner if current user is not activated and will be seeing unauthorized error once repo is configured. 
> fix: Only show activation banner for non activated users

- src/shared/utils/cn.spec.ts
- src/shared/utils/cn.ts
Adds `cn` function as a wrapper around both classnames and tailwind-merge. This is to be used in our new reusable components right out of the gate, but a longer term migration plan for old classnames instances may be in order.
> feat: Implement cn utility to wrap classnames and tailwind-merge

- src/ui/Card/Card.tsx
- src/ui/RadioTileGroup/RadioTileGroup.spec.tsx
- src/ui/RadioTileGroup/RadioTileGroup.stories.tsx
- src/ui/RadioTileGroup/RadioTileGroup.tsx
- src/ui/RadioTileGroup/index.ts
Adds a new RadioTileGroup component to be used in repo and bundle onboarding. Description added preemptively to work with Failed test onboarding designs, which is coming soon.
Uses radixui react radio group and react label as base for accessibility.
[Repo and bundle onboarding designs](https://www.figma.com/file/ICgJ2z5wJSxs0kzrtOp073/GH-1439?type=design&node-id=1-238&mode=design&t=AJwVUnmg0UpBAybr-0)
[Failed test onboarding designs](https://www.figma.com/file/MbfQ7BE0ENmUOPRIe6GMvV/GH-1494?type=design&node-id=1-2&mode=design&t=GQQKAWFEEFJNIV55-0)
Storybook:
> feat: Implement RadioTileGroup component

- src/pages/RepoPage/PullsTab/shared/Title/Title.tsx
Unlinks the PR author name on the pulls table. Currently the link just goes to the home page. Causes no visual changes.
Closes https://github.com/codecov/engineering-team/issues/1568
> fix: Unlink PR author on pulls table

- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
Show the banner if the repo is private, public repos can be viewed by all users anyway. 
> fix: Show banner for private repos only

- src/layouts/Footer/Footer.jsx
Bug introduced in https://github.com/codecov/gazebo/pull/2836, codecov Icon turned blue for some reason. This PR updates the color of the icon back to what it was previously.
**BUG**
**NO BUG**
> fix: Footer Codecov icon displaying incorrect color 

- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.tsx
Adds Card component to the bundle analysis onboarding page. Two more increments to come.
Part of https://github.com/codecov/engineering-team/issues/1439
Before:
After:
> style: Use Card component in bundle onboarding

- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
Updates the CI provider navigation in new repo onboarding to use the new RadioTileGroup component.
[Design](https://www.figma.com/file/ICgJ2z5wJSxs0kzrtOp073/GH-1439?type=design&node-id=1-238&mode=design&t=DWNl8qjORVenKYbd-0)
- Add new navigator on NewReopTab.tsx using RadioTileGroup component
- Rewrite NewRepoTab.tsx for better organization
- Add better testing for NewRepoTab.tsx
Before:
After:
> feat: Add radio button navigation to repo onboarding

- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/ComponentsTable.spec.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/ComponentsTable.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/DeleteComponentModal/DeleteComponentModal.spec.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/DeleteComponentModal/DeleteComponentModal.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/hooks/useRepoComponentsTable.spec.tsx
- src/services/repo/useRepoComponents.spec.tsx
- src/services/repo/useRepoComponents.tsx
fixes: https://github.com/codecov/engineering-team/issues/1702
The components table now displays component name instead of ID. This also fixes linking to the code tree view via clicking on the component names on the table
The codecov.yml file looks like this for components. Notice that the name is being displayed now, and "banker" has no name so the ID is showing.
```
individual_components:
- component_id: dictionary
name: DictionaryApp
paths:
- "**/dictionary.py"
- component_id: calculator
name: CalculatorApp
paths:
- "**/calculator.py"
flag_regexes:
- "unit"
- component_id: banker
paths:
- "**/banker.py"
flag_regexes:
- "integration"
```
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this …
> components over time display name instead of id

- src/ui/RadioTileGroup/RadioTileGroup.spec.tsx
- src/ui/RadioTileGroup/RadioTileGroup.stories.tsx
- src/ui/RadioTileGroup/RadioTileGroup.tsx
Adjusts the RadioTileGroup item's circle indicator such that it will overlay on the unselected indicator on all screen sizes. Happens to also simplify the css quite a bit!
Before:
After:
> style: Fix radio tile group indicator shifting on certain screen sizes

- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/IntroBlurb.tsx
- src/pages/RepoPage/CoverageOnboarding/IntroBlurb/IntroBlurb.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
Adds an intro banner to the BA onboarding page and also left aligns the page's layout to match designs. Radio button navigation to come next.
Part of https://github.com/codecov/engineering-team/issues/1439
Before:
After:
> feat: Add intro banner to bundle onboarding

- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
Converts the tab navigation on bundle analysis onboarding to use the new RadioTileGroup component.
Closes https://github.com/codecov/engineering-team/issues/1439
Before:
After:
> feat: Add radio button navigation to bundle analysis onboarding

- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.spec.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/ComponentsTable.spec.tsx
- src/pages/RepoPage/ComponentsTab/subroute/ComponentsTable/hooks/useRepoComponentsTable.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.spec.tsx
- src/pages/RepoPage/CoverageTab/CoverageTab.jsx
- src/pages/RepoPage/CoverageTab/CoverageTab.spec.jsx
- src/pages/RepoPage/CoverageTab/FirstPullRequestBanner/FirstPullRequestBanner.spec.tsx
- src/pages/RepoPage/CoverageTab/FirstPullRequestBanner/FirstPullRequestBanner.tsx
- src/pages/RepoPage/CoverageTab/FirstPullRequestBanner/index.ts
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.spec.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.spec.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/shared/RepoContentsResult.spec.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/shared/RepoContentsResult.tsx
- src/pages/RepoPage/DeactivatedRepo/DeactivatedRepo.spec.jsx
- src/pages/RepoPage/FlagsTab/subroute/FlagsTable/FlagsTable.spec.tsx
- src/pages/RepoPage/RepoPage.spec.tsx
- src/pages/RepoPage/RepoPageTabs.spec.tsx
- src/pages/RepoPage/context.spec.js
- src/services/repo/hooks.spec.tsx
- src/services/repo/useRepo.spec.tsx
- src/services/repo/useRepo.tsx
The purpose of this PR is to left the onboarding banner up the summary. The banner should be visible for the user under the coverage tab 
- Added `isFirstPR` field under repo. We needed a quick way to know whether this repo has an unmerged first PR in Codecov 
- Call repo hook in coverage tab. No need to call team settings in coverage tab not sure why we ever did that 
- Create the onboarding banner under coverage tab 
closes: https://github.com/codecov/engineering-team/issues/1541
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …
> fix: Move the banner above summary, and fix the use of team hook 

- src/pages/RepoPage/CoverageTab/CoverageTab.jsx
- src/pages/RepoPage/CoverageTab/CoverageTab.spec.jsx
- src/pages/RepoPage/CoverageTab/hooks/useCoverageTabData.spec.tsx
- src/pages/RepoPage/CoverageTab/hooks/useCoverageTabData.tsx
- src/pages/RepoPage/CoverageTab/subroute/CoverageChart/CoverageChart.jsx
- src/services/repo/useRepoCoverage.tsx
This PR contains a temp fix that hides the sunburst chart if there are more than 200,000 files in a given repo, until we have some more time to further investigate and come up with a solution for this.
- Grab file count in new `useCoverageTabData` hook
- Hide Sunburst currently if file count is less than or equal to `200_000`
- Update/add in tests
> fix: Hide sunburst on very large repos

- src/pages/RepoPage/BundlesTab/BundlesTab.spec.tsx
- src/pages/RepoPage/BundlesTab/BundlesTab.tsx
- src/pages/RepoPage/RepoPage.spec.tsx
- src/pages/RepoPage/RepoPage.tsx
This PR shuffles around how we render bundle onboarding tackling an infinite redirect issue we're currently seeing when a repo is not active ... but has bundle analysis enabled.
- Render `BundleOnboarding` directly in `RepoPage`
- Remove `BundleOnboarding` from `BundlesTab`
- Update tests
> fix: Directly render bundle onboarding

- src/ui/CodeSnippet/CodeSnippet.spec.tsx
- src/ui/CodeSnippet/CodeSnippet.stories.tsx
- src/ui/CodeSnippet/CodeSnippet.tsx
- src/ui/CodeSnippet/index.ts
Creates a proper reusable component for the code snippets we use across the app. PR to refactor existing snippets into this component to follow.
Closes https://github.com/codecov/internal-issues/issues/481
From Storybook:
> feat: Implement CodeSnippet component

- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
Refactors code snippet instances to use the new `CodeSnippet` component. Some tests had to be changed as a result of test id of the copyclipboard no longer being directly exposed - which is a drawback of the less than fully composable implementation we went with.
Closes https://github.com/codecov/internal-issues/issues/482
> ref: Convert onboarding code snippets to new component

- package-lock.json
- package.json
- src/ui/ExpandableSection/ExpandableSection.spec.tsx
- src/ui/ExpandableSection/ExpandableSection.stories.tsx
- src/ui/ExpandableSection/ExpandableSection.tsx
- src/ui/ExpandableSection/index.ts
This was requested by @Adal3n3 as we foresee this being used more in the future, this will be used in several areas in new onboarding for failed tests.
```
<ExpandableSection title="Click here">
<div>This is the collapsed section</div>
<ExpandableSection />
```
Create new ui component and stories.
https://github.com/codecov/gazebo/assets/91732700/d23b6470-4388-441f-8b70-e972ea44d3e4
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm …
> feat: Create a reusable component for expandable section

- src/pages/RepoPage/CoverageTab/Navigator/Navigator.spec.tsx
- src/pages/RepoPage/CoverageTab/Navigator/Navigator.tsx
- src/pages/RepoPage/CoverageTab/Navigator/index.ts
Implements and tests a radio button navigator for coverage tab navigation. This PR does not add the component to the page, however. That will be done in a future PR.
[Design](https://www.figma.com/design/4tPhxbAWxX2jAnoT2oXQPe/GH-722?node-id=291-4823&t=3n9YCviNQZkfXmkW-0)
Closes https://github.com/codecov/engineering-team/issues/1792
> feat: Implement radio button navigator for coverage tab

- src/shared/utils/extractUploads.js
- src/shared/utils/extractUploads.spec.js
We have custom logic on how we display regular and carried forward uploads in our commit page. The previous implementation omitted certain sessions due to the implementation of splice skipping indexes - more here https://stackoverflow.com/questions/9882284/looping-through-array-and-removing-items-without-breaking-for-loop. This change is to fix the implementation there.
Ticket: https://github.com/codecov/feedback/issues/352
- Adjusted the deleteDuplicate fn and added test for it
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …
> Correctly display cff's when many flags per upload

- src/layouts/Header/Dropdown.spec.tsx
- src/layouts/Header/Dropdown.tsx
Uses the new POST endpoint for Gazebo's sign out button. Currently logout by both POST and GET are supported on the API side, so we will change this and monitor for a day or so before completing the process and removing the GET endpoint API side.
Closes https://github.com/codecov/internal-issues/issues/487
> feat: Use new POST endpoint for logout

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/EmailAddress/EmailAddress.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/CreditCardForm.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentCard.spec.jsx
- src/ui/TextInput/TextInput.tsx
Updates the payment card component from using the split payment card to the single line Card Element. Also fixes a bug where the error message was just showing an empty banner (potentially regression from the stripe version upgrades?)
This also updates the email styling from the "billing" style to the "default" style.
Closes https://github.com/codecov/engineering-team/issues/1779
Closes https://github.com/codecov/engineering-team/issues/1759
**BEFORE**
**AFTER**
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and …
> feat: Update Edit Payment Card Component to use Stripe Card Element

- src/services/repo/useRepoCoverage.tsx
Fixes potential 404 on repo page. Noticed this causing a 404 due to failed parsing on a new repo today.
> fix: Make commit totals type nullable

- src/pages/RepoPage/FailedTestsTab/GitHubActions/FrameworkTabs/FrameworkTabs.tsx
Just a small fix to always apply a border that's transparent when not selected and set the colour when it is, which removes the jumping text when selected. Also a few tweaks to the TS so that we don't need to cast types.
- Use `border-transparent` as default style so that we always account for the border height
- Small TS tweaks
- Use the new built-in `clipboard` functionality from the `CodeSnippet` component (thanks @spalmurray-codecov)
Before: 
https://github.com/codecov/gazebo/assets/105234307/1e9f4087-6326-4e99-8f59-333d75fcbbe9
After:
https://github.com/codecov/gazebo/assets/105234307/7f8090d1-5ece-4810-87ad-98ce3e0a2c69
> fix: Small fix to remove jumping tab text

- src/pages/RepoPage/FailedTestsTab/FailedTestsTab.spec.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsTab.tsx
- src/pages/RepoPage/RepoPage.spec.tsx
- src/pages/RepoPage/RepoPage.tsx
- src/pages/RepoPage/RepoPageTabs.spec.tsx
- src/pages/RepoPage/RepoPageTabs.tsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
Instead of `/tests` use `/tests/new` and `/tests/new/codecov-cli`, reflecting other onboarding routes experience and making the development of `/tests` in dashboard easier  
Routes:
https://github.com/codecov/gazebo/assets/91732700/1cfe5731-ad10-49f2-993e-14de090c2d8b
> fix: Update /tests routes to reflect other onboarding routes

- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/shared/RepoContentsResult.spec.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/shared/RepoContentsResult.tsx
Moving all err checks to RepoContentResults, and remove banner for consistency. 
> fix: Move err checks to repo content results

- src/services/account/useUpdateCard.spec.tsx
- src/services/account/useUpdateCard.ts
- src/services/account/useUpgradePlan.spec.tsx
- src/services/account/useUpgradePlan.ts
Just converting a couple hooks over to TS and adding related types
- useUpgradePlan
- useUpdateCard
Closes https://github.com/codecov/engineering-team/issues/1861
Closes https://github.com/codecov/engineering-team/issues/1862
Example of updating a credit card:
https://github.com/codecov/gazebo/assets/159853603/2c26863b-b0a1-4943-8b6f-532a305e1bbd
Example of changing a plan:
https://github.com/codecov/gazebo/assets/159853603/3e89173b-f140-409d-8d15-d09df8ba7fd1
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and …
> ref: convert billing hooks to TS

- src/ui/SessionExpiryTracker/SessionExpiryTracker.tsx
Adds in a redirect in `SessionExpiryTracker` for self hosted instances.
> fix: Add in redirect for self hosted in SessionExpiryTracker

- src/pages/RepoPage/ComponentsTab/BackfillBanners/TriggerSyncBanner/TriggerSyncBanner.spec.tsx
- src/pages/RepoPage/ComponentsTab/BackfillBanners/TriggerSyncBanner/TriggerSyncBanner.tsx
This PR changes the text as the ticket designates. "Enable component analytics" text is now bolded and italicized.
https://github.com/codecov/engineering-team/issues/1843
> fix: clarify components text for enabling analytics

- src/shared/ListRepo/RepoTitleLink/RepoTitleLink.jsx
- src/shared/ListRepo/ReposTable/ReposTable.tsx
- src/shared/ListRepo/ReposTableTeam/ReposTableTeam.tsx
Fixes vertical alignment of a few elements on the repos table for small screen sizes and/or long repo names.
Closes https://github.com/codecov/engineering-team/issues/1883
Pro view:
Team view:
Unconfigured repo:
Pro view:
Team view:
Unconfigured repo:
> Fix alignment of elements on ReposTable

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentCard.spec.jsx
This PR aims to fix situations where a user doesn't have a default payment method but does have a stripe subscription, and is unable to update their card.
Originally, we were checking to see if the user didn't have a card, but was a paying customer, and then showing the "no card set message," but looking at the serializer and data we were keying off of, [plan has never existed on a subscriptionDetail](https://github.com/codecov/codecov-api/blob/83a55770400f5693bac483d0de68a0593b39ad27/api/internal/owner/serializers.py#L184-L193) and so that condition was always returning false.
Because a user without a default payment method also didn't have a card (referring to the condition !card && !payingCustomer), we were essentially always hiding the billing update screen from the user when they …
> fix: User unable to update card if no default payment method

- src/pages/RepoPage/CoverageTab/CoverageTab.tsx
Fixes bug with branch selector introduced in new information architecture update. 
Issue is as pictured below, branch was not getting pulled out of the url by useParams as it was before. Problem was that the route matcher at the CoverageTab level needed explicit param definitions instead of a catch-all matcher.
> fix: Branch selector redirect broken after info architecture update

- src/layouts/Header/Header.tsx
- src/layouts/LoginLayout/LoginLayout.spec.tsx
- src/layouts/LoginLayout/LoginLayout.tsx
Shows the new guest header on the Login page. Previously, we had a special header for this page, but we've decided to replace this with the guest header. 
Had some ideas to clean up the code here a bit more, but decided to leave as is because I'll be making big changes to our header over the next couple weeks.
Closes https://github.com/codecov/engineering-team/issues/1819
Before:
After:
> feat: Show new guest header on Login page

- src/services/account/useUpdateBillingAddress.spec.tsx
- src/services/account/useUpdateBillingAddress.ts
Part of the Q2 billing epic, particularly around updates for edit billing details, this PR aims to add a a new hook for updating the user's billing address that will be used when we add the stripe address component to the plan page.
For now, the hook is hardcoded to use Sentry's address, and isn't being used anywhere just yet. I wanted to try and isolate gazebo PR's to small chunks to make it easier to review. Directly relates to https://github.com/codecov/codecov-api/pull/611 which adds the service function in API
Closes https://github.com/codecov/engineering-team/issues/1864
N/A
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need …
> feat: Create "dumb" useUpdateBillingAddress hook

- src/pages/LoginPage/LoginPage.jsx
- src/pages/LoginPage/LoginPage.spec.jsx
Update link to point to new dedicated cloud docs.
Just an updated version of #2527
- Update link on login page
- Update tests
> fix: Update self hosted link on login page

- .github/workflows/ci.yml
- package.json
- src/pages/RepoPage/FailedTestsTab/GitHubActions/GitHubActions.spec.tsx
Adds a check to the CI run that will fail if Prettier check fails. This should only happen if you commit with `--no-verify` as we run Prettier formatting in a commit hook. That said, the reason for adding this is because some way or another it seems we do get non-pretty stuff merged from time to time.
> feat: Add Prettier check to ci

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/Address/AddressCard.tsx
Saw address 2 was coming back as null and showing on the UI, we want to hide it.
**BEFORE**
**AFTER**
> fix: Hide Address 2 if null

- package-lock.json
- package.json
As I'm closely working on adding in a new chart for bundle data I thought it fit to update our as FormidableLabs has released  [v37.0.0](https://github.com/FormidableLabs/victory/releases/tag/v37.0.0), there are no breaking changes, just dropping support for older browsers.
- Update version
> chore: Update to latest version of victory for charts

- src/layouts/EnterpriseLoginLayout/EnterpriseLoginLayout.spec.tsx
- src/layouts/EnterpriseLoginLayout/EnterpriseLoginLayout.tsx
- src/layouts/LoginLayout/LoginLayout.spec.tsx
- src/layouts/LoginLayout/LoginLayout.tsx
- src/ui/SessionExpiryTracker/SessionExpiryTracker.spec.tsx
- src/ui/SessionExpiryTracker/SessionExpiryTracker.tsx
This stemmed from thinking through what is causing the redirect, which is the presence of the expiration cookie timestamp.
That cookie is added on login here: https://github.com/codecov/codecov-api/blob/c3f5e7f903c63f8a5eadc5a69a2846df57e65a0a/codecov_auth/views/github.py#L169-L171 in API on login, and only for Github
Because we're already setting a "session expired" key here: https://github.com/codecov/gazebo/blob/902fa2fcff89b96d1fc0ab470a22b7088b21fc61/src/ui/SessionExpiryTracker/SessionExpiryTracker.tsx#L74 and that key is removed and reset only when the user logs in, since Session Expiry Tracker is only present on the BaseLayout here: https://github.com/codecov/gazebo/blob/5d142294fee83428c92ca4f33a8861a7e15b4dde/src/layouts/BaseLayout/BaseLayout.jsx#L72
My hunch is that we shouldn't …
> fix: Remove Cookie Session Expiry cookie when expired and redirect

- src/services/bundleAnalysis/index.ts
- src/services/bundleAnalysis/useBundleTrendData.spec.tsx
- src/services/bundleAnalysis/useBundleTrendData.tsx
This PR adds in a hook to fetch the trend data for a given branch + bundle, with additional options for time range, data interval, and report type filters.
Closes #1800
```ts
const { data, /* ... */ } = useBundleTrendData({
provider: 'gh',
owner: 'codecov',
repo: 'codecov',
branch: 'main',
bundle: 'test-bundle',
interval: 'INTERVAL_1_DAY',
after: '2024-06-15T03:00:00.000Z',
before: '2024-06-20T03:00:00.000Z',
filters: {
assetTypes: ['REPORT_SIZE'],
},
})
```
- Add in new `useBundleTrendData` hook
- Add in tests
> feat: Create hook to fetch bundle trend data

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSelector.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.tsx
This PR updates the `BundleSelector` component by having it default to the first bundle in the returned list of bundles and select it for the user.
Closes #1783
- Update `BundleSelector` to set bundle to first one from list
- Update tests
https://github.com/codecov/gazebo/assets/105234307/71cca61f-db93-46db-bc46-fb60cf5d4891
> feat: Select first bundle on bundles tab

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.spec.jsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
- src/services/codecovEventMetrics/index.ts
- src/services/codecovEventMetrics/useStoreCodecovEventMetric.spec.tsx
- src/services/codecovEventMetrics/useStoreCodecovEventMetric.tsx
This closes https://github.com/codecov/engineering-team/issues/1830. 
Notion: https://www.notion.so/sentry/Eng-Design-Tracking-Codecov-user-signup-to-first-commit-conversion-rate-6097411516f84563820276aafe3436ea
The useStoreCodecovMetric hook calls the storeCodecovMetric mutation [defined in API
](https://github.com/codecov/engineering-team/issues/1829) There are already a few layers of validation to sanitize input and prevent duplicate entries. In this PR, another check is added so as not to overcrowd the number of client network requests. 
We store all added metrics in `localstorage` and do not make a request if the client sees that we have already added that metric. The size of what can go into the `localstorage` object is also restricted to 30 entires to be reasonable with space …
> [feat] Add user onboarding metrics tracking + mutation 

- src/shared/utils/bundleAnalysis.spec.ts
- src/shared/utils/bundleAnalysis.ts
- src/ui/BundleTrendChart/BundleTrendChart.spec.tsx
- src/ui/BundleTrendChart/BundleTrendChart.stories.tsx
- src/ui/BundleTrendChart/BundleTrendChart.tsx
- src/ui/BundleTrendChart/NoBundleData.tsx
- src/ui/BundleTrendChart/chart.css
- src/ui/BundleTrendChart/index.ts
This PR adds in a new `ui/BundleTrendChart` component which will be added into the bundle tab shortly providing trend data for users and their bundles.
Closes codecov/engineering-team#1801
- Add in `ui/BundleTrendChart`, CSS, and `NoData` component
- Add in tests and stories
- Add in new helper function
> feat: Create BundleTrendChart

- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/AssetsTable.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.spec.tsx
- src/services/bundleAnalysis/useBundleAssets.spec.tsx
- src/services/bundleAnalysis/useBundleAssets.tsx
This PR updates the `useBundleAssets` hook to grab a bit more data including the total bundle size, and the measurements for each possible asset. I have temporarily provided place holder values for the interval and dates for the measurements until we have the rest of the page hooked up with the trend chart and time frame selector.
Closes codecov/engineering-team#1803
- Update `useBundleAssets` to grab total bundle size, and asset measurements
- Update tests
> feat: Update useBundleAssets service to grab asset measurements

- src/pages/RepoPage/CoverageTab/ComponentsTab/subroute/ComponentsTable/ComponentsTable.spec.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.spec.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.tsx
See [design](https://www.figma.com/design/y0XTfMFA4gXnMEe5JsZ753/GH-1269?node-id=19-1045&t=l24ROFhzK2uJYtIu-0).
https://github.com/codecov/engineering-team/issues/1453 is the original issue. 
Since we auto update the coverage totals already, this issue has been updated to sum up the column totals in each row(excluding name and coverage %) IFF we have 2 or more rows. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can …
> [gazebo] Add subtotals row on coverage page + test fix

- src/services/defaultOrganization/useUpdateDefaultOrganization.spec.tsx
- src/services/defaultOrganization/useUpdateDefaultOrganization.ts
Redirect on clicking "Continue" button was technically working and rerouting correctly but the new user info after mutating the user's -> owner -> defaultOrgUsername wasn't being refreshed so the code still thought we needed to show the org selector component. As it exists, a refresh after clicking continue would reflect the correct behavior. With this change to invalidate the query, we now will get the new user data and change the UI accordingly.
Closes https://github.com/codecov/engineering-team/issues/1842
https://github.com/codecov/gazebo/assets/170470397/c9c76dbf-531e-499b-ae3d-305da6ebda08
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is …
> fix: refresh user query on continue from org selection

- src/layouts/BaseLayout/BaseLayout.jsx
- src/layouts/BaseLayout/BaseLayout.spec.jsx
- src/layouts/Header/Header.spec.tsx
- src/layouts/Header/Header.tsx
- src/layouts/Header/index.ts
- src/layouts/LoginLayout/LoginLayout.spec.tsx
- src/layouts/LoginLayout/LoginLayout.tsx
- src/pages/AccountSettings/shared/Header/Header.jsx
- src/pages/AccountSettings/shared/Header/Header.spec.jsx
- src/pages/AdminSettings/AdminSettingsHeader/AdminSettingsHeader.jsx
- src/pages/AdminSettings/AdminSettingsHeader/AdminSettingsHeader.spec.jsx
- src/pages/AnalyticsPage/AnalyticsPage.jsx
- src/pages/AnalyticsPage/AnalyticsPage.spec.jsx
- src/pages/CommitDetailPage/CommitDetailPage.spec.tsx
- src/pages/CommitDetailPage/CommitDetailPage.tsx
- src/pages/MembersPage/MembersPage.jsx
- src/pages/MembersPage/MembersPage.spec.jsx
- src/pages/OwnerPage/OwnerPage.jsx
- src/pages/OwnerPage/OwnerPage.spec.jsx
- src/pages/PlanPage/PlanPage.jsx
- src/pages/PlanPage/PlanPage.spec.jsx
- src/pages/PullRequestPage/PullRequestPage.spec.tsx
- src/pages/PullRequestPage/PullRequestPage.tsx
- src/pages/RepoPage/RepoBreadcrumb.jsx
- src/pages/RepoPage/RepoPage.spec.tsx
Hides all primary and secondary Navs along with old header whenever the `newHeader` feature flag is `true`. This is prep for implementing the new header/nav and will not affect any users until the proper rollout of the feature.
Closes https://github.com/codecov/engineering-team/issues/1935
Closes https://github.com/codecov/engineering-team/issues/1951
> feat: Hide old header stuff when new header flag is true

- src/pages/RepoPage/BundlesTab/BundleContent/BundleChart/BundleChart.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleChart/BundleChart.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleChart/TrendDropdown.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleChart/TrendDropdown.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleChart/index.ts
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSummary/BundleSummary.tsx
- src/shared/utils/bundleAnalysis.spec.ts
- src/shared/utils/bundleAnalysis.ts
- src/ui/BundleTrendChart/BundleTrendChart.tsx
This PR puts all of the pieces together and adds in the bundle chart component to the bundles tab.
Blocked by #2983
Closes codecov/engineering-team#1802
- Add in `TrendDropdown` component for bundle selecting
- Add in `BundleChart` component
- Add `BundleChart` to `BundleContent`
- Adjust `BundleSummary` styles
> feat: Add in bundle chart

- src/pages/RepoPage/BundlesTab/BundleContent/BundleChart/BundleChart.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/ToggleElement/ToggleElement.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/ToggleElement/ToggleElement.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/ToggleElement/index.ts
This PR quickly adds in a `ToggleElement` component that allows the user to toggle the trend chart on the bundles tab, when toggling it will save the value to local storage so it remembers the users preference upon re-visiting the page.
- Add in `ToggleElement` component
- Make `BundleChart` slight narrower
- Wrap `BundleChart` with `ToggleElement`
https://github.com/codecov/gazebo/assets/105234307/218f6b69-26eb-47ff-b9e8-eb506fbb4ea2
> feat: Add show/hide chart toggle on bundles tab

- src/layouts/BaseLayout/BaseLayout.spec.jsx
- src/layouts/Header/Header.spec.tsx
- src/layouts/Header/Header.tsx
- src/layouts/Header/components/UserDropdown/UserDropdown.spec.tsx
- src/layouts/Header/components/UserDropdown/UserDropdown.tsx
- src/layouts/Header/components/UserDropdown/index.ts
- src/layouts/LoginLayout/LoginLayout.spec.tsx
- src/layouts/OldHeader/Dropdown.tsx
- src/pages/OwnerPage/Header/Header.jsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTable/Title/Title.tsx
- src/pages/RepoPage/CommitsTab/CommitsTable/Title/Title.tsx
- src/pages/RepoPage/PullsTab/PullsTable/Title/Title.tsx
- src/ui/Avatar/Avatar.jsx
- src/ui/ContextSwitcher/ContextSwitcher.jsx
- src/ui/List/List.stories.jsx
Implements the UserDropdown for the new Header. For now, this is an almost exact copy the old user dropdown, but we'll move this over to the new Dropdown component once we implement that in https://github.com/codecov/engineering-team/issues/1942. The only difference between this and the old user dropdown is minor spacing change and dark border on the Avatar.
[Design](https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385&t=oCWsofSFCNg0QXiK-0)
Closes https://github.com/codecov/engineering-team/issues/1952
> feat: Implement new header's User dropdown

- src/services/bundleAnalysis/useBundleAssets.tsx
- src/services/bundleAnalysis/useBundleTrendData.tsx
Aligning these queries with updates to the API.
> chore: Make after nullable for BA queries

- src/pages/AccountSettings/tabs/OktaAccess/OktaAccess.spec.tsx
- src/pages/AccountSettings/tabs/OktaAccess/OktaConfigForm/OktaConfigForm.spec.tsx
- src/pages/AccountSettings/tabs/OktaAccess/OktaConfigForm/OktaConfigForm.tsx
- src/pages/AccountSettings/tabs/OktaAccess/hooks/index.ts
- src/pages/AccountSettings/tabs/OktaAccess/hooks/useOktaConfig.spec.tsx
- src/pages/AccountSettings/tabs/OktaAccess/hooks/useOktaConfig.tsx
- src/pages/AccountSettings/tabs/OktaAccess/hooks/useUpdateOktaConfig.spec.tsx
- src/pages/AccountSettings/tabs/OktaAccess/hooks/useUpdateOktaConfig.tsx
waiting for: 
Now that API is ready, i'm creating 2 new hooks:
- Fetch okta config values 
- Mutate okta config values 
- Create new hooks 
- New changes in form 
- Tests 
https://github.com/codecov/gazebo/assets/91732700/684ca743-33bd-4561-a00b-1a3a3980a5b6
https://github.com/codecov/gazebo/assets/91732700/e18ca6d2-1b7d-468f-abf5-1cec11d4bfbe
closes: https://github.com/codecov/engineering-team/issues/1983 and https://github.com/codecov/engineering-team/issues/2044
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and …
> feat: Create OKTA hooks and hook them up with form 

- src/layouts/EnterpriseLoginLayout/Header/Header.tsx
- src/layouts/Header/Header.spec.tsx
- src/layouts/Header/Header.tsx
- src/layouts/Header/components/AdminLink/AdminLink.spec.tsx
- src/layouts/Header/components/AdminLink/AdminLink.tsx
- src/layouts/Header/components/AdminLink/index.ts
- src/layouts/Header/components/SeatDetails/SeatDetails.spec.tsx
- src/layouts/Header/components/SeatDetails/SeatDetails.tsx
- src/layouts/Header/components/SeatDetails/index.ts
- src/layouts/OldHeader/DesktopMenu.tsx
- src/ui/A/A.jsx
Adds self-hosted/enterprise header items.
[Design](https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385&t=obSouBUmcJD9rdK1-0)
Closes https://github.com/codecov/engineering-team/issues/1954
> feat: Add self-hosted items to new header

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/BillingDetails.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/BillingDetails.tsx
- src/services/account/useAccountDetails.ts
Zod schema failing to parse account-details endpoint due to incorrect schema type.
This PR updates with the correct schema type, parsing bare minimum we need from tax info. Tested locally by hard coding customer data into local and confirming page now loads correctly.
> fix: Update schema for account details with correct tax info

- src/services/account/useAccountDetails.ts
useAccountDetails zod schema parser was failing due to lack of .nullish() check on defaultPaymentMethod  card property. We didn't realize that users using Link would run into this issue, but this looks to fix it.
> fix: nullish defaultPaymentMethod for Link users

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/Address/AddressCard.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/Address/AddressCard.tsx
Just doing a little polish for the nulls that appear when some user address info doesn't exist
> fix: Nulls when address info doesn't exist on Plan page

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.spec.jsx
- src/pages/TermsOfService/TermsOfService.spec.tsx
- src/pages/TermsOfService/TermsOfService.tsx
- src/ui/Button/Button.stories.jsx
Closes https://github.com/codecov/engineering-team/issues/1940
Added a story for Listbox variant of the Button as it seems like it was missed.
I believe keeping copy text as "Which organization" is more grammatically correct for org selector as we have a list.
Figma: bottom of [https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385&t=rNtuPGrNv5Adbn8H-1](url)
https://github.com/user-attachments/assets/c1ba2f75-66ed-4023-985e-63d3ada3cc96
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: …
> feat: add back and cancel btns to TOS and Org select pages

- src/layouts/BaseLayout/hooks/useUserAccessGate.js
- src/layouts/BaseLayout/hooks/useUserAccessGate.spec.tsx
When user set customer intent to personal on onboarding, their default org is always their personal account, this PR is fixing the bug to allow user to switch between default orgs despite their customer intent after the first login. 
Closes: https://github.com/codecov/internal-issues/issues/586
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> fix: Don't fire update default org if user already has a default org

- src/layouts/Header/Header.spec.tsx
- src/layouts/Header/Header.tsx
- src/layouts/Header/components/Navigator/MyContextSwitcher.spec.tsx
- src/layouts/Header/components/Navigator/MyContextSwitcher.tsx
- src/layouts/Header/components/Navigator/Navigator.spec.tsx
- src/layouts/Header/components/Navigator/Navigator.tsx
- src/services/user/useMyContexts.ts
- src/services/user/useOwner.js
- src/services/user/useUser.ts
- src/ui/Breadcrumb/Breadcrumb.jsx
- src/ui/ContextSwitcher/ContextSwitcher.jsx
Adds logic for adjusting the navigator shown on different pages of the app along with actually rendering those navigators.
I'm still doing another styling pass over everything so please ignore minor styling issues for now!
[Design](https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=327-2668&t=Ds53xQRyUmGhvcmF-0)
Owner page shows Context switcher for navigation:
Self-hosted admin settings uses a breadcrumb:
Repo page uses a breadcrumb:
> feat: Implement remaining Navigator functionality for new header

- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/RenderError.tsx
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/Upload.jsx
Fixing text wrap + place of error in upload card.
issue: https://github.com/codecov/engineering-team/issues/2085 
> fix: Move render error down the download link in upload card. 

- package-lock.json
- package.json
- src/layouts/Header/components/HelpDropdown/HelpDropdown.spec.tsx
- src/layouts/Header/components/HelpDropdown/HelpDropdown.tsx
Fixes bug where the Sentry feedback modal would disable scrolling on the page and not reenable it on close. Also updates Sentry sdk to latest version (not necessary for fix).
> fix: Help dropdown user feedback scrolling bug

- docker/start-nginx.sh
The old string replacement isn't correct, this handles a case where a string eg r.Ay.GHE_URL doesn't get replaced because we only expect exactly 1 character between the 2 dots. This fix will match at least one character between the 2 dots.
> fix enterprise url not properly being set during build

- .yarnrc.yml
- package.json
- src/ui/Dropdown/Dropdown.spec.tsx
- src/ui/Dropdown/Dropdown.stories.tsx
- src/ui/Dropdown/Dropdown.tsx
- yarn.lock
Creating Dropdown component with new shadcn/radix/cva archetype.
Closes https://github.com/codecov/engineering-team/issues/1942
Figma: section 2 of https://www.figma.com/design/kbJfmcDgAuptsJR5KB28O9/GH-293-(nav%2C-header%2C-and-related-elements)?node-id=322-1385&t=Nga242WoJqfXLEvv-1
Storybook: https://preview-pr-3020-storybook.codecov.dev/
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> feat: new ui dropdown component

- src/pages/CommitDetailPage/CommitCoverage/BotErrorBanner/BotErrorBanner.jsx
Previously, there was no space between `to InstallCodecov's App`, which is fixed now.
I also removed the `span`, as all other error variants don’t have one either.
> Fix Whitespace in `BotErrorBanner`

- src/layouts/Header/Header.tsx
Hides the self-hosted header items on small screen sizes as they clutter things up and make weird layouts occur.
> style: Hide self-hosted header items on small screen sizes

- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/TerminalInstructions/InstructionBox.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/TerminalInstructions/InstructionBox.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/TerminalInstructions/instructions.ts
Closes https://github.com/codecov/engineering-team/issues/1812
Figma: https://www.figma.com/design/oSgW7AFOXDr1TGrkWh79kV/GH-1812?node-id=1-488&t=H7qE1Ij99oPCP235-1
Cloud:
OLD Self-Hosted (step 3): <img width="1045" alt="old_enterprise_step_2" src="https://github.com/user-attachments/assets/1ad22652-1fc2-428a-9cfb-7f0fad95136f">
NEW Self-Hosted (step 3 now same as cloud):<img width="1027" alt="new_enterprise" src="https://github.com/user-attachments/assets/fecb1f44-fabc-4c5c-a173-1e4e5a60e88c">
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I …
> Other CLI New repo onboarding text changes

- src/pages/RepoPage/FailedTestsTab/hooks/index.ts
- src/pages/RepoPage/FailedTestsTab/hooks/useInfiniteTestResults.spec.tsx
- src/pages/RepoPage/FailedTestsTab/hooks/useInfiniteTestResults.tsx
Create hook for test results new table
closes: https://github.com/codecov/engineering-team/issues/2071
> feat: Create hook for test results

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PlanTypeOptions/PlanTypeOptions.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PlanTypeOptions/PlanTypeOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateBlurb/UpdateBlurb.tsx
Slight regression from https://github.com/codecov/gazebo/pull/2739, no longer pulling the query param if exists when user has a sentryId and clicks upgrade plan from developer (free) plan state
This only affected users who had a sentry account linked
Also fixed a small issue where user was on Free plan -> Pro plan and the bullet point showing `You are changing from the Developer plan to the [Pro plan]`
Closes https://github.com/codecov/engineering-team/issues/2051
https://github.com/user-attachments/assets/2f6ebdf3-f181-42a8-9fe6-5a710e9083fb
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …
> fix: show team plan on upgrade plan page when click team upgrade and has sentryId

- src/mocks/handlers.js
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.tsx
- src/services/account/mocks.ts
- src/services/account/useAccountDetails.ts
This PR aims to add the delinquent alert banner when the user has a payment due. We pull the user's delinquent status off the account-details endpoint, and if true, render the banner
I decided to just create a simple ad-hoc component within the CurrentOrgPlan component since it was just a tiny banner; we may need to pull these alert banners out into a separate component at some point though. _maybe_
Also adds a small UT
Depends on https://github.com/codecov/codecov-api/pull/706
Closes https://github.com/codecov/engineering-team/issues/1814
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …
> feat: Add delinquent alert when user has due payment

- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/hooks/useRepoConfigurationStatus/useRepoConfigurationStatus.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/hooks/useRepoConfigurationStatus/useRepoConfigurationStatus.tsx
Implements useRepoConfigurationStatus, which is the data fetching hook for the new Configuration Manager settings page. No invocation exists yet as it will come in a future PR. Just hook implementation and unit tests here.
> feat: Implement useRepoConfigurationStatus

- src/pages/AccountSettings/tabs/YAML/YamlEditor/YamlEditor.tsx
- src/pages/AccountSettings/tabs/YAML/YamlEditor/codecov-theme.css
- src/pages/RepoPage/SettingsTab/tabs/YamlTab/YAML/YAML.jsx
Closes https://github.com/codecov/engineering-team/issues/1851
Changing the focus color of the cursor to be the same as its unfocused version when the editor is read-only
Read-only version:
Editable version:
> fix: make readonly yaml editor appear less editable

- package.json
- src/pages/AccountSettings/tabs/Profile/NameEmailCard/NameEmailCard.jsx
- src/pages/AccountSettings/tabs/Profile/NameEmailCard/NameEmailCard.spec.jsx
- yarn.lock
Saw we were using a package called "yup," and was wondering what it was used for. Realized it's basically just zod, and that there was only one usage in the codebase
Looked simple enough to remove and we save 18KB from doing so!
- https://bundlephobia.com/package/yup@0.32.11 for ref
- **Edit:** Apparently bundle analysis is telling us 33KB, even better!
Closes https://github.com/codecov/engineering-team/issues/2153
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping …
> dev: Remove yup and convert to zod

- .eslintrc.json
- src/layouts/Header/components/HelpDropdown/HelpDropdown.tsx
- src/layouts/Header/components/UserDropdown/UserDropdown.tsx
- src/old_ui/Icon/Icon.spec.jsx
- src/pages/RepoPage/FailedTestsTab/GitHubActions/FrameworkTabs/FrameworkTabs.tsx
- src/pages/RepoPage/SettingsTab/tabs/YamlTab/YAML/YAML.jsx
- src/shared/utils/cn.spec.ts
- src/ui/FileViewer/ToggleHeader/Title/Title.tsx
Updates our tailwind eslint plugin's config to use their recommended configuration. Also fixes all eslint warnings in the repo - so we no longer will get this at the bottom of every PR's files changed tab:
> chore: Use recommended tailwind eslint plugin config and fix warnings

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/InfoMessageStripeCallback/InfoMessageStripeCallback.spec.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/InfoMessageStripeCallback/InfoMessageStripeCallback.tsx
This closes https://github.com/codecov/engineering-team/issues/1795.
The error banner will no longer render when the user navigates back from the stripe checkout session. We have a `DelinquentAlert` in the parent component that handles any relevant messaging. 
> Remove the "Subscription Update Failed" banner when there is no error

- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/hooks/useRepoConfigurationStatus/useRepoConfigurationStatus.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
Implements the Coverage group of feature for the configuration manager page in repo settings. We may come back to change some of these links. Will be discussing this project more with design and product next week, but this can be merged now as-is since it's behind a feature flag.
I have okayed the use of Card header and footer with design - but this change is not reflected in figma yet.
[Design](https://www.figma.com/design/JTajBZUaEeqfijoy1mCDsz/GH-1509?node-id=1-238&t=RJi59kHV7GIoPEge-0)
Closes https://github.com/codecov/engineering-team/issues/2106
Screenshots showing all the items working:
> feat: Implement coverage group for configuration manager page

- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
- src/shared/GlobalTopBanners/OktaBanners/OktaBanners.spec.tsx
- src/shared/GlobalTopBanners/OktaBanners/OktaBanners.tsx
- src/shared/GlobalTopBanners/OktaEnabledBanner/OktaEnabledBanner.spec.tsx
- src/shared/GlobalTopBanners/OktaEnabledBanner/OktaEnabledBanner.tsx
- src/shared/GlobalTopBanners/OktaEnforcedBanner/OktaEnforcedBanner.spec.tsx
- src/shared/GlobalTopBanners/OktaEnforcedBanner/OktaEnforcedBanner.tsx
-  render the banners when the user is not authenticated 
-  hide the banners behind the feature flag 
- redirect the user to` /login/okta/provider/owner` as okta requests this info 
> fix: Update with some okta tweaks

- src/shared/utils/ownerHelpers.js
Noticed [this issue](https://codecov.sentry.io/issues/3747448258/?project=5514400&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=0) seems to be happening quite a bit, so I tested locally and found that we don't have a url mapper for the 'github' provider, only for 'gh'. This PR adds a mapper for 'github'.
> fix: Avatars not loading for github provider

- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/hooks/useRepoConfigurationStatus/useRepoConfigurationStatus.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/hooks/useRepoConfigurationStatus/useRepoConfigurationStatus.tsx
Implement bundle analysis feature group for configuration manager tab.
[Design](https://www.figma.com/design/JTajBZUaEeqfijoy1mCDsz/GH-1509?node-id=99-500&t=s353tqca2PXZhQOZ-0)
Closes https://github.com/codecov/engineering-team/issues/2109
> feat: Implement Bundle analysis feature group

- src/pages/RepoPage/FailedTestsTab/FailedTestsTable/FailedTestsTable.tsx
Update avgDuration, failureRate and commitFailed columns to numeric data type
> fix: Use numeric type on Failed Test Table columns

- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
Adds the breadcrumb to the bundle content page, where prior it didn't exist
Closes https://github.com/codecov/engineering-team/issues/2062
**BEFORE**
**AFTER**
> fix: add breadcrumb to bundle content page

- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.spec.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/ErrorBanner/ErrorBanner.spec.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/ErrorBanner/ErrorBanner.tsx
- src/pages/CommitDetailPage/CommitCoverage/ErrorBanner/ErrorBanner.spec.tsx
- src/pages/CommitDetailPage/CommitCoverage/ErrorBanner/ErrorBanner.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/ErrorBanner/ErrorBanner.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/ErrorBanner/ErrorBanner.tsx
- src/pages/PullRequestPage/PullCoverage/ErrorBanner/ErrorBanner.jsx
Converts the error banners on the pull and commit details pages to the new Alert component for consistency across the app.
Closes https://github.com/codecov/engineering-team/issues/1715
Before: 
After:
> ref: Convert pull/commit details page error banners to Alert component

- src/services/repo/useRepoRateLimitStatus.tsx
- src/services/user/useOwnerRateLimitStatus.tsx
In API this param is nullable now if it errors out, we want to make the same update on the zod schema
> fix: Make isGithubRateLimited param nullable

- package.json
- src/layouts/Header/components/HelpDropdown/HelpDropdown.spec.tsx
- src/layouts/Header/components/HelpDropdown/HelpDropdown.tsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.spec.jsx
- src/pages/TermsOfService/TermsOfService.spec.tsx
- src/pages/TermsOfService/TermsOfService.tsx
- src/sentry.ts
- yarn.lock
Adjusts the Sentry user feedback integration such that the widget only loads on the user onboarding pages (TermsOfService and DefaultOrgSelector). Also Refactors the existing HelpDropdown instantiation of the feedback integration to be contained in sentry.ts, and makes a minor copy change in the HelpDropdown form.
Closes https://github.com/codecov/engineering-team/issues/2173
Closes https://github.com/codecov/engineering-team/issues/1941
> feat: Adjust Sentry user feedback instances

- docker/Dockerfile
saw that yarn was being installed at v1.22.19, and then later at 4.3.1, this PR aims to get rid of the original npm builder that was just getting overwritten with the second yarn install. I think previously we were using the separate npm builder because downloading and using the packages was taking 2+ minutes where now it takes ~30 seconds
This leads to a timing improvement overall of ~1.5 minutes pre/post (25% faster)
Pre: https://github.com/codecov/gazebo/actions/runs/10255316136/job/28372007061 (6:14)
Post: https://github.com/codecov/gazebo/actions/runs/10275127882/job/28433206745 (4:38)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going …
> dev: remove double yarn install on dockerfile

- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
Fixes an an accidental change I made that broke this link in onboarding. 
Closes https://github.com/codecov/engineering-team/issues/2194
> fix: Revert change to new github respository secret link in onboarding

- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FileExplorer.jsx
- src/ui/FileViewer/ToggleHeader/Title/Title.spec.tsx
- src/ui/FileViewer/ToggleHeader/Title/Title.tsx
Fixes the file explorer top bar sticking in the wrong place:
> fix: File explorer sticky top bar in wrong location

- package.json
- src/services/charts/mocks.js
- yarn.lock
This PR aims to remove the devDependency "faker" which only looked to be used in 1 set of mocks in our whole repo. Those mocks weren't being used anywhere, so this seemed to be a no-brainer.
New faker package is something completely different too -> https://www.npmjs.com/package/@faker-js/faker
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> chore: Remove faker

- README.md
- package.json
- yarn.lock
Package semver needs to be at these versions
`>= 7.5.2`
`>= 6.3.1`
`>= 5.7.2`
The only instance that this was not the case is
├─ @stryker-mutator/jest-runner@npm:5.6.1 [6563e] (via npm:^5.6.1 [6563e])
│  └─ semver@npm:7.3.8 (via npm:~7.3.5)
We don't use stryker anymore and have not for a long time so we can remove it. Updating the readme accordingly.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> chore: Remove stryker and update readme

- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/FailedTestsTab/CodecovCLI/CodecovCLI.tsx
- src/pages/RepoPage/FailedTestsTab/GitHubActions/GitHubActions.tsx
- src/ui/ExpandableSection/ExpandableSection.tsx
Adds a framework selector to the GitHub Actions coverage onboarding page.
Have approved the differences in copy with design.
[Design](https://www.figma.com/design/3zN1Mh6rjYKLxqoUD1XJOI/GH-1920?node-id=1-2&t=A6Hb7zQfZQDlClRE-0)
Closes https://github.com/codecov/engineering-team/issues/1920
> feat: Add framework selector to GitHub Actions coverage onboarding

- src/pages/DefaultOrgSelector/GitHubHelpBanner/GitHubHelpBanner.spec.tsx
- src/pages/DefaultOrgSelector/GitHubHelpBanner/GitHubHelpBanner.tsx
- src/shared/AppInstallModal/AppInstallModal.spec.tsx
- src/shared/AppInstallModal/AppInstallModal.tsx
- src/shared/AppInstallModal/index.ts
- src/shared/GlobalTopBanners/RequestInstallBanner/RequestInstallBanner.tsx
Adds a CTA and modal for sharing an app install link with your GitHub admin to the DefaultOrgSelector. Reusing the modal from the request install banner required refactoring it out to its own component.
[Design](https://www.figma.com/design/LTCG0grVc5O6FpVcqmNTUj/GH-764?node-id=165-300&t=1mD3JJQ1fps8gBE0-0)
Closes https://github.com/codecov/engineering-team/issues/1916
> feat: Add share with admin button to DefaultOrgSelector

- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.spec.js
- src/shared/GlobalTopBanners/BundleFeedbackBanner/BundleFeedbackBanner.spec.tsx
- src/shared/GlobalTopBanners/BundleFeedbackBanner/BundleFeedbackBanner.tsx
- src/shared/GlobalTopBanners/BundleFeedbackBanner/index.ts
- src/shared/GlobalTopBanners/GlobalTopBanners.spec.tsx
- src/shared/GlobalTopBanners/GlobalTopBanners.tsx
- src/shared/GlobalTopBanners/TeamPlanFeedbackBanner/TeamPlanFeedbackBanner.tsx
- src/ui/TopBanner/TopBanner.tsx
Adds bundle analysis feedback survey banner. Also, adjusts GlobalTopBanners to only render at most one banner. Was scratching my head for a bit on how to only show max one banner, but just had to use my whole brain and realize could do with CSS 😄 
[Design](https://www.figma.com/design/7UXH8qTtbsX5Vz0yYYEZVr/GH-1065?node-id=82-52&t=2dzfE0WcH3arnvss-0)
Closes https://github.com/codecov/engineering-team/issues/2030
> feat: Add bundle analysis feedback survey banner

- src/shared/RawFileViewer/RawFileViewer.spec.tsx
- src/ui/VirtualFileRenderer/VirtualFileRenderer.spec.tsx
- src/ui/VirtualFileRenderer/VirtualFileRenderer.tsx
The current scroll margin isn't being correctly set, so this PR updates this, by setting the correct scroll margin in our once off `useEffect` that will set the correct height. This PR also includes some small tidying up things to get everything playing nicely and "properly".
- Set the correct scroll margin in the new renderer
- Tidy some things up moving to `useEffect` from `useLayoutEffect`
> fix: Set correct scroll margin in new file renderer

- src/pages/AccountSettings/tabs/OktaAccess/OktaConfigForm/OktaConfigForm.tsx
According to https://react-hook-form.com/docs/useform/formstate:
> // ❌ formState.isValid is accessed conditionally, 
> // so the Proxy does not subscribe to changes of that state
> return <button disabled={!formState.isDirty || !formState.isValid} />;
>   
> // ✅ read all formState values to subscribe to changes
> const { isDirty, isValid } = formState;
> return <button disabled={!isDirty || !isValid} />;
This is fixing the following issue:
https://github.com/user-attachments/assets/1c2b366b-1465-47c0-8cf3-d9647256f3c5
Now its:
https://github.com/user-attachments/assets/06ed06c4-69b8-4822-8a8e-bb54df8da1ba
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result …
> fix: Destruct isDirty directly from formstate object

- src/config.js
- src/sentry.ts
- src/shared/RawFileViewer/RawFileViewer.spec.tsx
- src/ui/CodeRenderer/CodeRenderer.spec.tsx
- src/ui/CodeRenderer/CodeRenderer.tsx
- src/ui/VirtualFileRenderer/VirtualFileRenderer.spec.tsx
- src/ui/VirtualFileRenderer/VirtualFileRenderer.tsx
This PR adds in Sentry's browser profiling integration, as well as HOC profilers for the old and new code renderers. I'll eventually remove the HOC profilers this is to track some data as we transition from the old to new code renderer, whereas the browser profiler integration will continue to hang around. We'll set the profiling collection rate at 10%, which is a percentage of our trace collection rate, so we don't get flooded with profiles, we can always increase this value if we choose to do so.
- Add Sentry browser profiling
- Add HOC profiler to `CodeRenderer` and `VirtualFileRenderer`
> feat: Add Sentry Profiler and profiling for code renderers

- src/ui/VirtualFileRenderer/VirtualFileRenderer.spec.tsx
- src/ui/VirtualFileRenderer/VirtualFileRenderer.tsx
Fixes line coverage being off by one in the new VirtualFileRenderer.
> fix: Line coverage off by one in VirtualFileRenderer

- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/NuxtOnboarding/NuxtOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/NuxtOnboarding/NuxtOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/NuxtOnboarding/index.ts
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RemixOnboarding/RemixOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RemixOnboarding/RemixOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RemixOnboarding/index.ts
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/SolidStartOnboarding/SolidStartOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/SolidStartOnboarding/SolidStartOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/SolidStartOnboarding/index.ts
- src/pages/RepoPage/BundlesTab/BundleOnboarding/SvelteKitOnboarding/SvelteKitOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/SvelteKitOnboarding/SvelteKitOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/SvelteKitOnboarding/index.ts
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/ViteOnboarding/ViteOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/WebpackOnboarding/WebpackOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/metricHelpers.ts
- src/pages/RepoPage/RepoPage.tsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
Closes all at https://github.com/codecov/engineering-team/issues/2174
Added routes for all 4 new meta-frameworks and buttons to switch in onboarding
> feat: Add new meta-framework onboarding doc tabs

- src/pages/AccountSettings/AccountSettings.jsx
- src/pages/AccountSettings/AccountSettings.spec.jsx
- src/pages/AccountSettings/AccountSettingsSideMenu.jsx
- src/pages/AccountSettings/AccountSettingsSideMenu.spec.jsx
- src/shared/GlobalTopBanners/OktaBanners/OktaBanners.spec.tsx
- src/shared/GlobalTopBanners/OktaBanners/OktaBanners.tsx
Removing feature flag as it's fully released now.
> fix: Clean up okta feature flag

- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.spec.jsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverageTabs/CommitCoverageTabs.spec.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTab.spec.tsx
- src/pages/CommitDetailPage/Header/Header.spec.tsx
- src/pages/PullRequestPage/Header/Header.spec.tsx
- src/pages/PullRequestPage/PullCoverage/Summary/Summary.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FileExplorer/FileExplorer.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChangedTab.spec.tsx
- src/pages/RepoPage/CommitsTab/CommitsTab.spec.jsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/Tokens/TokensTeam/TokensTeam.spec.js
- src/pages/RepoPage/CoverageTab/ComponentsTab/ComponentsTab.spec.tsx
- src/pages/RepoPage/CoverageTab/ComponentsTab/ComponentsTab.tsx
- src/pages/RepoPage/CoverageTab/CoverageTab.spec.tsx
- src/pages/RepoPage/CoverageTab/FlagsTab/FlagsTab.jsx
- src/pages/RepoPage/CoverageTab/FlagsTab/FlagsTab.spec.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/OverviewTab.spec.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FlagMultiSelect.spec.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Fileviewer/Fileviewer.spec.jsx
- src/services/repo/useRepoSettingsTeam.spec.tsx
- src/services/repo/useRepoSettingsTeam.tsx
We show `enable  anayltics` button for non logged in users, this fixes so that if current user is not part of org, we don't show the enabled button.
issue: https://github.com/codecov/feedback/issues/452
- Update to reflect is current user part of the org 
- Fix tests 
> fix: Show enable button in components/flags for activated users only

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/NewRepoTab.tsx
- src/services/codecovEventMetrics/useStoreCodecovEventMetric.spec.tsx
- src/services/codecovEventMetrics/useStoreCodecovEventMetric.tsx
This closes https://github.com/orgs/codecov/projects/31/views/11?pane=issue&itemId=68552864.
We already have some validation server side. This PR adds some TS checking so that we can receive type safe messaging earlier.
> Add type checking for codecov metrics

- src/ui/MultiSelect/MultiSelect.jsx
- src/ui/Select/Select.jsx
Some z-index values were off, this is a quick fix to the `Select` and `MultiSelect` components.
Closes codecov/engineering-team#2344
- Adjust z-index values
> fix: z-index issues on pulls and commits

- src/pages/LoginPage/LoginButton.jsx
- src/pages/SyncProviderPage/SyncButton.tsx
- src/ui/Button/Button.jsx
- src/ui/ContextSwitcher/ContextSwitcher.jsx
- src/ui/Dropdown/Dropdown.tsx
- src/ui/Select/Select.jsx
This PR aims to quick fix the hover styling on the selectors
This style is also used for the hover on regenerate button, but its a tradeoff I think we're willing to make for now
https://github.com/user-attachments/assets/e708f47a-91d0-417f-b873-6eb75b5ecf00
> fix: hover styles for dark mode on selectors

- package.json
- yarn.lock
We're a couple versions behind, this will bring us up to date.
> chore: Bump Codecov plugin to latest beta

- src/App.spec.tsx
- src/pages/RepoPage/RepoPage.spec.tsx
- src/pages/RepoPage/RepoPage.tsx
- src/pages/RepoPage/hooks/useJSorTSPendoTracking.spec.tsx
- src/pages/RepoPage/hooks/useJSorTSPendoTracking.ts
- src/services/repo/useRepoOverview.tsx
- src/services/tracking/pendo.js
- src/services/tracking/pendo.spec.js
This PR adds in a new `updateOptions` call to Pendo when users navigate to the repo page, and the given repo has JS or TS present. It will only update the options once, and will only run again once the owner value has changed.
Closes codecov/engineering-team#2451
- Fix equality check between two objects in current Pendo tracking, this should reduce the amount of times we're calling Pendo, as we're now checking the diff between the owner ids instead of object references
- Add in new hook to trigger `pendo.updateOptions` when JS or TS is present for a given repo
> feat: Fire Pendo event on RepoPage for JS and TS users

- src/pages/CommitDetailPage/CommitDetailPage.tsx
- src/pages/CommitDetailPage/Header/HeaderDefault/HeaderDefault.jsx
- src/pages/PullRequestPage/PullRequestPage.tsx
Some gaps were removed, removing the padding from the PR and Commit pages, this PR adds them back in.
Before:
After:
> fix: Add gaps back in

- src/services/account/useAccountDetails.ts
This PR aims to fix an issue where a user was receiving a 404 error due to zod schema failing to parse scheduledPhase being a null value.
> fix: Add nullable to scheduled phase

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PlanTypeOptions/PlanTypeOptions.spec.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PlanTypeOptions/PlanTypeOptions.tsx
This PR updates the plan option buttons to set the URL plan param when selecting plan option, previously this was not being done, and we were using it to determine the state of the button.
- Set plan param when selecting plan option
- Update tests
Before:
https://github.com/user-attachments/assets/d624a352-770c-41dd-9ac5-4052079f8eb9
After:
https://github.com/user-attachments/assets/23c2d706-dcdb-4e5a-80cc-19d58c4dde9b
> fix: Plan option not updating when plan param is set

- src/App.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSelection/BranchSelector.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSelection/BundleSelector.tsx
- src/pages/RepoPage/CommitsTab/CommitsTab.jsx
- src/pages/RepoPage/CoverageTab/ComponentsTab/Header/BranchSelector/BranchSelector.tsx
- src/pages/RepoPage/CoverageTab/CoverageTab.tsx
- src/pages/RepoPage/CoverageTab/CoverageTabNavigator.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsTable/BranchSelector/BranchSelector.tsx
- src/pages/RepoPage/RepoPage.tsx
- src/pages/RepoPage/RepoPageTabs.spec.tsx
- src/pages/RepoPage/RepoPageTabs.tsx
- src/services/navigation/useNavLinks/index.js
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
Closes https://github.com/codecov/engineering-team/issues/2188
Part 2/2 of https://www.notion.so/sentry/Branch-Selector-Mismatch-Experience-292469a7e517485b80eaf31f3f7d06d8
In order to share the link across page loads, I've tacked on the selected branch to the most of the Repo Page Tabs:
- Coverage
- Overview
- Flags
- Components
- Bundles
- Tests
- Commits
I've excluded Pulls and Configurations as they don't really pertain to having a branch selected. If a user navigates to either of those with a selected branch, it will be wiped away and the user will need to manually switch away from the default branch when they go back to a tab that allows branch selection.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, …
> Persist Selected Branch Across Tabs/Pages

- src/pages/RepoPage/CoverageTab/FlagsTab/FlagsTab.jsx
- src/pages/RepoPage/RepoPage.tsx
Fixing a bug I just introduced with https://github.com/codecov/gazebo/pull/3181
The Flags table wasn't showing on Flags Tab for a url that includes a selected branch
With branch (wrong):
Without branch (normal):
> fix: Continue to show FlagsTable for flag tab with selected branch

- src/pages/RepoPage/CoverageTab/OverviewTab/hooks/useRepoCoverageTimeseries.js
Small fix to the `useRepoCoverageTimeseries` hook as it's using the incorrect field, causing it to not re-run when a user selects a different trend. 🤦
> fix: useRepoCoverageTimeseries using wrong field 

- src/old_ui/Message/Message.jsx
Just a short term fix for the dark mode colors that I saw while testing out some stripe stuff
Long term we want to remove these altogether for the new Alert component so this is just a stop gap until we have bandwidth for that
I just copied over the colors from Alert.tsx to this file and confirmed it looked alright in UI. Pictures below
**BEFORE**
**AFTER**
**OTHERS UPDATED**
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that …
> fix: Dark mode colors on Message component

- src/shared/utils/commit.ts
as title
- issue https://github.com/codecov/engineering-team/issues/1520
- worker PR https://github.com/codecov/worker/pull/703
- API PR https://github.com/codecov/codecov-api/pull/820
https://github.com/codecov/gazebo/tree/main/src/pages/CommitDetailPage/CommitCoverage/UploadsCard/RenderError.tsx appears to be where we would reference these codes to decide what to display in the UI. i am not going to touch that, but i'll let folks know when i add new codes so appropriate text can be worked out
i fixed some plumbing around error handling in upload processing. everything that used to be "unknown" will still be "unknown" for now but now there's a catchall for any exceptions we have not already assigned an error code. we can watch logs for exceptions we have not already made an error code …
> add new UploadErrorEnum values

- .eslintrc.json
- README.md
- src/pages/RepoPage/CoverageTab/ComponentsTab/subroute/ComponentsTable/ComponentsTable.tsx
- src/pages/RepoPage/CoverageTab/FlagsTab/subroute/FlagsTable/FlagsTable.tsx
- src/ui/Dropdown/Dropdown.tsx
We had disabled some of these rules a while ago, and everything has been going on smoothly ever since, so we might as well get rid of them once and for all. As well we're getting rid of the nested callback lint rule, as it was being used in the same way as the others and really only hinders development over providing any really meaningful value.
> chore: Remove old lint rules

- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/CancelButton/CancelButton.jsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/CancelButton/hooks.js
- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/CancelButton/useBarecancel.js
- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/CancelButton/useBarecancel.spec.js
- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/CancelButton/utils.js
**PROBLEM**
- Users with adblock on weren't able to cancel their Codecov subscriptions.
- This was due to the script being correctly "injected" into the DOM, but that being the "guard" for us to signal that "baremetrics was blocked," which is actually incorrect
- Maybe that worked previously where adblockers were preventing scripts from loading altogether; but now I guess it does inject scripts but just blocks them from executing.
Today I learned that scripts have .onload() and .onerror() handlers that allow you to throw errors if they aren't injected properly into the DOM!
Previously we were relying on doing all of that on "our own" in a bit of a hacky way; and it turns out just relying on those aspects and removing the unneeded code was all we needed to get baremetrics to work with and …
> fix: Users unable to cancel when have adblock

- package.json
- vite.config.mjs
- yarn.lock
This PR adds in the Codecov Vite plugin and Sentry Vite plugin, to upload bundle stats and source maps respectively. 
Issue: codecov/engineering-team#2125
- Add in Codecov Vite plugin
- Add in Sentry Vite plugin
- Configure plugins conditionally in Vite config
> chore: Add and configure Vite plugins

- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/DowngradePlan.jsx
idk why but just saw this file didn't save the additional "l"
Component prop here:
https://github.com/codecov/gazebo/blob/1f8f9153c19c8c5802f17a9abb43c2f29dffa5c8/src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/DowngradePlan/CancelButton/CancelButton.jsx#L16
> fix: missing l on cancellation

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.spec.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
Updating avg to last duration, adding new flake rate + tooltip. 
Updating styles and support dark mode in the tooltip used in metrics section.
issues: [[Gazebo] Create flake rate new column](https://github.com/codecov/engineering-team/issues/2428) 
[[Gazebo] Update avg duration to last duration in the table](https://github.com/codecov/engineering-team/issues/2426)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can …
> feat: Creating new tests analytics columns / fix styles 

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.spec.jsx
- src/ui/A/A.jsx
- src/ui/A/A.spec.jsx
- src/ui/CodeRenderer/CodeRendererProgressHeader/CodeRendererProgressHeader.jsx
Aiming to fix: https://codecov.sentry.io/issues/5616514924
Not sure exactly where this sentry issue is coming from, but my hunch is it's from the only place we're calling .match() on something here: https://github.com/codecov/gazebo/blob/7a43fe74ff12c04adefdbb971009a9282e79cc37/src/ui/A/A.jsx#L37-L38
Tracing that function up though, even weirder because we have a guard checking for if href exists here:
https://github.com/codecov/gazebo/blob/7a43fe74ff12c04adefdbb971009a9282e79cc37/src/ui/A/A.jsx#L78-L80
Technically it will resolve to true for _any_ truthy value, such as true, 1, '', etc. In those cases, we also wouldn't be throwing an error saying "can't read properties of undefined" either, but something more like these:
In any case, I don't think this PR "hurts" us. If the URL doesn't …
> fix: Guard when calling match() on undefined

- src/layouts/LoginLayout/LoginLayout.test.tsx
This PR updates the tests of `layouts/LoginLayout` to Vitest
- Update `LoginLayout` to Vitest
> chore: Update layouts/LoginLayout to Vitest

- .eslintrc.json
- package.json
- src/layouts/BaseLayout/InstallationHelpBanner/InstallationHelpBanner.test.jsx
- src/layouts/Footer/Footer.test.tsx
- src/old_ui/Message/Message.test.jsx
- src/vitest.setup.ts
- yarn.lock
This PR fixes some linting issues with Vitest, and we no longer have to import `vi` only for JS files.
> chore: Vitest config tweaks

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
This PR aims to fix the styling issue on the flake rate tooltip, and adds the copy and tooltip aspect to the column as well
> fix: Add tooltip and correct styling to flake rate column header

- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.jsx
- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.test.jsx
- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/TokenRequiredModal.spec.tsx
- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/TokenRequiredModal.tsx
- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/TokenlessSection.spec.tsx
- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/TokenlessSection.tsx
- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/index.ts
No api work, tokenless section in global upload token, hidden behind a feature flag. 
- New modal for required token 
- New component for the radio buttons of tokenless 
issue: [[Frontend] Add new toggle switch to org settings page](https://github.com/codecov/engineering-team/issues/2302)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> feat: Tokenless section in global upload token tab

- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/NameColumn/NameColumn.jsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/NameColumn/NameColumn.jsx
This PR updates the name columns for the files changed and indirect changes table so that they grab the URL params and pass them to the pre-fetch hook.
- Update `NameColumn` to grab params and pass them
> fix: URL params not being passed to pull prefetching hooks

- src/ui/VirtualFileRenderer/VirtualFileRenderer.tsx
This PR includes some small tweaks to the `VirtualFileRenderer` fixing some issues with the line number column.
- Adjust line height values to match text area and tokens
- Remove bolding when clicking
- Adjust padding values so large numbers align properly when icons are present
Before:
After:
> fix: Small tweaks to line number column on VirtualFileRenderer

- package.json
For whatever reason starting yesterday, my vite dev server was not getting detected by umbrella hat's codecov-gateway. A port scan on localhost revealed no port 3000. Not sure how vite is accepting connections from browser, but clearly by some magic lol. Adding the `--host` flag properly exposes the port to localhost, making the devserver visible to the gateway container.
> fix: Add host flag to vite start script

- package.json
- src/ui/Checkbox/CheckboxNew.stories.tsx
- src/ui/Checkbox/CheckboxNew.test.tsx
- src/ui/Checkbox/CheckboxNew.tsx
- yarn.lock
Adds a new checkbox component in the new style. Will replace the old one in a future PR.
Also updates the storybook script to generate webpack icons.
Closes https://github.com/codecov/engineering-team/issues/524
Based on [designs](https://www.figma.com/design/JOS1ZW499rfWP9nT7ivjf8/Pavilion%3A-Codecov-Design-System-Library?node-id=4318-2499&node-type=frame&t=RWzqyrrd6q4E0hlg-0)
Implemented only necessary features for now, can extend as needed in the future.
Looks like this:
> feat: Add new checkbox component

- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/Upload.jsx
Noticed this while reviewing another PR.
Top one is with the fix applied, bottom is current.
> fix: Spacing on upload

- package.json
- yarn.lock
This PR just bumps up the sentry/react sdk version to latest on gazebo
From slack thread: 
> chore: Update sentry version

- package.json
- yarn.lock
Bump vite version to resolve vulnerability for [#800](https://github.com/codecov/internal-issues/issues/800) and [#801](https://github.com/codecov/internal-issues/issues/801)
After https://github.com/codecov/gazebo/pull/3331 , I noticed that the dependabot alerts for these ([here](https://github.com/codecov/gazebo/security/dependabot/97) and [here](https://github.com/codecov/gazebo/security/dependabot/99)) were not closing and it seemed to be because I needed to pin/bump the indirect dependencies specifically (they don't get done with the direct dependency)
> chore: Resolve vulnerability vite

- package.json
- yarn.lock
Resolve vulnerabilities related to express and path-to-regexp.
Closes:
`path-to-regexp`
https://github.com/codecov/internal-issues/issues/791
https://github.com/codecov/internal-issues/issues/790
https://github.com/codecov/internal-issues/issues/789
`express`
https://github.com/codecov/internal-issues/issues/788
https://github.com/codecov/internal-issues/issues/787
https://github.com/codecov/internal-issues/issues/786
Tested by spot-check confirming no regressions in the preview deploy pages
----------------------------------------
Here are the dependency chains
`path-to-regexp`
BEFORE
```
yarn why path-to-regexp
├─ express@npm:4.19.2
│  └─ path-to-regexp@npm:0.1.7 (via npm:0.1.7)
│
├─ msw@npm:1.3.3
│  └─ path-to-regexp@npm:6.2.2 (via npm:^6.2.0)
│
├─ msw@npm:2.4.8
│  └─ …
```
> chore: Resolve vulnerabilities - express, path-to-regexp

- .gitignore
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.jsx
This closes https://github.com/codecov/engineering-team/issues/2499. 
Before
After
> [fix] Relocate the upload widget to the bottom on small screens

- src/ui/VirtualFileRenderer/ColorBar.test.tsx
- src/ui/VirtualFileRenderer/ColorBar.tsx
- src/ui/VirtualFileRenderer/LineNumber.tsx
- src/ui/VirtualFileRenderer/VirtualDiffRenderer.test.tsx
- src/ui/VirtualFileRenderer/VirtualDiffRenderer.tsx
- src/ui/VirtualFileRenderer/VirtualFileRenderer.tsx
- src/ui/VirtualFileRenderer/constants.ts
- src/ui/VirtualFileRenderer/index.ts
- src/ui/VirtualFileRenderer/types.ts
This PR is the first in a handful for creating a diff renderer based off of the newer virtual file renderer.
Gonna do some further tidying up in a future PR.
- Create shared types, and consts
- Move line number component into it's own file `LineNumber`
- Create new `VirtualDiffRenderer`
- Update `VirtualFileRenderer` to use `LineNumber` component
https://github.com/user-attachments/assets/b9cba1fa-ea42-4ca5-9fd9-7ad98289b572
> feat: Create new VirtualDiffRenderer

- vite.config.mjs
In our CRACO `index.html` we determine if we add Pendo off of the set `REACT_APP_ENV`, however that's not how we currently do it in the Vite config, so this PR quickly updates that to follow that pattern.
```
// public/index.html
<% if(process.env.REACT_APP_ENV === "production") { %>
```
> fix: Change how we set isProduction in Vite config

- index.html
- vite.config.mjs
Two small changes:
- `index.html` this is how you correctly "replace" a value with this plugin
- Removing the override of the base, this was causing cors issues because it was trying to request things from the wrong URL
> fix: Small issues in the Vite config, and index.html

- README.md
- package.json
- src/mocks/browser.js
- src/mocks/handlers.js
- src/pages/AccountSettings/shared/Header/Header.test.tsx
- src/pages/AnalyticsPage/AnalyticsPage.test.jsx
- src/pages/AnalyticsPage/Tabs/Tabs.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/UploadsCard.test.tsx
- yarn.lock
This PR cleans up the remainder of things using MSW V1, once merged I'll make a follow up PR removing the `msw2` alias throughout the app.
> chore: Cleanup remaining MSW V1 things

- index.html
Basically we're seeing a lot of failing to load assets in Sentry, this is because of the way our infra is setup, and old versions of the app are not there for the user to request. This is how Vite recommends resolving the issue: [load-error-handling](https://vite.dev/guide/build#load-error-handling).
This PR adds this script into the `index.html` so it is unaffected by new deployments as the index.html is the file that is consistently served and not cached in the same manner.
> fix: Add script in the index.html if unable to dynamically load asset

- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/RenderError.tsx
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/UploadItem.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/UploadItem.tsx
Adds upload error when multiple flags are specified on an upload.
Closes https://github.com/codecov/engineering-team/issues/201
> feat: Add multiple flags error message to upload items

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.test.jsx
Adds seat usage banners for new multi org accounts using the useEnterpriseAccountDetails hook.
[Design](https://www.figma.com/design/Tytz3vo8mjlyAL8qSiXw3S/GH-1533?node-id=1-2&node-type=canvas&t=Ps6A4FQa6wLfdkve-0)
Closes https://github.com/codecov/engineering-team/issues/2561
> Add Account usage banners to plan page

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestResultsAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestsResultsAggregates.test.tsx
- src/services/repo/useRepoOverview.tsx
This PR aims to glue the hook created in https://github.com/codecov/gazebo/pull/3368 with the metrics section for many of the testResultsAggregates and their respective dynamic values.
We also create a new "PercentBadge" component which will dynamically show + or - and the appropriate color depending on the percentChange that comes back from API. If there's no percent change, which there won't be for the first 30ish days anyway, we won't have any badge populated.
What's not covered here is a "pretty format" of any of the times
Closes https://github.com/codecov/engineering-team/issues/2656
**Some test code**
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result …
> feat: Link hook to metrics section, make percent badge dynamic

- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.test.jsx
This PR updates the diff viewer on the commit detail page indirect changes tab, to use the new virtual diff viewer.
- Update `CommitFileDiff` to conditionally use new diff renderer
- Update tests
> chore: Update commit page indirect changes to use new diff viewer

- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.test.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.test.jsx
- src/shared/RawFileViewer/RawFileViewer.test.tsx
- src/shared/RawFileViewer/RawFileViewer.tsx
As a temporary fix to https://github.com/codecov/internal-issues/issues/708 and https://github.com/codecov/engineering-team/issues/2580, we will add a redirect to login to remind users to login. 
A follow up will include investigating a more reliable way to refresh Github OAuth tokens so this error auto-corrects itself. 
BEFORE
AFTER
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> Add login link to error message in fileviewer

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
This PR glues in the pass fail and skip counts from the test results query to the tooltip shown when you hover the flake rate field.
A minor refactor had to be done when generating the test results "values" to show on the table because multiple values from the query are being populated onto a single column.
I basically just moved over that component logic to the column and had the column render the value itself instead of having it on the column.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to …
> feat: Glue in pass/fail/skip params into tooltip via test results query

- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/ui/ExpandableSection/ExpandableSection.tsx
Small fix with some spacing issues, fixing an apostrophe, and rotating the default chevron for the expandable section to be down not up (requested by @aj-codecov)
Before:
After:
> fix: Small spacing issue on coverage onboarding

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/index.ts
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/useFlakeAggregates.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/useFlakeAggregates.tsx
Needed for the plan based hook
> feat: New flake aggregates hook 

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestResultsAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestsResultsAggregates.test.tsx
Don't show flake related components if the repo is private and plan is either team or free.
- Added required fields to the queries 
- Updated logic to hide flake related components if the repo is private and plan is either team or free
- Update tests
> feat: Plan specific details, flake rate related stuff

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/hooks/useInfiniteAccountOrganizations.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/hooks/useInfiniteAccountOrganizations.ts
Implements useInfiniteAccountOrganizations hook to be used in next step of multiple orgs ui: the org list.
Closes https://github.com/codecov/engineering-team/issues/2563
> feat: Add useInfiniteAccountOrganizations hook

- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.test.jsx
- src/services/comparison/useComparisonForCommitAndParent/useComparisonForCommitAndParent.tsx
This PR updates the commit detail page files changed commit diff viewer to conditionally use the new virtual diff renderer.
- Add `nullable` to `impactedFile` in `useComparisonForCommitAndParent` as it was missing
- Setup `CommitFileDiff` to conditionally render old viewer vs new viewer based off of a feature flag
- Update tests
> chore: Add new diff viewer to commit files changed

- src/ui/VirtualRenderers/VirtualDiffRenderer.tsx
Quick fix adjusting how we get the coverage value for the diff viewer
> fix: New diff renderer coverage off by one

- package.json
- vite.config.mjs
- yarn.lock
This PR adds in a package that provides the sourcemaps for React, since they're not included by default. This should hopefully help when we look into Sentry at errors that are being thrown by React.
> chore: Add react source maps to our builds

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/shared/utils/dates.js
- src/shared/utils/dates.test.js
We need it based on days/hours/minutes/seconds.
- New function for date
- Fixed descriptions 
> fix: Format date for durations in TA

- package.json
- src/vitest.setup.ts
- yarn.lock
Nothing was broken here per se, but the tests using this were logging an error because the old version uses an outdated API.
> chore: Update react-intersection-observer

- package.json
- vite.config.mjs
- yarn.lock
Couple of Vite config changes here and a plugin version bump. Goal of this is to resolve some issues with caching, browsers not supporting `Promise.allSettled`, and bumping a plugin version so it works properly with the extended hash values.
Will hopefully resolve: https://codecov.sentry.io/issues/5968807574/events/3a931390316b4d78a3de37186f8306d1/
- Polyfill `Promise.allSettled`
- Update Codecov Vite plugin
- Adjust output file names
> fix: Move from commit SHA to 22 char hash and polyfill Promise.allSettled

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsPage.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/useFlakeAggregates.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestsResultsAggregates.test.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.test.jsx
This PR adds a couple polish items to the failed tests table:
- Hide flake rate column when not on default branch
- Adds link for 60 day retention and UT
- Updates MSW stuff from msw2 -> msw
Showing link on bottom of image
Showing no flake rate on non-default branch:
> feat: Minor Polish for Failed Tests Table

- package.json
- src/index.tsx
- yarn.lock
This PR adds in TS Query V5 as a new dependency and adds in the new query client and provider to the app so the transition to V5 can happen smoothly.
Issue: codecov/engineering-team#2128
- Add TS Query Dep
- Add client and provider to app
> feat: Add TS Query v5 to Gazebo

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
Just a quick type fix for this param
> fix: Type fix for Total Count

- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/Tokens/RepoUploadToken/RepoUploadToken.jsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/Tokens/RepoUploadToken/RepoUploadToken.test.jsx
- src/services/uploadTokenRequired/useUploadTokenRequired.tsx
`isAdmin` is nullable sooo updating the schema accordingly. (also a fix for an incorrect apostrophe)
> fix: Invalid Schema for useUploadTokenRequired

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/AccountOrgs/AccountOrgs.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/AccountOrgs/AccountOrgs.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/hooks/useInfiniteAccountOrganizations.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/hooks/useInfiniteAccountOrganizations.ts
Adds the last piece of this feature: the organization list! 
During development we ran into some issues with the API and not having proper access, but that has been fixed over there pending my PR getting merged.
(Minor design changes have been okayed with design folks)
[Design](https://www.figma.com/design/Tytz3vo8mjlyAL8qSiXw3S/GH-1533?node-id=1-2&node-type=canvas&t=CjY1XPbsQTDbfMSl-0)
Closes https://github.com/codecov/engineering-team/issues/2564
> feat: Add org list for multi org setups on plan page

- src/ui/Tooltip/Tooltip.tsx
Sets default colors on the Tooltip component as expected.
Closes https://github.com/codecov/engineering-team/issues/2701
> fix: Incorrect default colors on Tooltip

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsFlags/useTestResultsFlags.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsFlags/useTestResultsFlags.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsTestSuites/useTestResultsTestSuites.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsTestSuites/useTestResultsTestSuites.tsx
This PR adds two new hooks:
- useTestResultsFlags
- useTestResultsTestSuites
These hooks are meant to drive two of the selectors on the Failed Tests Table Page. They haven't been linked up yet, this PR simply queries the values from API from here: https://github.com/codecov/codecov-api/blob/e14d14dc04de9027b345b0c4b9c1a4dde73044c2/graphql_api/types/test_analytics/test_analytics.graphql#L20-L24
The files are nearly identical, the only difference is one hook is fetching testSuites and the other is fetching Flags. They both have the ability to filter on "term" which is an attribute being passed into the hook
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result …
> feat: Add new Hooks for fetching testSuites and flags on Failed Tests Page

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.tsx
This PR links the two hooks created in https://github.com/codecov/gazebo/pull/3419 to the failedTestsTable via the SelectorSection component.
Luckily we've already done most of the heavy lifting with linking the filters to the hook so this PR simply calls the hooks and inputs their items to the multiSelect components, and then sets their current values to the states we already have on the component
Closes https://github.com/codecov/engineering-team/issues/2670 and https://github.com/codecov/engineering-team/issues/2671
https://github.com/user-attachments/assets/ae16d16c-82c9-426b-8018-3b81e4dfd7f5
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is …
> feat: Link Flags/Test Suites hooks to Failed Tests Table Selectors

- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTab.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTab.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTableTeam/FilesChangedTableTeam.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/IndirectChangesTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FilesChangedTable/FilesChangedTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/TableTeam/TableTeam.tsx
- src/services/commit/useCommit.test.tsx
- src/services/commit/useCommit.tsx
- src/services/commit/useCommitTeam.test.tsx
- src/services/commit/useCommitTeam.tsx
- src/services/commit/useCompareTotals.test.tsx
- src/services/commit/useCompareTotals.tsx
- src/services/commit/useCompareTotalsTeam.test.tsx
- src/services/commit/useCompareTotalsTeam.tsx
- src/services/pull/usePull.test.tsx
- src/services/pull/usePull.tsx
- src/services/pull/usePullCompareTotalsTeam.test.tsx
- src/services/pull/usePullCompareTotalsTeam.tsx
- src/services/pull/usePullTeam.test.tsx
- src/services/pull/usePullTeam.tsx
This PR fixes some zod schema issues where a field was being marked as non-nullable, however it is in fact nullable. This was most likely the root cause for: #3371. I've gone through and updated all instances of this `results` field to be nullable, and all the places where it's used. This should resolve the issue raised in #3371, so i've gone ahead and removed that error boundary so we start collecting these network errors up in the `NetworkErrorBoundary` again.
- Update zod schemas in hooks calling `impactedFiles.results` from the API to be nullable
- Update code using this field to handle if it is `null`
- Update `CoverageObjSchema` in `useCompareTotals` to be `coverage` not `percentCovered`
- Remove error boundary from `FilesChangedTab`
> fix: Results array for impacted files is nullable

- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Sunburst/Sunburst.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Sunburst/Sunburst.test.jsx
Fix bug with sunburst's breadcrumbs show a "..." if too long. It always display just the last element with "..." if it goes more than 1 deep as it seemed like in most cases only 1 fits on the page. This is a quick and dirty solution. For real we should probably give more real estate for this rich information or make a truncatable Breadcrumbs reusable component that has a resize observer.
Closes https://github.com/codecov/engineering-team/issues/2337
Example screenshots:
here are the befores which just need a bandaid:
> fix: Truncate sunburst chart's breadcrumbs

- src/pages/CommitDetailPage/CommitCoverage/routes/CommitDetailFileViewer/CommitDetailFileViewer.test.jsx
- src/pages/PullRequestPage/PullCoverage/routes/FileViewer/FileViewer.test.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Fileviewer/Fileviewer.test.jsx
- src/shared/RawFileViewer/RawFileViewer.test.tsx
- src/shared/RawFileViewer/RawFileViewer.tsx
This PR removes the old code renderer, in favour of the new virtual file renderer. This PR also includes some feature flag cleanup, and adding mocks to tests.
> chore: Remove old single file renderer

- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.test.jsx
- src/pages/CommitDetailPage/CommitCoverage/ErroredUploads/ErroredUploads.jsx
- src/pages/CommitDetailPage/CommitCoverage/ErroredUploads/ErroredUploads.test.jsx
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/UploadsCard.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/UploadsCard.tsx
- src/pages/CommitDetailPage/Dropdowns/CommitCoverageDropdown.tsx
Closes https://github.com/codecov/engineering-team/issues/2521
Figma: https://www.figma.com/design/4Z7yb2dkIIATkfzpWoMYQq/GH-2220?node-id=1-2
We're addressing point 4 and 5 of the Figma file
Removing old, unhelpful messaging and replacing with this new one. Anytime a commit has an upload error currently, the UI will be forever stuck show our existing messaging
> feat: Change errored uploads and uploads list text

- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.test.jsx
- src/ui/CIStatus/CIStatus.test.jsx
- src/ui/CIStatus/CIStatus.tsx
- src/ui/SummaryDropdown/SummaryDropdown.tsx
Closes https://github.com/codecov/engineering-team/issues/2523
Discussed with Adalene and we decided to do away with the border style to match with the tooltips on their way for TA.
Looked into the reason why we had z-30 in SummaryDropdown and it looks like we don't currently need it.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> feat: Add CI status tooltip

- src/App.test.tsx
- src/pages/RepoPage/FailedTestsTab/FrameworkTabsCard/FrameworkTabs/FrameworkTabs.test.tsx
- src/pages/RepoPage/FailedTestsTab/FrameworkTabsCard/FrameworkTabs/FrameworkTabs.tsx
This PR ships a copy update to the TA onboarding page around adding a new setting specific for Jest TA setups. We now need to include this new env variable when running jest so we can capture the file path and output it correctly
Needed to basically "copy paste" all the clipboard values into a separate value since the copy may be a JSX element now, and when copying a JSX element you get [Object object] which is not what we want. Thanks @spalmurray-codecov for pointing that out!
Closes https://github.com/codecov/engineering-team/issues/2605
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …
> feat: Update Jest TA onboarding copy to include filepath setting

- src/sentry.ts
I had originally ignored this error to silence some issues in Sentry, however myself and my mentor want to take a bit of a deeper dive into this, and see if there is something else afoot causing this.
> rev: Revert ignoring failing to import module in Sentry

- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.jsx
- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.test.jsx
- src/services/bundleAnalysis/useBundleSummary.tsx
- src/services/commit/useCommit.test.tsx
- src/services/commit/useCommit.tsx
- src/shared/api/helpers.test.ts
- src/shared/api/helpers.ts
- src/vitest.setup.ts
This PR changes the way that was recently introduced as to how we capture data fetching service errors, and send them to Sentry to tidy things up a little bit, and reduce what is logged out to the console. 
Use with a data fetching hook:
```tsx
if (!parsedRes.success) {
return rejectNetworkErrorToSentry({
status: 404,
data: {},
dev: 'useCommit - 404 failed to parse',
error: parsedRes.error,
})
}
```
- Create a function that handles, rejects, and sends info to Sentry for service parsing errors
- Update two examples hooks using this new function
> feat: Rework how we capture service errors to sentry

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/TableHeader/TableHeader.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/TableHeader/TableHeader.tsx
This PR aims to add two enhancements to the Failed Tests Page
- When clicking on metric that is already selected in Metric Section, we remove the parameter
- used the existing isSelected prop to default back to '' if clicked again
- When not on default branch, remove the "reset to default" button
- created a const and passed the prop down for isDefaultBranch which was being used in another const above
The rest of the PR is just updating/adding tests
Closes https://github.com/codecov/engineering-team/issues/2775
Closes https://github.com/codecov/engineering-team/issues/2801
https://github.com/user-attachments/assets/6c46e7f6-d40c-405b-8f06-902001538b98
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In …
> feat: Remove Reset button when not on default branch + double click selector to remove param

- src/pages/RepoPage/RepoPageTabs.test.tsx
- src/pages/RepoPage/RepoPageTabs.tsx
Since we're moving Test Analytics out of beta now, we'd like to update the copy on the tab from "Beta" to "New"
Closes https://github.com/codecov/engineering-team/issues/2862
> feat: Change tab copy from Beta to new

- src/ui/VirtualRenderers/VirtualDiffRenderer.tsx
- src/ui/VirtualRenderers/VirtualFileRenderer.tsx
Quick ordering change of the way we import styles into the virtual file renderers
Before:
After:
> fix: Incorrect CSS order in Virtual File Renderers

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/TableHeader/TableHeader.tsx
This PR aims to fix some responsiveness issues that occurred when on some smaller screen sizes on the Test Analytics page.
https://github.com/user-attachments/assets/caa264d1-be0f-4e4b-83e6-1965ad6503a1
> fix: Responsiveness tweaks for TA Selector section

- src/pages/AnalyticsPage/AnalyticsPage.jsx
Quick fix to pass the correct props around.
> fix: New charts not getting the correct props on Analytics Page

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.tsx
This PR aims to pin the default branch (if it exists) to the top of the list of branches on the Branch Selector for the Failed Tests tab.
This is a quality of life fix to make it easy for folks to go back to the "main" view.
Closes https://github.com/codecov/engineering-team/issues/2855
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> feat: Pin default branch to top of branch selector items

- src/pages/RepoPage/DeactivatedRepo/DeactivatedRepo.test.tsx
- src/pages/RepoPage/DeactivatedRepo/DeactivatedRepo.tsx
- src/pages/RepoPage/RepoPage.test.tsx
Fix the deactivated repo message to match the correct one [here](https://github.com/codecov/codecov-api/blob/15f9614dd6ded618c40e7b74a91700980018b2a7/upload/helpers.py#L762).
Closes https://github.com/codecov/engineering-team/issues/2688
NEW
OLD
> fix: Correct the deactivated repo message

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/useFlakeAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestResultsAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsFlags/useTestResultsFlags.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsTestSuites/useTestResultsTestSuites.tsx
This PR follows up on a few comments on the tests-analytics-v2 branch to do the following:
- Use const values instead of strings for TestResultsFilterParameter
- Update the hooks reject errors from Promise.reject to rejectNetworkError
> fix: PR comments for rejectNetworkError and using Const values

- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.test.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
Noticed this was wrong during an investigation this morning - the CLI throws an error if you do not include the org/ part of the repo slug.
> fix: Add org/ to upload command for other ci onboarding

- src/pages/RepoPage/FailedTestsTab/CodecovCLI/CodecovCLI.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/useFlakeAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestResultsAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsFlags/useTestResultsFlags.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsTestSuites/useTestResultsTestSuites.tsx
- src/pages/RepoPage/FailedTestsTab/GitHubActions/GitHubActions.test.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.test.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.ts
This PR does a lot of teeny updates and fixes in preparation for the TA launch:
- Nullable on TA and Flake Aggregates objects from zod, in the event those objects don't exist on request
- Adds "error" object to rejectNetworkError call when failing to parse on relevant TA hooks
- Updates the links to say "test-analytics" from "test-result-ingestion-beta" for anyone that hovers them
- Memoizes the branch selection list to prevent some extra overhead on failed tests table re-renders
- Removes unnecessary ?? operator 
- Adds "." to the end of Avg on the failed tests table
https://github.com/user-attachments/assets/5c922300-63b1-4552-af71-89cca8becbcf
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 …
> fix: TA finishing touches and just in case fixes

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
This PR fixes an issue where flake rate was unbounded coming from API, and bounds it to 2 decimals.
**BEFORE**
**AFTER**
> fix: Flake rate to fixed decimals

- package.json
- yarn.lock
Closes https://github.com/codecov/internal-issues/issues/971
Upgraded our own use of the package for
├─ gazebo@workspace:.
│  └─ http-proxy-middleware@npm:2.0.6 [6563e] (via npm:^2.0.6 [6563e])
but adding a resolution as it is also referenced here
gazebo@workspace:.
└─ react-scripts@npm:5.0.1 [6563e] (via npm:^5.0.1 [6563e])
└─ webpack-dev-server@npm:4.15.2 [37b33] (via npm:^4.6.0 [37b33])
└─ http-proxy-middleware@npm:2.0.6 [edb85] (via npm:^2.0.3 [edb85])
We can remove this resolution when we pull out react-scripts as part of Gazebo V2 work tickets.
> chore: Upgrade http-proxy-middleware to ^2.0.7

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
This PR updates the copy on the failed tests tooltip, as well as the failed tests metric section header. No other changes, purely copy updates.
Closes https://github.com/codecov/engineering-team/issues/2887
> fix: Tooltip copy for failed tests

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSelection/BundleSelection.tsx
This PR centers the selectors on the bundles tab to match the new TA format.
**AFTER**
https://github.com/user-attachments/assets/3fe3c56d-9f0f-4ee0-b340-21c65ca01ea7
**BEFORE**
https://github.com/user-attachments/assets/24d9c979-b4d4-4b7b-8384-7e6031e5da67
> feat: center selectors on bundles page

- src/App.test.tsx
I think this is flaking because the mocks aren't being reset properly.
We want to set the var before each, but then clear the query client after each (intuitively that makes sense at least)
> dev: Fix app.tsx flake I think

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
This PR just updates some copy on the cumulative failures tile on the failed tests table. Previously we mentioned that the failures shown were for all branches, but its actually just the default branch
Closes https://github.com/codecov/engineering-team/issues/2942
> fix: Copy update on Cumulative Failure tile

- src/layouts/Header/Header.test.tsx
- src/layouts/Header/Header.tsx
Quick fix to hide this navigator on the sync page.
- Hide navigator in `Header` while on sync page
Before:
After:
> fix: Hide navigator on sync page

- src/pages/RepoPage/ActivationAlert/ActivationAlert.test.tsx
- src/pages/RepoPage/ActivationAlert/ActivationAlert.tsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.test.tsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.tsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/index.ts
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationBanner.test.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationBanner.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.test.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/index.ts
In onboarding page: (Current user is not activated) => Banner
- User has seats left:
-  User is admin, link to members page (access)
-  User is not an admin, contact admin 
- User has reached seats limit, contact sales 
In the coverage page: (Current user is not activated) => Alert 
- User has seats left:
- User is admin, link to members page (access)
- User is not an admin, contact admin 
- User has reached seats limit, contact sales 
Issue: [#554](https://github.com/codecov/feedback/issues/554) 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: …
> feat: Handle self hosted activation statuses  

- src/pages/RepoPage/CoverageTab/FlagsTab/subroute/FlagsTable/FlagsTable.tsx
Just changing links to `link: "text-ds-blue-darker"` to better represent there are clickable.
Closes https://github.com/codecov/engineering-team/issues/2774
> fix: Change flags to anchor style

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
We want to display an empty state message on the main dashboard to explain why no data is visible yet for the first PR.
https://github.com/codecov/engineering-team/issues/2780
> feat: Handle isFirstPullRequest in TA page

- src/shared/GlobalBanners/GitHubRateLimitExceeded/GitHubRateLimitExceededBanner.test.tsx
- src/shared/GlobalBanners/GitHubRateLimitExceeded/GitHubRateLimitExceededBanner.tsx
This PR resolves the following issues:
```
Warning: validateDOMNesting(...): <h2> cannot appear as a child of <h5>.
Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
```
- Remove `h2` and `p` elements
Before:
After:
> fix: HTML Validation issues with GitHub Rate Limit Banner

- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.test.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.tsx
- src/pages/PullRequestPage/PullCoverage/PullCoverage.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverage.test.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/PullCoverageTabs.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/PullCoverageTabs.test.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/hooks/index.ts
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/useTabsCounts.test.tsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/useTabsCounts.ts
- src/pages/PullRequestPage/PullCoverage/routes/FileViewer/FileViewer.jsx
- src/pages/PullRequestPage/PullCoverage/routes/FileViewer/FileViewer.test.jsx
- src/pages/PullRequestPage/PullRequestPage.test.tsx
- src/pages/PullRequestPage/PullRequestPage.tsx
- src/pages/PullRequestPage/hooks/index.ts
- src/pages/PullRequestPage/queries/PullPageDataQueryOpts.test.tsx
- src/pages/PullRequestPage/queries/PullPageDataQueryOpts.tsx
This PR updates `usePullPageData` to `PullPageDataQueryOpts` as part of our migration over to TS Query V5.
Ticket: codecov/engineering-team#2965
- Update `usePullPageData` to `PullPageDataQueryOpts`
- Some tidying up of directories, and getting rid of barrel index files
- Update tests
> chore: Update usePullPageData to TSQ V5

- src/pages/PullRequestPage/Header/HeaderDefault/HeaderDefault.test.tsx
- src/pages/PullRequestPage/Header/HeaderDefault/HeaderDefault.tsx
- src/pages/PullRequestPage/Header/HeaderDefault/hooks/index.ts
- src/pages/PullRequestPage/Header/HeaderDefault/queries/PullHeadDataQueryOpts.test.tsx
- src/pages/PullRequestPage/Header/HeaderDefault/queries/PullHeadDataQueryOpts.tsx
This PR updates the `usePullHeadData` hook over to the query options API version: `PullHeadDataQueryOpts`.
Ticket codecov/engineering-team#2965
- Refactor `usePullHeadData` to `PullHeadDataQueryOpts`
- Update tests
> chore: Migrate usePullHeadData to TS Query V5

- src/pages/PullRequestPage/Header/HeaderTeam/HeaderTeam.test.tsx
- src/pages/PullRequestPage/Header/HeaderTeam/HeaderTeam.tsx
- src/pages/PullRequestPage/Header/HeaderTeam/hooks/index.ts
- src/pages/PullRequestPage/Header/HeaderTeam/queries/PullHeadDataTeamQueryOpts.test.tsx
- src/pages/PullRequestPage/Header/HeaderTeam/queries/PullHeadDataTeamQueryOpts.tsx
This PR updates `usePullHeadDataTeam` to the query options API equivalent `PullHeadDataTeamQueryOpts`, and updates the relevant tests.
Ticket codecov/engineering-team#2965
- Migrate `usePullHeadDataTeam` to `PullHeadDataTeamQueryOpts`
- Update tests
> chore: Migrate usePullHeadDataTeam to TS Query V5

- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.test.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.tsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.jsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.test.jsx
- src/pages/CommitDetailPage/CommitDetailPage.test.tsx
- src/pages/CommitDetailPage/CommitDetailPage.tsx
- src/pages/CommitDetailPage/hooks/index.js
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.tsx
This PR updates the `useCommitPageData` hook to `CommitPageDataQueryOpts` following along with the new style of writing data fetching utils.
Ticket: codecov/engineering-team#2966
- Update `useCommitPageData` to `CommitPageDataQueryOpts`
- Update tests
> chore: Migrate useCommitPageData to TSQ V5

- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FileExplorer.jsx
The current header for the repo page code tree/file list has no bg set so it's transparent, which isn't great. This PR is a small fix to resolve it
- Add BG to file wrapping sticky header 
Before:
After:
> fix: RepoPage table header having no BG

- src/pages/RepoPage/FailedTestsTab/GitHubActions/GitHubActions.tsx
Updates codecov-action to v5 in the TA onboarding example.
> chore: Update action to v5 in TA onboarding

- package.json
- yarn.lock
Adds the Amplitude Browser JS SDK.
Closes https://github.com/codecov/engineering-team/issues/2892
> chore: Add Amplitude browser JS SDK

- src/layouts/Header/components/UserDropdown/UserDropdown.test.tsx
- src/pages/AccountSettings/tabs/Admin/GithubIntegrationSection/GithubIntegrationSection.test.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.test.jsx
- src/pages/DefaultOrgSelector/GitHubHelpBanner/GitHubHelpBanner.test.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.ts
- src/ui/ContextSwitcher/ContextSwitcher.test.jsx
Was testing our the new changes to `GH_APP` and found some tests breaking when I had the config value set locally. This PR fixes those tests.
> fix: Broken tests when custom GH_APP set locally

- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/AssetsTable.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/useBundleAssetsTable.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.test.tsx
- src/services/bundleAnalysis/useBundleAssets.test.tsx
- src/services/bundleAnalysis/useBundleAssets.tsx
This PR updates the `useBundleAssets` hook to also fetch the newly introduced `routes` field on the `BundleAsset` type. This will be used to populate later on in the new column we're going to be adding to the assets table on the bundles tab.
Closes codecov/engineering-team#2956
- Update query and schema with new `routes` field in `useBundleAssets`
- Update tests
> feat: Update useBundleAssets to fetch routes field

- src/pages/CommitDetailPage/Header/HeaderDefault/HeaderDefault.jsx
- src/pages/CommitDetailPage/Header/HeaderDefault/HeaderDefault.test.jsx
- src/pages/CommitDetailPage/Header/HeaderDefault/hooks/index.ts
- src/pages/CommitDetailPage/Header/HeaderDefault/queries/CommitHeaderDataQueryOpts.test.tsx
- src/pages/CommitDetailPage/Header/HeaderDefault/queries/CommitHeaderDataQueryOpts.tsx
This PR migrates the `useCommitHeaderData` over to the query options API to `CommitHeaderDataQueryOpts`
Ticket: codecov/engineering-team#2966
- Migrate `useCommitHeaderData` to `CommitHeaderDataQueryOpts`
- Update tests
> chore: Migrate useCommitHeaderData to TS Query V5

- src/pages/CommitDetailPage/Header/HeaderTeam/HeaderTeam.jsx
- src/pages/CommitDetailPage/Header/HeaderTeam/HeaderTeam.test.jsx
- src/pages/CommitDetailPage/Header/HeaderTeam/hooks/index.ts
- src/pages/CommitDetailPage/Header/HeaderTeam/queries/CommitHeaderDataTeamQueryOpts.test.tsx
- src/pages/CommitDetailPage/Header/HeaderTeam/queries/CommitHeaderDataTeamQueryOpts.tsx
This PR migrates the `useCommitHeaderDataTeam` to the query options API version `CommitHeaderDataTeamQueryOpts`
Ticket: codecov/engineering-team#2966
- Migrate `useCommitHeaderDataTeam` to `CommitHeaderDataTeamQueryOpts`
- Update tests
> chore: Migrate useCommitHeaderDataTeam to TS Query V5

- .git-blame-ignore-revs
Quick PR to add the recently merged lint fix PR to ignore the commit in Git blame so it's easier to see the real previous changes.
> chore: Update Git Blame Ignore file

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/AccountOrgs/AccountOrgs.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/AccountOrgs/AccountOrgs.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/queries/InfiniteAccountOrganizationsQueryOpts.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/queries/InfiniteAccountOrganizationsQueryOpts.ts
This PR migrates the `useInfiniteAccountOrganizations` hook to the TS Query V5 `infiniteQueryOptions` version `InfiniteAccountOrganizationsQueryOpts`
Ticket: codecov/engineering-team#2968
- Migrates `useInfiniteAccountOrganizations` to `InfiniteAccountOrganizationsQueryOpts`
- Update usage in `AccountOrgs`
> chore: Migrate useInfiniteAccountOrganizations to TS Query V5

- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/RenderError.tsx
- src/services/commit/useCommit.tsx
- src/shared/utils/extractUploads.ts
Before we expect flags to always be in the commit object, but that shouldn't be the case as team plan doesn't support flags.
> fix: useCommit doesn't always expect flags

- src/pages/PlanPage/PlanPage.jsx
- src/pages/PlanPage/PlanPage.test.jsx
- src/pages/PlanPage/hooks/index.ts
- src/pages/PlanPage/queries/PlanPageDataQueryOpts.test.tsx
- src/pages/PlanPage/queries/PlanPageDataQueryOpts.ts
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.test.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/PaidPlanCard/PaidPlanCard.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/PaidPlanCard/PaidPlanCard.tsx
This PR migrates the `usePlanPageData` to the TS Query V5 `queryOptions` API version `PlanPageDataQueryOpts`
Ticket: codecov/engineering-team#2968
- Migrates `usePlanPageData` to `PlanPageDataQueryOpts`
- Update usage of `PlanPageDataQueryOpts`
- `PlanPage`
- `FreePlanCard`
- `PaidPlanCard`
> chore: Migrate usePlanPageData to TS Query V5

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/AccountOrgs/AccountOrgs.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/AccountOrgs/AccountOrgs.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/queries/EnterpriseAccountDetailsQueryOpts.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/queries/EnterpriseAccountDetailsQueryOpts.ts
This PR migrates the `useEnterpriseAccountDetails` to the queryOptions API version `EnterpriseAccountDetailsQueryOpts`
Ticket: codecov/engineering-team#2968
- Migrate `useEnterpriseAccountDetails` to `EnterpriseAccountDetailsQueryOpts`
- Update usage in `CurrentOrgPlan` and `AccountOrgs`
- Update tests
> chore: Migrate useEnterpriseAccountDetails to TS Query V5

- src/pages/EnterpriseLandingPage/EnterpriseLandingPage.test.tsx
- src/pages/EnterpriseLandingPage/EnterpriseLandingPage.tsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.tsx
- src/services/config/LoginProvidersQueryOpts.test.tsx
- src/services/config/LoginProvidersQueryOpts.ts
- src/services/config/index.ts
This PR migrates the `useLoginProviders` to the queryOptions API version `LoginProvidersQueryOpts`
Ticket: codecov/engineering-team#2962
- Migrate `useLoginProviders` to  `LoginProvidersQueryOpts`
- Update usage in `EnterpriseLandingPage`
- Update import in `ProviderCard`
> chore: Migrate useLoginProviders to TS Query V5

- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/AssetsTable.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/AssetsTable.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/useBundleAssetsTable.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/useBundleAssetsTable.ts
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.test.tsx
- src/services/bundleAnalysis/BundleAssetsQueryOpts.test.tsx
- src/services/bundleAnalysis/BundleAssetsQueryOpts.tsx
This PR updates the query options for grabbing a list of assets used to display the asset table, so that we can determine if we want to render the new path column in the asset table
Closes codecov/engineering-team#2957
- Grab plugin name in assets table query options
- also updated to be the TSQ V5 style we're moving to
- Update `useBundleAssetsTable`
- Update tests
> feat: Grab the plugin name for the given bundle

- codecov.yml
I've been investigating the static graphs made from `flare`, we'd like to reduce or eliminate them. Do you all find the `tree` graph in the cc pr comment helpful? If not, let's pull it.
The part in the red box is a flare graph.
> remove flare graph from pr comment

- src/pages/MembersPage/MembersActivation/Activation/Activation.jsx
- src/pages/MembersPage/MembersActivation/Activation/Activation.test.jsx
No such thing as a pro team plan, just pro or team lol. This fixes that
> fix: Change Pro Team to Pro

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateBlurb/UpdateBlurb.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateBlurb/UpdateBlurb.tsx
Free Plan has no billing cycle so we shouldn't say "Changing plan from monthly to annual" if the user wants to upgrade to an annual plan.
We just need to add the "isFreePlan" check to this function and rest we get for free.
**BEFORE**
**AFTER**
> fix: Copy when changing plan from free plan

- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.test.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/WorkflowYMLStep.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/types.ts
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.test.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
- src/pages/RepoPage/CoverageOnboarding/OutputCoverageStep/OutputCoverageStep.test.tsx
- src/pages/RepoPage/CoverageOnboarding/OutputCoverageStep/OutputCoverageStep.tsx
- src/pages/RepoPage/CoverageOnboarding/UseFrameworkInstructions.tsx
This PR adds the framework coverage generation step from GHA to circle ci and other ci onboarding. To facilitate this, I pulled the OutputCoverageStep component and the FrameworkInstruction definition out of the GHA directory up a level into the shared onboarding directory and made the necessary changes to GHA onboarding.
Closes https://github.com/codecov/engineering-team/issues/2697
> feat: Add coverage generation step to CircleCI and OtherCI onboarding

- src/shared/ListRepo/ReposTable/ReposTable.test.tsx
- src/shared/ListRepo/ReposTable/ReposTable.tsx
Pins the demo repo to the top of the repo list during sorts. Also hides the demo if two or more repos are configured.
Closes https://github.com/codecov/engineering-team/issues/2827
> fix: Pin demo repo to top during sort

- src/pages/DefaultOrgSelector/DefaultOrgSelector.test.jsx
- src/pages/RepoPage/CommitsTab/CommitsTab.test.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/Summary/Summary.test.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/SummaryTeamPlan/SummaryTeamPlan.test.tsx
- src/ui/FileViewer/ToggleHeader/ToggleHeader.test.tsx
Friday afternoon "chores" had me looking at the Test Analytics tool on Codecov for the Gazebo repo just because I hadn't in a while. I was surprised to see that some tests were taking over 5 seconds to run, with one being an even more abnormal "18 seconds."
**Screenshot of initial test analytics page**
I used the historical selector in the top to narrow my search to the last 7 days to see if it was just a blip of some weird data or if there was actually something abnormal going on here. To my surprise, even at 7 days I was seeing some similarly high test times and had to do a double check locally to see if I could reproduce those exact tests.
**Screenshot of last 7 days data**
Locally, I booted up the Commit.jsx test suite to see if I was also seeing some slow test suite run times since I …
> dev: Clean up some unneccesary mocks to speed up gazebo tests

- package.json
- yarn.lock
Was getting SUPER annoyed with the punycode deprecation warning and wanted to get to the bottom of it.
Turns out it was due to a couple packages that were out of date on jsdom, that are subsequently patched in v25.0.1
[Changelog](https://github.com/jsdom/jsdom/releases)
**BEFORE**
**AFTER**
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice …
> dev: update jsdom to remove punycode warning

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.test.jsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationBanner.tsx
- src/shared/utils/billing.test.ts
- src/shared/utils/billing.ts
isBasicPlan looked to only be used in two places, both related to trials. After talking with @aj-codecov and @adrian-codecov we thought that shifting to all free plans, as long as they haven't trialed before, made sense to us allowing us to remove some extra overhead with logic and just rely on isFreePlan in a few more places.
Luckily because the schemas all stayed the same this PR remained pretty lightweight.
Closes https://github.com/codecov/engineering-team/issues/3002
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, …
> ref: Convert isBasicPlan to isFreePlan GQL property

- src/layouts/Header/components/SeatDetails/SeatDetails.test.tsx
- src/layouts/Header/components/SeatDetails/SeatDetails.tsx
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/ActivationBanner.jsx
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/ActivationBanner.test.jsx
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/useSelfActivationMutation.js
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/useSelfActivationMutation.test.jsx
- src/pages/AccountSettings/tabs/Profile/Profile.test.jsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.test.tsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.test.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.tsx
- src/services/selfHosted/SelfHostedSeatsConfigQueryOpts.test.tsx
- src/services/selfHosted/SelfHostedSeatsConfigQueryOpts.ts
- src/services/selfHosted/index.ts
This PR migrates the `useSelfHostedSeatsConfig` to the TS Query V5 queryOptions version `SelfHostedSeatsConfigQueryOpts`
Ticket: codecov/engineering-team#2961
- Migrate `useSelfHostedSeatsConfig` to `SelfHostedSeatsConfigQueryOpts`
- Update usage in `SeatDetails`, `ActivationBanner`, `ActivationRequiredSelfHosted`, `ActivationRequiredSelfHosted`
- Fix issue in `Profile` tests
> chore: Migrate useSelfHostedSeatsConfig to TS Query V5

- src/shared/GlobalBanners/MissingDesignatedAdmins/MissingDesignatedAdmins.test.jsx
- src/shared/GlobalBanners/MissingDesignatedAdmins/MissingDesignatedAdmins.tsx
This PR aims to resolve this [Sentry issue](https://codecov.sentry.io/issues/6172200302/?project=5514400), which is caused by the `provider` not being defined as there are some cases where the `GlobalBanners` can be rendered when no provider is present.
I've updated the [Gazebo Guidelines](https://www.notion.so/sentry/Writing-Services-TS-Query-V5-1278b10e4b5d8046bb17f57e3b04a3e7?pvs=4#1698b10e4b5d800a8518d25897902a1c) to cover these cases specifically.
- Create small wrapper for `MissingDesignatedAdmins` to conditionally fetch
- Clean up tests removing Query V4 things
> fix: Resolve Sentry issue fetching in MissingDesignatedAdmins Without a Provider

- src/services/selfHosted/SelfHostedSeatsAndLicenseQueryOpts.test.tsx
- src/services/selfHosted/SelfHostedSeatsAndLicenseQueryOpts.ts
- src/services/selfHosted/index.ts
- src/shared/GlobalBanners/SelfHostedLicenseExpiration/SelfHostedLicenseExpiration.test.tsx
- src/shared/GlobalBanners/SelfHostedLicenseExpiration/SelfHostedLicenseExpiration.tsx
This PR migrates the `useSelfHostedSeatsAndLicense` to the TSQ V5 query options version `SelfHostedSeatsAndLicenseQueryOpts`, as well as a TS migration
Ticket: codecov/engineering-team#2961
- Migrate `useSelfHostedSeatsAndLicense` to `SelfHostedSeatsAndLicenseQueryOpts`
- Update `SelfHostedLicenseExpiration`
- Refactor to TS
- Add in tiny wrapper component so that we can short circuit rendering the actual banner and triggering the data fetching, as suspense queries cannot be controlled via an `enabled` property
> chore: Migrate useSelfHostedSeatsAndLicense to TS Query V5

- src/layouts/Header/components/AdminLink/AdminLink.test.tsx
- src/layouts/Header/components/AdminLink/AdminLink.tsx
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/ActivationBanner.jsx
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/useSelfActivationMutation.js
- src/pages/AccountSettings/tabs/Profile/ActivationBanner/useSelfActivationMutation.test.jsx
- src/pages/AccountSettings/tabs/Profile/Profile.jsx
- src/pages/AdminSettings/AdminSettings.jsx
- src/pages/AdminSettings/AdminSettings.test.jsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.test.tsx
- src/pages/RepoPage/ActivationAlert/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.test.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationRequiredSelfHosted/ActivationRequiredSelfHosted.tsx
- src/services/selfHosted/SelfHostedCurrentUserQueryOpts.test.tsx
- src/services/selfHosted/SelfHostedCurrentUserQueryOpts.ts
- src/services/selfHosted/index.ts
This PR migrates the `useSelfHostedCurrentUser` to the TS Query V5 queryOptions API version `SelfHostedCurrentUserQueryOpts`
Ticket: codecov/engineering-team#2961
- Migrate `useSelfHostedCurrentUser` to `SelfHostedCurrentUserQueryOpts`
- Migrate `useSelfActivationMutation` to TS Query V5
- Update usage in `AdminLink`, `Profile`, `ActivationBanner`, `useSelfActivationMutation`, `AdminSettings`, ActivationRequiredSelfHosted` x 2
> chore: Migrate useSelfHostedCurrentUser to TS Query V5

- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.test.jsx
- src/pages/CommitDetailPage/CommitDetailPage.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.tsx
This PR updates the query for `CommitPageDataQueryOpts` to grab the `isCached` field which will be used in a later PR to create a banner informing the user that there is data in the commit that has been cached from a previous commit.
Ticket: codecov/engineering-team#3152
- Update `CommitPageDataQueryOpts` query and validation schema
- Update MSW mock responses
> feat: Fetch isCached Field with CommitPageDataQueryOpts

- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.test.jsx
- src/pages/CommitDetailPage/CommitDetailPage.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.tsx
> Revert "feat: Fetch isCached Field with CommitPageDataQueryOpts"

- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.test.jsx
- src/pages/CommitDetailPage/CommitDetailPage.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.test.tsx
- src/pages/CommitDetailPage/queries/CommitPageDataQueryOpts.tsx
This PR updates the query for `CommitPageDataQueryOpts` to grab the `isCached` field which will be used in a later PR to create a banner informing the user that there is data in the commit that has been cached from a previous commit.
Ticket: codecov/engineering-team#3152
>[!NOTE]
>This is the second iteration of this PR, as the previous one had an issue with the Zod validation schema and how it handled the union type. This has been resolved in this PR.
>Before:
>```
>const BundleAnalysisReportSchema = z.object({
>  __typename: z.literal('BundleAnalysisReport'),
>  isCached: z.boolean(),
>})
>
>const BundleAnalysisReportUnion = z.union([
>  BundleAnalysisReportSchema,
>  MissingHeadReportSchema.shape.__typename,
>])
>```
>After:
>```ts
>const BundleAnalysisReportSchema = z.object({
> …
```
> feat: Fetch isCached Field with CommitPageDataQueryOpts - Round 2

- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/TokenlessSection.test.tsx
- src/pages/AccountSettings/tabs/OrgUploadToken/TokenlessSection/TokenlessSection.tsx
a quick fix for copy in the tokenless tab
closes: [UI copy updates for token auth](https://github.com/codecov/engineering-team/issues/3060)
> fix: Update copy for tokenless tab

- src/shared/CachedBundleContentBanner/CachedBundleContentBanner.test.tsx
- src/shared/CachedBundleContentBanner/CachedBundleContentBanner.tsx
This PR creates the banner component that will be used in upcoming PRs, adding it to the Commit, and Pull pages.
Ticket: codecov/engineering-team#3153
- Create new `CachedBundleContentBanner` component
- Add in tests
> feat: Create CachedBundleContentBanner Component

- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.test.tsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/PullCoverageTabs.test.jsx
- src/pages/PullRequestPage/PullCoverage/PullCoverageTabs/useTabsCounts.test.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FileViewer/FileViewer.test.jsx
- src/pages/PullRequestPage/PullRequestPage.test.tsx
- src/pages/PullRequestPage/queries/PullPageDataQueryOpts.test.tsx
- src/pages/PullRequestPage/queries/PullPageDataQueryOpts.tsx
This PR updates the query and validation schema for `PullPageDataQueryOpts` to include the `isCached` field for some upcoming work to inform users when a given pull request has data that has been cached from a previous commit included in it.
Tickets: codecov/engineering-team#3152
- Update query string and validation schema for `PullPageDataQueryOpts`
- Add in new field in MSW tests
> feat: Fetch isCached Field in PullPageDataQueryOpts

- src/pages/AdminSettings/AdminMembers/MemberList/MemberTable.tsx
- src/pages/AnalyticsPage/AnalyticsPage.jsx
- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.jsx
- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.test.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FileListTable/FileListTable.tsx
- src/services/repos/ReposQueryOpts.test.tsx
- src/services/repos/ReposQueryOpts.tsx
- src/services/repos/ReposTeamQueryOpts.test.tsx
- src/services/repos/ReposTeamQueryOpts.tsx
- src/services/repos/index.ts
- src/shared/ListRepo/ListRepo.jsx
- src/shared/ListRepo/OrgControlTable/OrgControlTable.test.jsx
- src/shared/ListRepo/ReposTable/ReposTable.test.tsx
- src/shared/ListRepo/ReposTable/ReposTable.tsx
- src/shared/ListRepo/ReposTable/getReposColumnsHelper.tsx
- src/shared/ListRepo/ReposTableTeam/ReposTableTeam.test.tsx
- src/shared/utils/demo.ts
- src/shared/utils/queries.ts
This PR migrates the `useRepos` hook over to the `infiniteQueryOptions` version `ReposQueryOpts` and to TS Query V5. 
~~There's some changes with how the imports from the `repos/config.ts` file that will be cleaned up once the prior PR #3615 has been migrated, and this PR can be rebased off of it.~~
Ticket: codecov/engineering-team#2969
- Migrate `useRepos` to `ReposQueryOpts`
- Update usage in `ReposTable` and `ChartSelectors`
- Update imports from `services/repos/config` (removing barrel file)
- Update/refactor tests
> ref: Migrate useRepos to TS Query V5

- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.test.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.tsx
This PR adds in the newly added cached bundles banner to the commits page behind a feature flag so that we can roll it out together once the work has been done for the pulls page.
Ticket: codecov/engineering-team#3153
- Add banner to commit bundle component behind a feature flag
- Add in tests
>[!note]
>These screenshots are forced as there aren't any examples on staging where caching is enabled.
Coverage and BA enabled:
BA only:
> feat: Add Cache Bundle Banner to Commits Page

- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.test.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.tsx
This PR adds in the cached bundle banner to the pulls page, when there is cached data included on the page. This is currently behind a feature flag, so it can be released at the same time as the commit page one.
Ticket: codecov/engineering-team#3153
- Add banner to commit bundle component behind a feature flag
- Add in tests
>[!note]
>These screenshots are forced as there aren't any examples on staging where caching is enabled.
> feat: Add Cache Bundle Banner to Pulls Page

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/queries/InfiniteAccountOrganizationsQueryOpts.ts
- src/services/bundleAnalysis/BundleAssetsQueryOpts.tsx
- src/services/repos/ReposQueryOpts.tsx
- src/services/repos/ReposTeamQueryOpts.tsx
- src/services/selfHosted/SelfHostedUserListQueryOpts.ts
This PR is a quick fix to ensure that these infinite query options are more consist in the way they handle `pageParam`'s to reduce potential issues down the road, the docs in notion have also been updated accordingly.
- Update all TS Query V5 implementations that differ
> fix: Rewrite infinite queries to be consist using undefined over null

- .eslintrc.cjs
- src/pages/AccountSettings/tabs/Admin/GithubIntegrationSection/GithubIntegrationSection.jsx
- src/pages/AccountSettings/tabs/Admin/GithubIntegrationSection/GithubIntegrationSection.test.jsx
- src/pages/AccountSettings/tabs/Admin/ManageAdminCard/AdminTable/AdminTable.tsx
- src/pages/AccountSettings/tabs/Admin/ManageAdminCard/ManageAdminCard.test.jsx
- src/pages/CommitDetailPage/CommitCoverage/BotErrorBanner/BotErrorBanner.jsx
- src/pages/CommitDetailPage/CommitCoverage/BotErrorBanner/BotErrorBanner.test.jsx
- src/pages/EnterpriseLandingPage/EnterpriseLandingPage.test.tsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.test.tsx
- src/pages/RepoPage/FailedTestsTab/CodecovCLI/CodecovCLI.tsx
- src/pages/RepoPage/FailedTestsTab/GitHubActions/GitHubActions.tsx
- src/pages/SyncProviderPage/SyncButton.test.tsx
- src/shared/GlobalBanners/GitHubRateLimitExceeded/GitHubRateLimitExceededBanner.test.tsx
- src/shared/GlobalBanners/GitHubRateLimitExceeded/GitHubRateLimitExceededBanner.tsx
- src/shared/ListRepo/OrgControlTable/RepoOrgNotFound/RepoOrgNotFound.tsx
- src/shared/utils/loginProviders.ts
- src/shared/utils/provider.test.ts
- src/shared/utils/provider.ts
The linter will now warn if we use Github instead of GitHub, same for GitLab. Also fixes casing errors for Bitbucket. 
This closes https://github.com/codecov/engineering-team/issues/3175
> [chore] Add rule to make provider casing more consistent

- src/services/toast/ErrorToast/ErrorToast.test.tsx
- src/services/toast/ErrorToast/ErrorToast.tsx
- src/services/toast/ErrorToast/index.ts
- src/services/toast/GenericToast/GenericToast.test.tsx
- src/services/toast/GenericToast/GenericToast.tsx
- src/services/toast/GenericToast/index.ts
- src/services/toast/SuccessToast/SuccessToast.test.tsx
- src/services/toast/SuccessToast/SuccessToast.tsx
- src/services/toast/renderToast.test.tsx
- src/services/toast/renderToast.tsx
This PR adds in a new toast variant for "success", this is required for when the user successfully updates their cache settings.
Ticket: codecov/engineering-team#3156
- Tidy up imports for other toasts
- Add in success toast
- Update tests
- Add success toast to the `renderToast` function
> feat: Add Success Variant Toast

- src/services/bundleAnalysis/CachedBundlesQueryOpts.test.tsx
- src/services/bundleAnalysis/CachedBundlesQueryOpts.tsx
This PR adds in a new query that is used to collect the list of bundles and their cache status for the future modal to configure bundle caching settings.
Closes: codecov/engineering-team#3155
- Create `CachedBundlesQueryOpts`
- Add in tests
> feat: Add in CachedBundlesQueryOpts

- src/ui/Select/Select.jsx
This PR fixes a background style on the trend selector elements for both the coverage overview and bundle overview pages.
Just settings it to transparent, pics before and after.
**COVERAGE PAGE**
**BUNDLE PAGE**
> fix: background color on trend selector container for dark mode

- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.test.tsx
- src/pages/RepoPage/CoverageOnboarding/CircleCI/CircleCI.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/TokenStep.tsx
- src/pages/RepoPage/CoverageOnboarding/GitHubActions/WorkflowYMLStep.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.test.tsx
- src/pages/RepoPage/CoverageOnboarding/OtherCI/OtherCI.tsx
- src/services/orgUploadToken/useOrgUploadToken.ts
This PR removes the new repo flag which has been on in LD at 100% since Feb 2024. Safe to say it's probably good to remove at this point; also had to update a few tests in the process.
[Flag in LD](https://app.launchdarkly.com/projects/dashboard/flags/new-repo-flag/targeting?env=test&env=production&selected-env=production)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> chore: Remove new repo flag in LD

- src/services/bundleAnalysis/useUpdateBundleCache.test.tsx
- src/services/bundleAnalysis/useUpdateBundleCache.tsx
This PR adds in a new mutation that will be used with the upcoming modal allowing users to control their bundle cache settings for a given repo.
Closes codecov/engineering-team#3154
- Add in new mutation that updates bundle cache settings
- Add in tests
> feat: Add mutation to update bundle cache settings

- src/shared/AppLink/AppLink.tsx
Fixing a console issue @nicholas-codecov found while developing locally. A tags don't allow you to have a "to" prop on them
This PR removes / clears out the to prop if it exists and the component is an <a> tag.
> fix: Remove "to" prop if component is <a>

- src/ui/ContextSwitcher/ContextSwitcher.test.jsx
- src/ui/ContextSwitcher/ContextSwitcher.tsx
Closes https://github.com/codecov/engineering-team/issues/2734
Figma: https://www.figma.com/design/SsoxtY2SB73l0wiLbJ8FhZ/GH-2092?node-id=2288-16704&t=Ae9VxfEVoCH7C8je-1
> Appless non-PAT org dropdown clarity changes

- src/pages/AnalyticsPage/Chart/useCoverage.ts
- src/pages/AnalyticsPage/ChartSelectors/ChartSelectors.jsx
- src/shared/ListRepo/ReposTable/ReposTable.tsx
We replaced the check for tier names with isTeamPlan, resulting in a false default for isPublic for signed in users 
> Is repo public bug

- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/DangerZone.jsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/EraseRepo/EraseRepo.jsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/EraseRepo/EraseRepo.test.jsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/EraseRepo/EraseRepoModal.jsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/EraseRepo/index.js
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/EraseRepoContent/index.js
- src/services/repo/useEraseRepoContent.test.tsx
- src/services/repo/useEraseRepoContent.tsx
Instead of erasing just the "repo coverage content", the repository as a whole will be deleted using the new `FlushRepo` task. This adjusts the frontend to reflect that.
> Reword the "Erase Repo" action

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/BillingDetails.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentCard.test.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentMethodForm.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentMethodForm.tsx
It appears some customers can have messy data missing billing details email or name, which makes them encounter an error on the Payment Element (this UI element requires this that was formerly optional with the Card Element). 
Instead infer these values from other places on the Stripe customer such as the name/email on the latest invoice, or that attached to the customer, or that attached to the accountDetails.
Fixes https://codecov.sentry.io/issues/6237642048/?alert_rule_id=15115849&alert_type=issue&notification_uuid=50a22e19-57b2-4b3e-81c9-c85911f30570&project=5514400&referrer=issue_alert-slack
> fix: Infer name if not in billing details

- src/shared/ListRepo/ListRepo.jsx
- src/shared/ListRepo/ListRepo.test.tsx
Followup PR to the Non-PAT Appless experience to prevent both the blue Welcome banner and blue GH App Install banner don't show at the same time as it overwhelms the user. The GH banner should only come up when the other is not showing.
Problem: 
New:
> fix: Only show GH config banner when no welcome banner

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSelection/BundleSelection.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleSelection/BundleSelection.tsx
- src/pages/RepoPage/ConfigTab/tabs/ConfigurationManager/ConfigurationManager.test.tsx
- src/pages/RepoPage/ConfigTab/tabs/ConfigurationManager/ConfigurationManager.tsx
This PR just removes the `displayBundleCachingModal` from the codebase cleaning up things once everything has been fully released.
Closes codecov/engineering-team#3157
- Clean up feature flag in `BundleSelection` and `ConfigurationManager`
> chore: Clean up bundle caching feature flag

- src/App.test.tsx
Small PR that adds in `OwnerContext` and `RepoContext` MSW mocks to `App.test.tsx` to silence some console warnings
- Add `OwnerContext` and `RepoContext` MSW mocks to `App.test.tsx`
> chore: Add in Owner/RepoContext MSW Mocks to App tests

- src/pages/AccountSettings/tabs/OktaAccess/OktaAccess.test.tsx
- src/pages/AccountSettings/tabs/OktaAccess/OktaConfigForm/OktaConfigForm.test.tsx
- src/pages/AccountSettings/tabs/OktaAccess/OktaConfigForm/OktaConfigForm.tsx
- src/pages/AccountSettings/tabs/OktaAccess/hooks/index.ts
- src/pages/AccountSettings/tabs/OktaAccess/hooks/useUpdateOktaConfig.test.tsx
- src/pages/AccountSettings/tabs/OktaAccess/hooks/useUpdateOktaConfig.tsx
- src/pages/AccountSettings/tabs/OktaAccess/queries/OktaConfigQueryOpts.test.tsx
- src/pages/AccountSettings/tabs/OktaAccess/queries/OktaConfigQueryOpts.tsx
- src/shared/GlobalTopBanners/OktaBanners/OktaBanners.test.tsx
- src/shared/GlobalTopBanners/OktaBanners/OktaBanners.tsx
This PR migrates the `useOktaConfig` to TSQ V5 `queryOptions` API version `OktaConfigQueryOpts`, as well as it's usage in a couple of components and tests.
Ticket: codecov/engineering-team#2963
- Migrates `useOktaConfig` to `OktaConfigQueryOpts`
- Update `useUpdateOktaConfig` to use TSQ V5 and `OktaConfigQueryOpts` to clear the cache
- Update usage in `OktaConfigForm`, and `OktaBanners`
- Update tests, including `OktaAccess`
> ref: Migrate useOktaConfig to TSQ V5

- src/pages/MembersPage/MembersActivation/MembersActivation.jsx
- src/pages/MembersPage/MembersActivation/MembersActivation.test.jsx
Title. Adds another data fetch hook call, but I think this is guaranteed to be a local cache hit as this same hook is used in a parent component.
Closes https://github.com/codecov/engineering-team/issues/3201
> feat: Only show auto-activate toggle for admins when on enterprise cloud plan

- src/pages/OwnerPage/OwnerPage.jsx
- src/shared/ListRepo/ListRepo.test.tsx
- src/shared/ListRepo/ListRepo.tsx
- src/ui/Icon/svg/outline/index.jsx
Closes https://github.com/codecov/engineering-team/issues/3287
Background info copied from ^ for context:
In the new non-PAT appless experience, we made a shift of rendering the GH Config Banner from `<HeaderBanners>` to `<ListRepo>` which moved it outside of scope of the `SilentNetworkErrorWrapper`. The `account-details` API (used for getting data about if org has GH app installed) call 404s inside of that ErrorBoundary wrapper so anything `isGHApp` related would just error and be caught by the boundary. Now that we've moved `<GithubConfigBanner>` out, it needs more boolean checks to make sure we only show it for admins on their org that does not have the GH app already installed. We also don't want to show this at the same time as the "Welcome" banner when someone just onboards. 
Check …
> fix: Only show GH app config banner if admin

- src/ui/Modal/Modal.tsx
- tailwind.config.mjs
Adding an optional classname prop for the size of a modal to allow possible extra styles such as max width. Currently, on large screens, the designated width is 50% which can be much wider than needed, especially if the modal also has vertical scrolling as our BaseModal element right now has a max height of `m-h-96' designated.
Existing situation that is super wide where a single text line doesn't even reach the halfway point of the modal:
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> fix: Add modal max width on wide screens

- src/shared/utils/billing.ts
Needed so it doesn't fail when we default users to usere-developer in db
> feat: Add users-developer to plans enum

- src/shared/GlobalTopBanners/TokenlessBanner/TokenlessBanner.test.tsx
- src/shared/GlobalTopBanners/TokenlessBanner/TokenlessBanner.tsx
Closes https://github.com/codecov/engineering-team/issues/3009
Only show banner if user is logged in.
Logged in:
Logged out:
> fix: Hide tokenless banner for signed out user

- src/config.js
- src/config.test.js
- src/shared/GlobalBanners/SelfHostedLicenseExpiration/SelfHostedLicenseExpiration.test.tsx
- src/shared/GlobalBanners/SelfHostedLicenseExpiration/SelfHostedLicenseExpiration.tsx
> DISPLAY_SELF_HOSTED_EXPIRATION_BANNER probably

- src/pages/TermsOfService/TermsOfService.tsx
Fixes Safari only race condition in new onboarding flow.
> fix: Onboarding continue button on Safari

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/InfoMessageStripeCallback/InfoMessageStripeCallback.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/InfoMessageStripeCallback/InfoMessageStripeCallback.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.tsx
Fixes scenario where user sets up an initial checkout session with an instant payment method (like credit card), then they go to put in a new delayed notification payment method (e.g., ACH microdeposits). Then during these 2 days of waiting, they go to upgrade their Codecov account from Team to Pro. This should NOT show the modal that says it will cancel their existing incomplete upgrade. The modal should only show if this is the initial checkout session. This PR fixes that logic.
> fix: Handle ach case

- package.json
- vitest.config.mjs
- yarn.lock
Bumping to latest version of Vitest closing out any potential security tickets ahead of time.
[Release notes for V2.1.9](https://github.com/vitest-dev/vitest/releases/tag/v2.1.9)
> chore: Update Vitest to latest V2

- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/BundleContent.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/InfoBanner/InfoBanner.test.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/InfoBanner/InfoBanner.tsx
- src/services/bundleAnalysis/BranchBundleSummaryQueryOpts.test.tsx
- src/services/bundleAnalysis/BranchBundleSummaryQueryOpts.tsx
This PR updates the bundles tab to conditionally render the trend chart if timescale is not enabled on the backend as the chart is powered from data that comes from timescale.
Closes: codecov/engineering-team#3215
- Migrate `BranchBundleSummaryQueryOpts` fully to query options API and remove `useBranchBundleSummary`
- Update `BundleContent` to conditionally 
Timescale enabled:
Timescale disabled:
> feat: Hide BA trend chart if Timescale is disabled

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
This PR is a quick fix to allow rendering the test results when there are test results to be shown, but also this is the users first pull request. This issue was ran into, where there were test results uploaded on a branch, and no branches had been merged into main.
Examples:
- [Preview deploy](https://preview-pr-3710.codecov.dev/gh/eliatcodecov/PHPMailer/tests/add_codecov_staging)
- [Prod](https://app.codecov.io/gh/eliatcodecov/PHPMailer/tests/add_codecov_test_analytics)
- Update `FailedTestsTable` logic to only show first pull message when first pull and no data to be rendered
- Update tests to add in new cases
> fix: Test results not rendering on first pull branches with test data

- src/stripe.ts
ACH bank picker buttons were hard to read due to the background color of them previously. This PR updates that color to a lighter gray to make it easier to view. Also updates the text color to be darker as well, which I think is only the case on test mode, but just to be safe.
Closes https://github.com/codecov/engineering-team/issues/3338
**OLD**
**NEW - Dark Mode**
**Regression - Light Mode**
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate …
> fix: Update picker button colors for ACH on dark mode

- src/pages/AnalyticsPage/Chart/Chart.test.tsx
- src/pages/AnalyticsPage/Chart/Chart.tsx
- src/pages/AnalyticsPage/Chart/useCoverage.test.tsx
- src/pages/AnalyticsPage/Chart/useCoverage.ts
- src/services/charts/ReposCoverageMeasurementsQueryOpts.test.tsx
- src/services/charts/ReposCoverageMeasurementsQueryOpts.ts
This PR migrates the `useReposCoverageMeasurements` over to the query options version `ReposCoverageMeasurementsQueryOpts`. 
Ticket: codecov/engineering-team#3165
- Migrates `useReposCoverageMeasurements` to `ReposCoverageMeasurementsQueryOpts`
- Update usage in `useCoverage`
- Update usage in `Chart.tsx`
- Update tests
> ref: Migrate useReposCoverageMeasurements to TSQ V5

- package.json
- yarn.lock
This PR updates Sentry to the newly release version 9 of their SDK, at the same time I also bumped the version of the `@sentry/vite-plugin` to it's latest version as well, just to ensure that we're up to date on everything Sentry.
- Update `@sentry/react` and `@sentry/vite-plugin` to their latest versions
> chore: Upgrade Sentry SDK to V9

- src/pages/AccountSettings/tabs/Access/CreateTokenModal.jsx
- src/pages/AccountSettings/tabs/Access/CreateTokenModal.test.jsx
- src/services/access/index.ts
- src/services/access/useGenerateUserToken.test.tsx
- src/services/access/useGenerateUserToken.ts
This PR migrates the `useGenerateUserToken` over to TSQ V5, and updates it's usage throughout the app.
Ticket: codecov/engineering-team#3167
- Migrate `useGenerateUserToken` over to TSQ V5
- Update usage in `CreateTokenModal`
- Update tests
> ref: Migrate useGenerateUserToken to TSQ V5

- package.json
- src/services/events/__mocks__/events.ts
- src/services/events/amplitude/amplitude.test.tsx
- src/services/events/amplitude/amplitude.ts
- src/services/events/events.ts
- src/services/events/types.ts
- yarn.lock
Enables Amplitude autocapture for attribution, sessions, and page views.
> feat: Enable some Amplitude autocapture events

- src/pages/AccountSettings/tabs/OrgUploadToken/OrgUploadToken.test.tsx
- src/pages/AccountSettings/tabs/OrgUploadToken/RegenerateOrgUploadToken.tsx
This PR aims to fix some weird behavior when hiding org upload tokens where an extra character was being added to the end of each pattern due to the "|" operator being present and comparing the last character in each sequence, an empty "" and converting that character to an "x" as well.
We just remove the "|" and we're good
Closes https://github.com/codecov/internal-issues/issues/174
**BEFORE**
https://github.com/user-attachments/assets/f6ea57a6-056b-4ff3-bb0e-5d9ae8874043
**AFTER**
https://github.com/user-attachments/assets/e70a7da3-e87b-45ff-ad12-2ab3845180f7
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in …
> fix: Extra x's when replacing / hiding tokens

- src/services/events/amplitude/amplitude.test.tsx
- src/services/events/amplitude/amplitude.ts
I was looking at the available properties again and it seems we are missing out on a bunch by doing things in the way I had initially set it up. Now, instead of stating the keys we do want, we'll just delete the keys we don't want. This means we get whatever else amplitude sends, including some useful attribution stuff (utm_params, referrer domain, etc).
> ref: Update Amplitude page view sanitization

- src/services/repo/useEraseRepoContent.tsx
Interestingly enough, the `owner` was already being passed an one of the mutation `variables`, but that was not being used to pass along to the `eraseRepository` mutation within the graphql query.
This is being done now, and the mutation is being triggered with that input field.
---
Depends on https://github.com/codecov/codecov-api/pull/1156 which adds this new input field.
> Pass the `owner` along to the `eraseRepository` mutation

- src/layouts/BaseLayout/hooks/useUserAccessGate.js
This PR fixes a small logic issue, where if the user doesn't exist it tries to update the default org for the user, causing an empty failure toast to pop up. This PR fixes this issue, by checking to see if the user data exists in the first place.
- Check to see if user exists
Before:
https://github.com/user-attachments/assets/ef3a7e5d-6b54-4493-9a58-f8e34b3e9e74
After:
https://github.com/user-attachments/assets/59152997-43b9-4d91-aad2-74d2999700c0
> fix: Check to see if user exists before setting default org

- src/index.tsx
- src/sentry.ts
- src/shared/featureFlags/featureFlag.ts
Followed the [docs](https://docs.sentry.io/platforms/javascript/configuration/integrations/launchdarkly/) to get the Sentry LD setup all configured. As well i have gone through and setup the webhook integration in LD itself to send updates to Sentry when we change our feature flags.
- Reorder App startup sequence so Sentry is initialized before LD
- Add LD integration to Sentry integrations
- Add Sentry inspector to LD inspectors
> feat: Add Sentry feature flag integration with LD

- src/pages/CommitDetailPage/CommitCoverage/CommitCoverage.jsx
- src/pages/CommitDetailPage/CommitCoverage/CommitCoverageSummary/hooks/useCommitForSummary.js
- src/pages/CommitDetailPage/CommitCoverage/UploadsCard/useUploads/useUploads.ts
- src/pages/CommitDetailPage/CommitCoverage/YamlModal/YAMLViewer.jsx
- src/pages/CommitDetailPage/CommitCoverage/YamlModal/YAMLViewer.test.jsx
- src/pages/CommitDetailPage/CommitCoverage/routes/ComponentsSelector/ComponentsSelector.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.test.tsx
- src/services/commit/index.ts
- src/services/commit/useCommit.test.tsx
- src/services/commit/useCommitYaml.test.tsx
- src/shared/utils/extractUploads.ts
This PR removes the `index.ts` file from the `services/commit` directory, and updates the various imports throughout the app to their updated import paths.
Ticket: codecov/engineering-team#3352
- Remove `index.ts` from `services/commit`
- Update imports across the app
> chore: Remove use of barrel files in services/commit

- src/pages/RepoPage/BundlesTab/BundleContent/BundleSelection/BranchSelector.tsx
- src/pages/RepoPage/CommitsTab/CommitsTab.jsx
- src/pages/RepoPage/CommitsTab/hooks/useCommitsTabBranchSelector.ts
- src/pages/RepoPage/ConfigTab/tabs/BadgesAndGraphsTab/Badges/Badges.tsx
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DefaultBranch/DefaultBranch.jsx
- src/pages/RepoPage/CoverageTab/ComponentsTab/Header/BranchSelector/BranchSelector.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/Summary/CoverageTrend/CoverageTrend.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/hooks/useBranchSelector.ts
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/ComponentsMultiSelect/ComponentsMultiSelect.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/CoverageChart/CoverageChart.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/summaryHooks/useSummary.ts
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.tsx
- src/services/branches/index.ts
- src/services/branches/useBranch.tsx
This PR removes the barrel index file from the `services/branches` directory, and updates the respective imports across the app.
Ticket: codecov/engineering-team#3352
- Remove `index.ts` from `services/branches`
- Update `services/branches` imports
> chore: Remove use of barrel files in services/branches

- src/ui/SunburstChart/SunburstChart.jsx
Pretty quick PR to replace the usage of `structuredClone`, as some (edge) users are running into issues with it.
Can see this [Sentry issue](https://codecov.sentry.io/issues/6318271732/?environment=production&project=5514400&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=10), for more details.
> fix: Remove use of structuredClone

- src/services/repo/useRepoComponentsSelect.test.tsx
- src/services/repo/useRepoComponentsSelect.tsx
- src/services/repo/useRepoConfig.test.tsx
- src/services/repo/useRepoConfig.tsx
- src/services/repo/useRepoCoverage.test.tsx
- src/services/repo/useRepoCoverage.tsx
- src/services/repo/useRepoFlags.test.tsx
- src/services/repo/useRepoFlags.tsx
- src/services/repo/useRepoFlagsSelect.test.tsx
- src/services/repo/useRepoFlagsSelect.tsx
- src/services/repo/useRepoOverview.test.tsx
- src/services/repo/useRepoOverview.tsx
- src/services/repo/useRepoRateLimitStatus.test.tsx
- src/services/repo/useRepoRateLimitStatus.tsx
- src/services/repo/useRepoSettings.test.tsx
- src/services/repo/useRepoSettings.tsx
- src/services/repo/useRepoSettingsTeam.test.tsx
- src/services/repo/useRepoSettingsTeam.tsx
- src/services/uploadTokenRequired/useUploadTokenRequired.test.tsx
- src/services/uploadTokenRequired/useUploadTokenRequired.tsx
- src/services/useIsTeamPlan/useIsTeamPlan.test.tsx
- src/services/useIsTeamPlan/useIsTeamPlan.ts
- src/services/user/useInternalUser.test.tsx
- src/services/user/useInternalUser.ts
This PR is part four in a series going through Gazebo updating our API calls to utilize `rejectNetworkError` in functions where we call the API.
Ticket: codecov/engineering-team#3329
- Update API calls to use `rejectNetworkError` (see [commits](https://github.com/codecov/gazebo/pull/3768/commits))
- Update tests
> feat: Add rejectNetworkError to API calls (part four)

- src/services/user/useMyContexts.test.tsx
- src/services/user/useMyContexts.ts
- src/services/user/useOwnerRateLimitStatus.test.tsx
- src/services/user/useOwnerRateLimitStatus.tsx
- src/services/user/useUser.test.tsx
- src/services/user/useUser.ts
- src/services/users/useInfiniteUser.test.tsx
- src/services/users/useInfiniteUser.tsx
This is the last PR updating API calls to use the new `rejectNetworkError` helper function
Ticket: codecov/engineering-team#3329
- Update calls to use updated `rejectNetworkError` (see [commits](https://github.com/codecov/gazebo/pull/3771/commits))
- Update tests
> feat: Add rejectNetworkError to calls (part five)

- src/shared/ContentsTable/TableEntries/BaseEntries/DirEntry.test.tsx
- src/shared/ContentsTable/TableEntries/BaseEntries/DirEntry.tsx
Converts DirEntry to TSX.
Part of https://github.com/codecov/engineering-team/issues/2747
> ref: Convert DirEntry to TSX

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentOrgPlan.test.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FileExplorer.test.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Sunburst/Sunburst.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Sunburst/Sunburst.test.jsx
- src/services/account/useAccountDetails.ts
- src/services/charts/SunburstCoverageQueryOpts.ts
- src/services/pathContents/branch/dir/useRepoBranchContents.test.tsx
- src/services/pathContents/branch/dir/useRepoBranchContents.tsx
- src/services/user/useInternalUser.ts
This PR fixes an initial set parsing errors that have been raised in Sentry:
- https://codecov.sentry.io/issues/6328437600/?project=5514400
- https://codecov.sentry.io/issues/6328498503/?project=5514400
- https://codecov.sentry.io/issues/6331422543/?project=5514400
Ticket: codecov/engineering-team#3385
- Update schemas for: `useRepoBranchContents`, `SunburstCoverageQueryOpts `, `useInternalUser`, `useAccountDetails`
- Update affected things
> fix: Initial set of parsing errors

- src/services/user/TokenlessQueryOpts.ts
Fixes https://codecov.sentry.io/issues/6334753344/?project=5514400
> fix: Set new owner fields to nullable in zod

- src/pages/PullRequestPage/PullCoverage/Summary/CompareSummary/usePullForCompareSummary.js
- src/pages/PullRequestPage/PullCoverage/Summary/CompareSummary/usePullForCompareSummary.test.js
- src/pages/PullRequestPage/PullCoverage/routes/ComponentsSelector/ComponentsSelector.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FilesChangedTable/FilesChangedTable.test.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/NameColumn/NameColumn.jsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/hooks/useImpactedFilesTable.js
- src/pages/PullRequestPage/PullCoverage/routes/FlagsTab/FlagsTab.test.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FlagsTab/FlagsTab.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/IndirectChangedFiles.test.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/NameColumn/NameColumn.jsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.ts
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/PullFileDiff/PullFileDiff.tsx
- src/services/pull/index.ts
This PR removes the barrel file from `services/pull`, while updating the imports throughout the app.
Ticket: codecov/engineering-team#3352
- Remove `index.ts` from `services/pull`
- Update imports throughout app.
> chore: Remove use of barrel files in services/pull

- src/ui/SunburstChart/SunburstChart.jsx
This PR quickly adds `withProfiler` HOC to the `SunburstChart` so we can start collecting information on it, for comparison against some optimizations that are in the pipeline.
Closes: codecov/engineering-team#3428
> feat: Profile sunburst chart

- src/services/pull/usePullCompareTotalsTeam.tsx
This PR updates the Zod schema for usePullCompareTotalsTeam to set the `patchCoverage` field to be nullable
Ticket: codecov/engineering-team#3385
- Set `patchCoverage` to be nullable
> fix: usePullCompareTotalsTeam parsing error

- src/shared/ListRepo/ListRepo.test.tsx
- src/shared/ListRepo/ListRepo.tsx
- src/shared/ListRepo/OrgControlTable/OrgControlTable.test.tsx
- src/shared/ListRepo/OrgControlTable/OrgControlTable.tsx
Closes https://github.com/codecov/engineering-team/issues/3445
Adding back the resync feature that was removed as part of https://github.com/codecov/gazebo/pull/3727
> fix: Add back sync repos feature in list

- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/Sunburst/Sunburst.jsx
- src/ui/SunburstChart/SunburstChart.jsx
The goal of this PR is to optimize the sunbursts performance overall and reduce the lagginess when viewing the coverage overview page. This was accomplished by changing the way that we render the sunburst. Previously we would render the entire tree structure of the repo, hiding elements that weren't currently visible. This lead to many performance issues as we were creating two elements per file in a repo. When users interacted with the sunburst, under the hood it was actually D3 updating the elements attributes overtime "animating" the transition.
With this refactor we have changed our rendering strategy, and how users interact with the sunburst:
**Initial render:**
1. Process and set root node
2. Set the root node as the selected node
3. Run effect
1. Call `renderArcs`
1.  Determine …
> ref: Render only two levels of the sunburst

- src/pages/AccountSettings/tabs/Admin/ManageAdminCard/AdminTable/AdminTable.tsx
- src/pages/MembersPage/MembersList/MembersTable/MembersTable.tsx
- src/services/users/useInfiniteUser.test.tsx
- src/services/users/useInfiniteUser.tsx
Should resolve this [Sentry issue](https://codecov.sentry.io/issues/6333058034/?project=5514400&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=3) from occurring again.
Ticket: codecov/engineering-team#3385
- Make field nullable
- Only extract values that are being used, as this is optimal for reducing the amount of things being tracked by Query, reducing the chance of an extra re-render
> fix: useInfiniteUser schema parsing error

- src/ui/Toggle/Toggle.stories.tsx
- src/ui/Toggle/Toggle.test.tsx
- src/ui/Toggle/Toggle.tsx
This PR adds an optional spinner on the Toggle component that can be triggered by a new isLoading prop.
To be used in https://github.com/codecov/engineering-team/issues/3325
> feat: Add spinner to Toggle component

- src/layouts/Header/components/GuestHeader/GuestHeader.test.tsx
- src/layouts/Header/components/GuestHeader/GuestHeader.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/PullFileDiff/PullFileDiff.test.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/PullFileDiff/PullFileDiff.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/PullFileDiff/PullFileDiff.test.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/PullFileDiff/PullFileDiff.tsx
- src/shared/RawFileViewer/RawFileViewer.test.tsx
- src/shared/RawFileViewer/RawFileViewer.tsx
This PR updates the various locations in Gazebo where we are using a `pageName: 'login'`, and updating them to include a `to` param of the current location. This will allow us to redirect the user from whatever page they are on after logging in with Codecov, streamlining the process for users to get back to where they were.
Closes: codecov/engineering-team#3452
- Update `GuestHeader`, `CommitFileDiff` x 2, `PullFileDiff` x 2, and `RawFileViewer` to include `to` redirect param
- Update tests
> feat: Update login pageName to include redirect

- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.jsx
- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.test.jsx
This PR updates the `NetworkErrorBoundary` component when a 404 error occurs to conditionally render a `Login` button with a redirect to the current page if the user is currently not logged in
Closes: codecov/engineering-team#3453
- Add login button to `NetworkErrorBoundary`
- Update copy for when 404's occur, and `DocErrorMessage` to conditionally render capital letters
- Update tests
> feat: Update NotFoundError to have login button

- src/pages/PullRequestPage/PullCoverage/routes/ComponentsSelector/ComponentsSelector.tsx
- src/services/account/useInvoices.ts
- src/services/bundleAnalysis/BundleTrendDataQueryOpts.tsx
- src/services/pathContents/branch/dir/usePrefetchBranchDirEntry.tsx
- src/services/pull/usePullComponents.tsx
This PR updates the following Zod schemas, to resolve their related Sentry issue:
- `useInvoices` -> [Sentry issue](https://codecov.sentry.io/issues/6393367486/?query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=5)
- `usePrefetchBranchDirEntry` -> [Sentry issue](https://codecov.sentry.io/issues/6392066289/?alert_rule_id=15115849&alert_type=issue&notification_uuid=07598a3a-0bc0-4a4a-8923-18b54d42b184&project=5514400&referrer=issue_alert-slack)
- `BundleTrendQueryOpts` -> [Sentry issue](https://codecov.sentry.io/issues/6391712513/?alert_rule_id=15115849&alert_type=issue&notification_uuid=8a1a2e6d-83a8-4cd5-8034-237eeb0c504e&project=5514400&referrer=issue_alert-slack)
- `usePullComponents` -> [Sentry …
> fix: useInvoices, usePrefetchBranchDirEntry, BundleTrendQueryOpts, usePullComponents schemas

- src/pages/MembersPage/MembersActivation/AutoActivate/AutoActivate.jsx
- src/pages/MembersPage/MembersList/MembersList.jsx
- src/pages/MembersPage/MembersList/MembersList.test.jsx
- src/pages/MembersPage/MembersList/MembersTable/MembersTable.test.tsx
- src/pages/MembersPage/MembersList/MembersTable/MembersTable.tsx
- src/pages/MembersPage/MembersList/MembersTable/index.js
- src/services/users/useUpdateUser.js
- Adds a spinner to indicate the query is in flight.
- To achieve the spinners on members list I did a refactor that pulls the mutation down into the table component itself. Also gets rid of unnecessary prop drilling.
- Prevents the toggle div from filling the whole card width (whole div is clickable).
- Right aligns toggles in the members list.
Closes https://github.com/codecov/engineering-team/issues/3325
> fix: Various usability tweaks on the members page

- src/pages/RepoPage/CoverageOnboarding/UseFrameworkInstructions.tsx
Fixes pytest test run command.
I recall testing this worked without `--cov` when I last updated this, but today it seems to not work. I guess my testing was wrong.
> fix: Pytest instructions wrong command

- src/layouts/Header/components/UserDropdown/UserDropdown.test.tsx
- src/pages/MembersPage/MembersActivation/MembersActivation.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/ComponentsMultiSelect/ComponentsMultiSelect.test.tsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FlagMultiSelect.test.jsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/services/commit/useCommit.test.tsx
- src/ui/FileViewer/ToggleHeader/Title/Title.test.tsx
- vitest.config.mjs
Fixes a few flakes. There are probably more but CI has passed twice in a row.
> fix: some flakes

- .github/workflows/ci.yml
Overwatch uses a default `.` for working directory if not specified in the flag.
This results in the below command run, which fails in local as well
```
yarn run eslint .                                                                                                                 
Oops! Something went wrong! :(
ESLint: 8.57.1
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/suejungshin/dev/codecov/gazebo/node_modules/tsconfck/package.json
Occurred while linting /Users/suejungshin/dev/codecov/gazebo/vite.config.mjs:1
Rule: "import/namespace"
at exportsNotFound (node:internal/modules/esm/resolve:296:10)
at packageExportsResolve (node:internal/modules/esm/resolve:586:13)
at resolveExports (node:internal/modules/cjs/loader:640:36)
at Function._findPath …
```
> chore(overwatch): Fix overwatch CI step

- src/sentry.ts
- src/shared/featureFlags/featureFlag.ts
Reduce the noise in our console in prod by lowering the loglevel for Launch Darkly and Sentry integrations.
> chore: Silence launchDarkly, sentry console logs

- src/pages/RepoPage/CoverageTab/ComponentsTab/subroute/ComponentsTable/ComponentsTable.test.tsx
- src/pages/RepoPage/CoverageTab/ComponentsTab/subroute/ComponentsTable/ComponentsTable.tsx
Changes from "Coverage %" to "Last aggregated coverage %" in the Components tab to better communicate intent to user.
Closes https://github.com/codecov/engineering-team/issues/3460
> fix: Change header text for components

- src/ui/FileViewer/ToggleHeader/Title/Title.tsx
Remove the redundant call to the flags api. Was formerly calling with `filters: {term: ""}` and also `filters: {}` so reduce it down to 1 call. These behave same on the [api side](https://github.com/codecov/codecov-api/blob/795e37f5bb45e311b351af47442f9cad2cdb1afb/graphql_api/actions/flags.py#L27) so that's no issue.
Closes https://github.com/codecov/engineering-team/issues/3529
> fix: Remove redundant call - coverage file

- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FileExplorer.jsx
- src/pages/RepoPage/CoverageTab/OverviewTab/subroute/FileExplorer/FlagMultiSelect.jsx
Remove a couple more duplicate calls on the coverage overview page
* Branch Contents ~400 ms (was called both with and without some default initial ordering - updated so both calls would have the same first call so first page load is faster and can make the extra call if sorting the table)
* Flag Select ~100 ms (was swapping between null and "")
Closes https://github.com/codecov/engineering-team/issues/3530
> fix: Remove duplicate calls on coverage overview page

- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/shared/CommitFileDiff/CommitFileDiff.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.test.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/CommitFileDiff/CommitFileDiff.tsx
- src/services/comparison/constants.ts
- src/services/comparison/useComparisonForCommitAndParent/useComparisonForCommitAndParent.test.tsx
- src/services/comparison/useComparisonForCommitAndParent/useComparisonForCommitAndParent.tsx
- src/services/navigation/useStaticNavLinks.test.tsx
- src/services/navigation/useStaticNavLinks.ts
Handle when segments returns `ProviderError` or `UnknownPath` [here](https://github.com/codecov/codecov-api/blob/18eb985ef8ed3d409421df684e8fb9f6442cec17/graphql_api/types/segment_comparison/segment_comparison.graphql#L11). 
Closes https://github.com/codecov/engineering-team/issues/3485
> fix: Handle segments ProviderError

- docker/Dockerfile
Updates base docker images to alpine 3.21
Closes https://github.com/codecov/feedback/issues/705
> chore: Update base docker images to alpine3.21

- src/layouts/Header/components/GuestHeader/GuestHeader.test.tsx
- src/layouts/Header/components/GuestHeader/GuestHeader.tsx
- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.jsx
- src/layouts/shared/NetworkErrorBoundary/NetworkErrorBoundary.test.jsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.test.tsx
- src/pages/EnterpriseLandingPage/ProviderCard/ProviderCard.tsx
- src/pages/LoginPage/LoginButton.jsx
- src/pages/LoginPage/LoginButton.test.jsx
- src/pages/LoginPage/LoginPage.jsx
- src/pages/LoginPage/LoginPage.test.jsx
- src/services/navigation/useNavLinks.ts
> fix: change login copy to say 'log in'

- src/shared/utils/dates.test.ts
- src/shared/utils/dates.ts
The total test run time on https://app.codecov.io/github/getsentry/sentry/tests/master is bugged, this fixes that.
> fix(ta): seconds to duration function

- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/ProPlanController/BillingOptions/BillingOptions.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/ProPlanController/BillingOptions/BillingOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/ProPlanController/ProPlanController.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/ProPlanController/ProPlanController.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/ProPlanController/UserCount/UserCount.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/SentryPlanController/BillingOptions/BillingOptions.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/SentryPlanController/BillingOptions/BillingOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/SentryPlanController/SentryPlanController.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/SentryPlanController/SentryPlanController.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/BillingOptions/BillingOptions.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/BillingOptions/BillingOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/ErrorBanner/ErrorBanner.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/TeamPlanController.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/TeamPlanController.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/Controllers/TeamPlanController/UserCount/UserCount.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PendingUpgradeModal.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PendingUpgradeModal.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PersonalOrgWarning.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PlanTypeOptions/PlanTypeOptions.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/PlanTypeOptions/PlanTypeOptions.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateBlurb/UpdateBlurb.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateButton/UpdateButton.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpdateButton/UpdateButton.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.test.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeForm/UpgradeForm.tsx
Adds a few changes that draw attention to the org you are about to change the plan of. Most notably, this adds a confirmation modal to the checkout flow and adds a banner letting you know you're about to change the plan of your personal org. This is because we've had several issues caused by users upgrading their personal org by accident. There is another issue that fixes a more core issue, but these are certainly improvements regardless.
Closes https://github.com/codecov/feedback/issues/722
Closes https://github.com/codecov/feedback/issues/651
Related to https://github.com/codecov/engineering-team/issues/3587
> feat: Add personal org warnings to checkout flow

- src/App.test.tsx
- src/App.tsx
- src/layouts/BaseLayout/BaseLayout.test.tsx
- src/layouts/BaseLayout/hooks/useUserAccessGate.test.tsx
- src/pages/SyncProviderPage/SyncProviderPage.test.tsx
- src/pages/TermsOfService/TermsOfService.test.tsx
- src/services/user/useInternalUser.test.tsx
- src/services/user/useInternalUser.ts
Main motivation for this is plan page troubles faced by users. A common flow we're trying to fix is: User clicks Learn more on plans page which takes them to our marketing site. They they click Get started from the marketing site, which takes them back to the app, but the default org logic fails and they end up on their personal org instead of the org they started with. We have had several instances of users upgrading the plan of their personal org instead of the desired org from this flow. We made some other improvements to the checkout page in a previous PR, but we also want to get this part fixed as it's likely the primary problem.
> feat: Use new default-org on internal user for default org decision

- src/shared/utils/billing.ts
Fixes Plan page schema parsing fail on new plan name.
Fixes https://codecov.sentry.io/issues/6713090607/?project=5514400&query=is%3Aunresolved&referrer=issue-stream&stream_index=4
> fix: Add sentry-merge to list of acceptable plan names

- src/App.tsx
When no default org exists currently, users are shown an empty page. This change fixes that behaviour to show the user’s personal org instead.
> fix: Default to owner username when no default org received

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/Address/AddressCard.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/Address/AddressForm.tsx
- src/services/account/useUpdateBillingAddress.ts
Paired with this https://github.com/codecov/umbrella/pull/298/files
Properly show the user the error
> fix(address-form): Update error message for address form

- .github/workflows/ci.yml
- src/pages/RepoPage/ConfigTab/tabs/GeneralTab/DangerZone/EraseRepo/EraseRepoModal.jsx
Overwatch CI no longer needed, just removing from Gazebo for cleanup
Relates to https://linear.app/getsentry/issue/PREVENT-260/clean-up-overwatch-cli
Also snuck in a copy update to tighten up some wording on the delete repo component
> chore: Remove overwatch from CI

- src/pages/RepoPage/CoverageOnboarding/GitHubActions/TokenStep.tsx
Closes https://linear.app/getsentry/issue/CCMRG-676/remove-the-static-repo-name-or-make-it-dynamic
Replaces hardcoded repo name with the repo they are looking at
> fix: Use dynamic repo name for token step copy

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/BranchSelector/BranchSelector.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/SelectorSection/SelectorSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useFlakeAggregates/useFlakeAggregates.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useTestResultsAggregates/useTestResultsAggregates.tsx
This PR adds changes so that the default value for TA pages is "All Branches" instead of the default branch.
> feat: add all branches as default capability to test analytics page
