codecov/gazebo

- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.spec.tsx
- src/pages/OwnerPage/Tabs/TrialReminder/TrialReminder.tsx
- src/pages/PlanPage/subRoutes/UpgradePlanPage/UpgradeDetails/UpgradeDetails.spec.jsx
Updates trial copy from "Trial Pro Team" to "Try Codecov Pro"
> Update Trial Copy and Tests

- src/pages/DefaultOrgSelector/DefaultOrgSelector.jsx
- src/pages/DefaultOrgSelector/DefaultOrgSelector.spec.jsx
- src/pages/DefaultOrgSelector/GitHubHelpBanner/GitHubHelpBanner.jsx
- src/pages/DefaultOrgSelector/GitHubHelpBanner/GitHubHelpBanner.spec.jsx
- src/shared/GlobalTopBanners/RequestInstallBanner/RequestInstallBanner.jsx
- src/shared/GlobalTopBanners/RequestInstallBanner/RequestInstallBanner.spec.jsx
- src/shared/ListRepo/OrgControlTable/RepoOrgNotFound/RepoOrgNotFound.jsx
- src/shared/ListRepo/OrgControlTable/RepoOrgNotFound/RepoOrgNotFound.spec.jsx
Copy changes for trial onboarding
- Copy and test changes in onboarding and repos page
> fix: Copy changes + tests

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.spec.jsx
Another day ... another PR removing trial flag things, this time from the `FreePlanCard` component.
- Remove trial flag from `FreePlanCard` component
- Update tests
> ref: Remove Trial Flag from FreePlanCard

- .github/workflows/ci.yml
Since we're slowly migrating to TS might as well as throw in a type checking step. As well this PR adds names to each step missing one, and adds a consistent styling format to the steps arrays.
> build: Add Some Type Checking and Some Formatting

- src/services/commit/useCommit.tsx
- src/services/commit/useCompareTotals.tsx
- src/services/commits/useCommits.js
- src/services/comparison/constants.js
- src/services/pull/fragments.js
- src/services/pulls/usePulls.tsx
> Revert "fix: Update Remaining Comparisons with FirstPullRequest Spread"

- src/pages/CommitDetailPage/CommitDetailPage.spec.jsx
Trying to get rid of the last remaining flaky tests.
> fix: Cleaning up remaining flaky tests

- package-lock.json
- package.json
Just a quick dependency update for PostCSS.
> build: Update PostCSS

- src/pages/CommitDetailPage/CommitDetailPage.spec.jsx
- src/pages/RepoPage/RepoPage.spec.jsx
They're currently flaky and breaky so this is an attempt to fix it.
> fix: Attempting to fix CommitDetailPage Tests

- src/pages/PullRequestPage/subroute/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.spec.js
> fix: Attempt to fix useIndirectChangedFilesTable flaky test

- src/services/pull/index.js
- src/services/pull/usePullComponents.spec.tsx
- src/services/pull/usePullComponents.tsx
We need to fetch name of components to display for the components selector
- Create new hook 
- Tests
> feat: Create a new hook for the components selector hook 

- src/pages/PullRequestPage/subroute/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.spec.js
> fix: Update to skip the annoying test

- codecov.yml
Some quick tweaks to the Codecov yaml file. Adding in the new AI comment feature, as well as fixing up some of the ignores that weren't being applied anymore because the files were moved over to TS from JS.
- Add AI comment preview feature
- Fix up ignores to fix coverage issues
> build: Few tweaks to Codecov yaml

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
- Makefile
- docker/start-nginx.sh
Allow self hosted users to configure their GHE/GLE/BBS host to fix links in app
Set env var(s) on frontend container:
```
CODECOV_GHE_HOST: "YOURGHE"
CODECOV_GLE_HOST: "YOURGLE"
CODECOV_BBS_HOST: "YOURBBS"
```
Note that the scheme (`https://`) is auto prepended.
> Add sed for vcs

- src/pages/RepoPage/NewRepoTab/GitHubActions/GitHubActions.spec.tsx
- src/pages/RepoPage/NewRepoTab/GitHubActions/GitHubActions.tsx
> revert: Revert upload token to repo token

- src/mocks/handlers.js
This PR adds in a couple MSW queries that can be used if working on bundle analysis work will the API work is being finalized.
Add in new handlers that can be optional used if working on bundle analysis work will the API is still being worked on.
> feat: Add in new MSW mocks for bundle analysis work

- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/BundleOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.spec.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/RollupOnboarding.tsx
- src/pages/RepoPage/BundlesTab/BundleOnboarding/RollupOnboarding/index.ts
>[!warning]
>Needs #2513 to be merged first
This PR adds in the onboarding for users using the Rollup bundler.
GH codecov/engineering-team#1043
- Create `RollupOnboarding` component
- Update `BundleOnboarding` component
- Added/updated some tests
> feat: Create Rollup plugin onboarding steps

- .github/workflows/ci.yml
- docker/Dockerfile
- package-lock.json
- package.json
This PR updates the version of `@codecov/webpack-plugin` as well as move things over to Node 20 from 18.
> build: Move bundler plugin to beta version and move to Node 20

- .github/workflows/ci.yml
- craco.stats.config.js
- package.json
Update the CI pipeline to also upload bundle stats to plain old Codecov
> build: Setup Gazebo to upload stats to prod

- src/ui/Modal/Modal.tsx
Super small fix to fix z-index issues for the model
Closes codecov/engineering-team#1335
> fix: Bump up the z-index of the model a little bit

- src/pages/PullRequestPage/Dropdowns/PullBundleDropdown.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleAnalysis.spec.tsx
- src/pages/PullRequestPage/PullRequestPage.spec.tsx
- src/services/pull/usePullBADropdownSummary.spec.tsx
- src/services/pull/usePullBADropdownSummary.tsx
Small change to use new change field for the pull bundle dropdown summary.
- Update summary hook to fetch in data from new fields
- Update pull bundle message to access new fields
- Update tests
> ref: Update pull bundle summary to use new data

- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleComparisonTable/PullBundleComparisonTable.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleComparisonTable/PullBundleComparisonTable.tsx
- src/services/pull/usePullBundleComparisonList.spec.tsx
- src/services/pull/usePullBundleComparisonList.tsx
This is another PR where we're just updating the hook to grab the data from new GraphQL fields from the API.
- Update hook to fetch data from new fields
- Update table to use new fields
- Update tests
> ref: Update pull bundle comparison list hook

- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleHeadTable/PullBundleHeadTable.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleHeadTable/PullBundleHeadTable.tsx
- src/services/pull/usePullBundleHeadList.spec.tsx
- src/services/pull/usePullBundleHeadList.tsx
Quick PR to update the pull head table data fetching hook so that we're using the latest fields to grab bundle information from.
- Update hook to grab data from new fields
- Update table to use new fields from API response
- Update tests
> ref: Update pull bundle head list hook

- src/shared/ListRepo/ReposTable/ReposTable.tsx
> Move loading spinner on repo page to center

- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.tsx
> Revert "don't get planData if user is not in org"

- src/shared/GlobalTopBanners/TrialBanner/TrialBanner.tsx
> Revert "Revert "don't get planData if user is not in org""

- src/services/account/useAccountDetails.ts
> make nullish to avoid error

- src/pages/RepoPage/BundlesTab/BundleContent/AssetsTable/AssetsTable.tsx
- src/pages/RepoPage/BundlesTab/BundleContent/EmptyTable/EmptyTable.tsx
- src/ui/Table/Table.css
- tailwind.config.js
This PR doesn't just fix the Bundles tab table ... but also tables across the app
- Tweak Table.css
- Tweak tailwind config
- Fix Asset, and Empty Table
Before
After
Before
After
> fix: Table styles and bundles tab tables

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/BillingDetails.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/BillingDetails/PaymentCard/PaymentCard.jsx
- src/services/account/useAccountDetails.ts
Make `invoicePdf` field nullable in `useAccountDetails`
> fix: Make invoice pdf nullable in use account details

- src/shared/GlobalTopBanners/GlobalTopBanners.spec.tsx
- src/shared/GlobalTopBanners/GlobalTopBanners.tsx
> Revert "[fix] Show install help banner in global top banners"

- src/layouts/Header/Dropdown.spec.jsx
- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useNavLinks.spec.js
This reverts commit c0dd9e3e8d947f1fcc7aeaed65dbbffd27787551.
> Revert change to logout button

- src/pages/AdminSettings/AdminAccess/AdminAccessTable/AdminAccessTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTable/FilesChangedTable.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/FilesChangedTab/FilesChangedTableTeam/FilesChangedTableTeam.tsx
- src/pages/CommitDetailPage/CommitCoverage/routes/IndirectChangesTab/IndirectChangesTable/IndirectChangesTable.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/PullBundleComparisonTable/PullBundleComparisonTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/CommitsTab/CommitsTableTeam/CommitsTableTeam.tsx
- src/pages/PullRequestPage/PullCoverage/routes/ComponentsTab/ComponentsTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FilesChangedTable/FilesChangedTable.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/TableTeam/TableTeam.tsx
- src/pages/PullRequestPage/PullCoverage/routes/FlagsTab/FlagsTab.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/IndirectChangedFiles.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.tsx
- src/pages/RepoPage/PullsTab/PullsTable/PullsTable.tsx
- src/pages/RepoPage/PullsTab/PullsTableTeam/PullsTableTeam.tsx
- src/shared/ListRepo/ReposTable/ReposTable.tsx
- src/shared/ListRepo/ReposTableTeam/ReposTableTeam.tsx
Just making sure that we import the table css everywhere and in a clear way
> fix: Ensure that table css is always imported

- package-lock.json
Closes https://github.com/codecov/internal-issues/issues/367
> Update follow-redirects to 1.15.6

- package-lock.json
Updating Express, and Webpack Dev Middleware.
> fix: Update Express, and Webpack Dev Middleware

- package-lock.json
- package.json
> Add class-variance-authority (aliased as cva)

- package-lock.json
Update node-tar to resolve dependabot vulnerability.
Closes https://github.com/codecov/internal-issues/issues/413
> Update tar sub-dependency

- .storybook/manager.ts
- .storybook/preview.tsx
- src/ui/Card/Card.spec.tsx
- src/ui/Card/Card.stories.tsx
- src/ui/Card/Card.tsx
- src/ui/Card/index.ts
First draft- looking for some feedback!
[Design](https://www.figma.com/file/JOS1ZW499rfWP9nT7ivjf8/Pavilion%3A-Codecov-Design-System-Library?type=design&node-id=4318-3234&mode=design&t=2OTkMmq90kms8llt-0)
The code was copied from [shadcn/ui](https://ui.shadcn.com/docs/components/card) and I added CVA, implemented our styles, and adjusted some types.
I've used CVA across the board because it gives us class overriding via the className prop for free, starting with things like this also makes it really easy to add variants in the future, should the need arise.
I've overwritten the existing card component, but still need to go back and check that old instances of it look fine with the new styles/api.
Storybook screenshot:
Closes https://github.com/codecov/engineering-team/issues/1456
> Implement Card component

- package-lock.json
- package.json
Required for RadioButtonGroup component that is incoming.
> Install radix-ui react radio group

- .github/workflows/ci.yml
> Add merge group to ci

- package-lock.json
- package.json
Install tailwind-merge. To be used with new components and beyond.
> feat: Install tailwind-merge

- src/services/charts/useBranchCoverageMeasurements.tsx
Updates useBranchCoverageMeasurements hook to use Repository over RepositoryDeprecated in query.
> ref: Use Repository instead of RepositoryDeprecated in useBranchCoverageMeasurements

- src/pages/CommitDetailPage/CommitCoverage/routes/CommitDetailFileExplorer/CommitDetailFileExplorerTable.spec.tsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/IndirectChangedFiles/hooks/useIndirectChangedFilesTable.spec.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/CodeTreeTable/CodeTreeTable.spec.tsx
- src/pages/RepoPage/CoverageTab/subroute/FileExplorer/FileListTable/FileListTable.spec.tsx
- **Fix coverage tab file list table**
- **Fix coverage tab code tree table tests**
- **Fix pull indirect changed files table**
- **Fix commit file explorer table**
> fix: Flaky tests around file explorer tables

- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationBanner.spec.tsx
https://github.com/codecov/gazebo/actions/runs/8987888349/job/24687494678?pr=2852
> fix: A potential fix for the flaky test

- src/pages/PullRequestPage/PullCoverage/routes/FileExplorer/FileExplorer.spec.tsx
- src/pages/RepoPage/CoverageOnboarding/ActivationBanner/ActivationBanner.spec.tsx
Updates some weird testing stuff here. Hopefully fixes a potentially flaky test.
> ref: Clean up pull file explorer tests

- src/globals.css
Some unknown changes were made in V8 to the feedback widget, this PR fixes those changes to the styles that were changed in the full release.
- Small style tweaks
> fix: Small tweak to align with V8 changes

- craco.config.js
- src/sentry.ts
Source maps are acting up again let's see if we can fix them.
> fix: Taking another peak at Sentry sourcemaps

- src/ui/SummaryDropdown/SummaryDropdown.tsx
Small tweaks to bring `SummaryDropdown` up to date with our latest tooling.
- Swap to `cva`
- Swap to `cn`
> ref: Small updates to SummaryDropdown

- package-lock.json
- package.json
- src/services/pathContents/branch/dir/useRepoBranchContents.tsx
Small change adding in a custom span for tracing the `BranchContents` query so we can better investigate as to what is causing slow loading times for this request.
> feat: Add in span for branch contents request

- src/pages/CommitDetailPage/CommitBundleAnalysis/BundleMessage/BundleMessage.spec.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/BundleMessage/BundleMessage.tsx
- src/pages/CommitDetailPage/CommitBundleAnalysis/CommitBundleAnalysis.spec.tsx
- src/pages/CommitDetailPage/Dropdowns/CommitBundleDropdown.spec.tsx
- src/pages/PullRequestPage/Dropdowns/PullBundleDropdown.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.spec.tsx
- src/pages/PullRequestPage/PullBundleAnalysis/BundleMessage/BundleMessage.tsx
Just removing references of `sizeDelta` as we are removing this from the API.
> chore: Remove size delta references

- package-lock.json
This PR updates the version of WS
> chore: Update WS

- craco.config.js
- craco.stats.config.js
- package-lock.json
- package.json
- src/sentry.ts
This PR removes Spotlight, as we're not really using it, and just looking to clean up some stuff.
> chore: Remove spotlight

- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/TeamPlanSpecialOffer/TeamPlanCard/TeamPlanCard.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/EnterprisePlanCard/EnterprisePlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/FreePlanCard.spec.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradePro/PlanUpgradePro.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/FreePlanCard/PlanUpgradeTeam/PlanUpgradeTeam.jsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/CurrentPlanCard/PaidPlanCard/PaidPlanCard.tsx
- src/shared/plan/ScheduledPlanDetails/ScheduledPlanDetails.jsx
Closes https://github.com/codecov/engineering-team/issues/1818
Points 2-4 in https://www.figma.com/design/jUKX9i3Lcgq7VE0zpwUxXM/GH-1508?node-id=1-464&t=KNhvhOsH2C5wPvXm-1
> feat: plan cards styling changes

- src/layouts/Header/components/AdminLink/AdminLink.tsx
- src/layouts/OldHeader/AdminLink.tsx
Fixes wrong variant added by accident.
> fix: Oldheader admin link has wrong link variant

- src/services/charts/useBranchCoverageMeasurements.tsx
Quick fix to make these query vars nullable
> fix: Make before and after nullable

- .eslintrc.json
- package.json
- yarn.lock
> fix: Slow tailwind eslint rule

- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/components/FeatureGroup/FeatureGroup.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/components/FeatureItem/FeatureItem.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/components/FeatureItem/FeatureItem.tsx
- src/services/navigation/useNavLinks/useStaticNavLinks.js
Implement Codecov integrations feature group for configuration manager.
[Design](https://www.figma.com/design/JTajBZUaEeqfijoy1mCDsz/GH-1509?node-id=99-500&t=s353tqca2PXZhQOZ-0)
Closes https://github.com/codecov/engineering-team/issues/2111
> feat: Implement Codecov integrations feature group

- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.spec.tsx
- src/pages/RepoPage/SettingsTab/tabs/ConfigurationManager/ConfigurationManager.tsx
Implements Test analytics feature group in configuration manager.
[Design](https://www.figma.com/design/JTajBZUaEeqfijoy1mCDsz/GH-1509?node-id=1-238&t=s353tqca2PXZhQOZ-0)
Closes https://github.com/codecov/engineering-team/issues/2108
> feat: Implement Test analytics feature group

- src/pages/AccountSettings/tabs/OktaAccess/hooks/useOktaConfig.tsx
Fixes: https://codecov.sentry.io/share/issue/aed59a66817642b6823cffc3f2fc9486/ 
Requires: https://github.com/codecov/codecov-api/pull/719
> fix: Fix schema of isUserOktaAuthenticated so it accepts nullable returned values

- src/ui/CoverageAreaChart/CoverageAreaChart.jsx
- src/ui/Sparkline/Sparkline.tsx
Update the color for charts per ticket below
1. Flags e.g., at http://localhost:3000/github/codecov/codecov-api/flags
2. Repo coverage e.g., at http://localhost:3000/github/codecov/shared
3. Org analytics e.g., at http://localhost:3000/analytics/github/codecov
4. Components e.g., at http://localhost:3000/github/codecov/gazebo/components
Closes https://github.com/codecov/engineering-team/issues/1251
> style: Recolor time series charts

- src/App.spec.tsx
After some debugging, we are taking the L... for now 😤 
Closes https://github.com/codecov/engineering-team/issues/2270
> chore: Ignore flaky App.spec.tsx - AccountSettings test 

- src/shared/utils/prismLanguageMapper.spec.ts
- src/shared/utils/prismLanguageMapper.ts
Using Sentry I've been able to find some more languages that users are using that we don't support at the moment, so this PR adds in the latest ones I've seen.
- Add in more languages
- Add tags to Sentry message to better determine what we're missing and how many people are looking at that file type.
> chore: Add support for more languages 

- src/App.spec.tsx
- src/App.tsx
Followup to https://github.com/codecov/gazebo/pull/3131
> dev: remove test skip and move login tests to end

- src/services/navigation/useNavLinks/useNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.js
- src/services/navigation/useNavLinks/useStaticNavLinks.spec.js
- src/shared/GlobalTopBanners/GlobalTopBanners.spec.tsx
- src/shared/GlobalTopBanners/GlobalTopBanners.tsx
- src/shared/GlobalTopBanners/ProPlanFeedbackBanner/ProPlanFeedbackBanner.spec.tsx
- src/shared/GlobalTopBanners/ProPlanFeedbackBanner/ProPlanFeedbackBanner.tsx
- src/shared/GlobalTopBanners/ProPlanFeedbackBanner/index.ts
Adds a top banner linking pro plan users out to a survey.
[Design](https://www.figma.com/design/7UXH8qTtbsX5Vz0yYYEZVr/GH-1065?node-id=82-52&t=8ttjd5gntkZyOrM0-0)
> feat: Add Pro Plan feedback survey banner

- src/pages/AccountSettings/tabs/Admin/DetailsSection/DetailsSection.jsx
- src/pages/AccountSettings/tabs/Profile/NameEmailCard/NameEmailCard.jsx
- src/pages/AccountSettings/tabs/YAML/YAML.jsx
- src/pages/TermsOfService/TermsOfService.tsx
This PR updates the remaining uses of `formState.<field>` based off of #3139
- Update `DetailsSection`
- Update `NameEmailCard`
- Update `YAML`
- Update `TermsOfService`
> fix: Other instances of incorrect use of formState

- package.json
- yarn.lock
Small update to bring us to the latest version of the bundler plugins.
> chore: Bump to 1.0.0 of the Bundler Plugin

- src/pages/RepoPage/ConfigTab/tabs/ConfigurationManager/ConfigurationManager.tsx
Closes https://github.com/codecov/engineering-team/issues/2306
> fix: Differentiate flags vs components configuration description

- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/SpecialOffer/SpecialOffer.jsx
- src/pages/PlanPage/subRoutes/CancelPlanPage/subRoutes/TeamPlanSpecialOffer/TeamPlanSpecialOffer.tsx
Updates this color to be more apparent on dark mode
**BEFORE**
**AFTER**
> fix: Update cancel color for dark mode

- src/pages/RepoPage/CoverageOnboarding/GitHubActions/GitHubActions.tsx
See https://github.com/codecov/feedback/issues/18#issuecomment-2356635543
> fix: Pytest coverage command in onboarding

- src/ui/TruncatedMessage/TruncatedMessage.test.tsx
- src/ui/TruncatedMessage/hooks/useTruncation.test.ts
This PR updates the tests for the `ui/TruncatedMessages` to Vitest
- Update `useTruncation` to Vitest
- Update `TruncatedMessage` to Vitest
> chore: Update ui/TruncatedMessage tests to Vitest

- src/config.js
- src/index.tsx
- src/shared/utils/metrics.ts
Removes code used for cleaning up cookies used by old session expiry logic.
Closes https://github.com/codecov/engineering-team/issues/2046
> chore: Remove old session expiry cleanup code

- src/pages/CodecovAIPage/CodecovAIPage.test.tsx
This PR updates the tests in `pages/CodecovAIPage` to Vitest
> chore: Update pages/CodecovAIPage tests to Vitest

- src/ui/CopyClipboard/CopyClipboard.test.tsx
- src/ui/CopyClipboard/CopyClipboard.tsx
This PR updates the tests in `ui/CopyClipboard` to Vitest.
> chore: Update ui/CopyClipboard to Vitest

- src/services/access/constants.js
- src/services/access/constants.ts
- src/services/access/useDeleteSession.test.tsx
- src/services/access/useGenerateUserToken.test.jsx
- src/services/access/useRevokeUserToken.test.tsx
- src/services/access/useRevokeUserToken.ts
- src/services/access/useSessions.test.tsx
This PR updates the tests in `services/access` to Vitest.
> chore: Update services/access to Vitest

- package.json
- yarn.lock
Bump vite version to resolve vulnerability
Closes https://github.com/codecov/internal-issues/issues/800
Closes https://github.com/codecov/internal-issues/issues/801
> chore: Bump vite to resolve vulnerability

- src/pages/CodecovAIPage/CodecovAICommands/CodecovAICommands.tsx
- src/pages/CodecovAIPage/CodecovAIPage.test.tsx
> [fix] Adjust spacing on AI commands text

- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/FileDiff/FileDiff.jsx
- src/pages/PullRequestPage/PullCoverage/routes/IndirectChangesTab/FileDiff/FileDiff.test.jsx
This PR updates the diff used in the PR indirect changes tab to conditionally use the new virtual diff renderer.
- Update `FileDiff` to conditionally use new renderer
- Update tests
> chore: Update pulls page indirect changes diff to new renderer

- src/pages/PlanPage/subRoutes/CurrentOrgPlan/hooks/useEnterpriseAccountDetails.test.tsx
- src/pages/PlanPage/subRoutes/CurrentOrgPlan/hooks/useEnterpriseAccountDetails.ts
Adds useEnterpriseAccountDetails hook to be used for Multiple orgs UI.
Closes https://github.com/codecov/engineering-team/issues/2560
> feat: Add useEnterpriseAccountDetails hook

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/hooks/useInfiniteTestResults/useInfiniteTestResults.tsx
Handle merge conflicts from the GraphQL restructure into this `tests-analytics-v2` branch
> chore: Handle merge conflicts with graphql restructure

- docker/Dockerfile
- docker/start-nginx.sh
This PR moves the Dockerfile over to Vite, and as well updates the inline replacement string so that we can ensure that we replace the given strings in the correct directory.
Built and ran the docker image locally and it was all happy (minus API requests 😅)
> chore: Move Dockerfile over to Vite

- package.json
- yarn.lock
Small PR updating our versions of Rollup.
> chore: Update Rollup 10/11/2024

- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FileDiff/FileDiff.jsx
- src/pages/PullRequestPage/PullCoverage/routes/FilesChangedTab/FilesChanged/FileDiff/FileDiff.test.jsx
- Update `FileDiff` to conditionally use new virtual diff renderer
- Update tests
> chore: Update pulls page files changed diff to new renderer

- .eslintrc.cjs
- package.json
- src/layouts/Header/components/ThemeToggle/ThemeToggle.test.tsx
- src/shared/useDisablePointerEvents/useDisablePointerEvents.test.tsx
- src/ui/CodeRenderer/CodeRenderer.test.tsx
- src/ui/VirtualRenderers/VirtualDiffRenderer.test.tsx
- src/ui/VirtualRenderers/VirtualFileRenderer.test.tsx
- src/ui/VirtualRenderers/useLeftScrollSync.test.tsx
With the move to CRACO, I missed a couple things while migrating us over to Vite, and bringing some other configurations up to date.
- Fix lint command not working properly
- Fix issue in lint config not pointing to the correct tailwind config
- Resolve linting issues
> fix: Small Issues with Linter

- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/MetricsSection/MetricsSection.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/TableHeader/TableHeader.test.tsx
- src/pages/RepoPage/FailedTestsTab/FailedTestsPage/TableHeader/TableHeader.tsx
Reflect filters on tests header, update the tooltip 
> feat: Update with table tests header 

- src/shared/utils/billing.ts
Follows up to changes in here https://github.com/codecov/gazebo/pull/3461/files
Closes https://github.com/codecov/internal-issues/issues/1111
> fix: Add 'users' plan

- package.json
- yarn.lock
Bumping to the latest version of the bundler plugins.
> chore: Update Codecov Bundler Plugin

- src/services/events/amplitude/amplitude.ts
Sets Amplitude config to use new Amplitude proxy we've spun up
Closes https://github.com/codecov/infrastructure-team/issues/521
> feat: Use amplitude proxy

- .eslintrc.cjs
- package.json
- src/ui/VirtualRenderers/LineNumber.tsx
- src/ui/VirtualRenderers/VirtualFileRenderer.tsx
- yarn.lock
This PR simply updates the version of TanStack Virtual that seems to resolve all of the issues that we were running into. As well as a couple other small fixes that I added in while testing things/running into issues.
- Update TanStack Virtual Version
- Some type fixes alongside
- Remove extra space from classname in `VritualFileRenderer`
- Fix ESLint conflicting key issue
- Also fix casing rule so that it also works for string literals
Before:
https://github.com/user-attachments/assets/03bda447-d7c3-4a06-8936-8c176b976312
After:
https://github.com/user-attachments/assets/f535ee3b-c631-4a2b-abf4-1a47e91ae98a
> fix: Virtual file renderer not resetting when changing branch

- docker/start-nginx.sh
Fixes the sed command that replaces GHE/GLE/BBS links in the frontend for self-hosted.
Closes https://github.com/codecov/feedback/issues/600
> fix: sed command for self-hosted git provider replacement

- package.json
- yarn.lock
Fix vulnerability in cross-spawn library
Closes https://github.com/codecov/internal-issues/issues/1271
> chore: Fix vulnerability in cross-spawn lib

- package.json
- yarn.lock
Resolves [Dependabot Vulnerability | Repo: gazebo | Package/EcoSystem: vite/npm | Dependency_Alert_Number: 128](https://github.com/codecov/internal-issues/issues/1329)
> chore: Bump Vite version

- .github/workflows/cache_cleanup.yml
- .github/workflows/ci.yml
- .github/workflows/enforce-license-compliance.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
- .github/workflows/trigger-gazebo-preview.yml
> fix: add workflow permissions

- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
> updating the perms

- .env.development
> changing url

- .env.development
This reverts commit 7360dabcabb5bb3633ab0a47179b67f4e132a8a7.
> Revert "changing url (#3889)"

- src/pages/RepoPage/CoverageTab/FlagsTab/subroute/FlagsTable/DeleteFlagModal/DeleteFlagModal.tsx
Adds a little warning about flag deletion being permanent.
Closes https://github.com/codecov/engineering-team/issues/3586
> chore: Make flag deletion modal warn action is permanent
